QualityUnit/wp-urlslab

admin/class-urlslab-admin.php, admin/src/components/generator/ContentGeneratorConfigPanel.jsx, admin/src/tables/GeneratorPromptTemplateTable.jsx, includes/api/class-urlslab-api-generators.php
fixed bug with wp date
**Checklist**
=> Fixed Bug with state changes in Generator and 

admin/src/tables/SerpCompetitorsTable.jsx, admin/src/tables/SerpGapTable.jsx, admin/src/tables/SerpTopDomainsTable.jsx, includes/api/class-urlslab-api-serp-competitors.php, includes/api/class-urlslab-api-serp-domains.php
Close QualityUnit/web-issues#1886
=> fix:  competitors table

admin/src/assets/styles/components/_SerpPanel.scss, admin/src/components/detailsPanel/QueryDetailPanel.jsx, admin/src/lib/serpQueries.js, admin/src/tables/SerpQueryDetailSimQueryTable.jsx, admin/src/tables/SerpQueryDetailTopUrlsTable.jsx, includes/api/class-urlslab-api-serp-queries.php
=> Added Serp Popup Enhancement

admin/src/tables/SerpQueryDetailSimQueryTable.jsx, includes/api/class-urlslab-api-serp-queries.php
=> Query Optimization for similar keywords Popup

admin/src/assets/styles/components/_ModuleViewHeader.scss, admin/src/assets/styles/components/_TableComponent.scss, admin/src/components/ImportPanel.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/components/TableComponent.jsx, admin/src/components/TableFilter.jsx, admin/src/components/TableFilterPanel.jsx, admin/src/components/TablePanels.jsx, admin/src/elements/ColumnsMenu.jsx, admin/src/hooks/filteringSorting.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/hooks/useTableStore.jsx
Close QualityUnit/web-issues#1824
Close QualityUnit/web-issues#1826
Close QualityUnit/web-issues#1831
Close QualityUnit/web-issues#1835
=> fix: #1824, #1826, #1831, #1835

admin/apps/ai-content-assistant/src/elements/JSXElements.tsx, admin/src/components/TableFilter.jsx, admin/src/components/TableFilterPanel.jsx, admin/src/elements/Checkbox.jsx, admin/src/elements/TagsFilterMenu.jsx, admin/src/elements/TagsMenu.jsx, admin/src/hooks/filteringSorting.jsx, admin/src/hooks/useTags.jsx, admin/src/lib/filterOperators.js
features new filtering by tags
Close QualityUnit/web-issues#1877
=> [1877] feat: tags filter

admin/src/tables/SerpQueryDetailSimQueryTable.jsx, includes/api/class-urlslab-api-serp-queries.php
=> Keyword Cluster Keywords

admin/src/components/TableFilter.jsx, admin/src/elements/TagsFilterMenu.jsx
Bugfix for multiple filter and tag filter values sending
=> fix: tagfilter value sending and display

admin/src/components/Header.jsx, admin/src/components/MainMenu.jsx, admin/src/modules/CssOptimizer.jsx, includes/widgets/class-urlslab-cache.php, includes/widgets/class-urlslab-content-generator-widget.php, includes/widgets/class-urlslab-custom-html.php, includes/widgets/class-urlslab-faq.php, includes/widgets/class-urlslab-html-optimizer.php, includes/widgets/class-urlslab-image-alt-text.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-link-enhancer.php, includes/widgets/class-urlslab-media-offloader-widget.php, includes/widgets/class-urlslab-meta-tag.php, includes/widgets/class-urlslab-optimize.php, includes/widgets/class-urlslab-redirects.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-serp.php, urlslab.php
update labels and texts
**Checklist**
=> feat: update labels and texts

includes/widgets/class-urlslab-cache.php, includes/widgets/class-urlslab-content-generator-widget.php, includes/widgets/class-urlslab-html-optimizer.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-link-enhancer.php, includes/widgets/class-urlslab-media-offloader-widget.php, includes/widgets/class-urlslab-optimize.php, includes/widgets/class-urlslab-redirects.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-serp.php
change default settings
**Checklist**
=> feat: change default settings

admin/src/components/EditRowPanel.jsx
bug with button on add new row/schedule
Close QualityUnit/web-issues#1902
=> [1902] fix: bug with button on add new row/schedule

admin/apps/ai-content-assistant/src/components/MainSettings.tsx, admin/src/components/CronRunner.jsx, admin/src/components/generator/ContentGeneratorConfigPanel.jsx, admin/src/tables/CacheRulesTable.jsx, admin/src/tables/CustomHtmlTable.jsx, admin/src/tables/FaqsTable.jsx, admin/src/tables/GeneratorPromptTemplateTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx, admin/src/tables/GscSitesTable.jsx, admin/src/tables/SchedulesTable.jsx, admin/src/tables/SerpCompetitorsTable.jsx, admin/src/tables/SerpGapTable.jsx, admin/src/tables/SerpQueriesTable.jsx, admin/src/tables/SerpQueryDetailSimQueryTable.jsx, admin/src/tables/SerpQueryDetailTopUrlsTable.jsx, includes/api/class-urlslab-api-billing.php, includes/api/class-urlslab-api-schedules.php, includes/cron/class-urlslab-update-url-http-status-cron.php, includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-redirects.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-serp.php
reorder columns and settings
**Checklist**
=> feat: reorder columns and settings

admin/src/modules/static/TagsLabels.jsx
fixing tags manager wrong fetch parameters after merge
=> fix: tags manager

admin/src/hooks/filteringSorting.jsx, admin/src/modules/static/TagsLabels.jsx, admin/src/tables/CSSCacheTable.jsx, admin/src/tables/CacheRulesTable.jsx, admin/src/tables/ContentCacheTable.jsx, admin/src/tables/CreditsTable.jsx, admin/src/tables/CustomHtmlTable.jsx, admin/src/tables/FaqUrlsTable.jsx, admin/src/tables/GeneratorProcessesTable.jsx, admin/src/tables/GeneratorPromptTemplateTable.jsx, admin/src/tables/GeneratorResultTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx, admin/src/tables/GscSitesTable.jsx, admin/src/tables/JSCacheTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/MetaTagsTable.jsx, admin/src/tables/RedirectsTable.jsx, admin/src/tables/SchedulesTable.jsx, admin/src/tables/ScreenshotTable.jsx, admin/src/tables/SearchReplaceTable.jsx, admin/src/tables/SerpCompetitorsTable.jsx, admin/src/tables/SerpGapTable.jsx, admin/src/tables/SerpQueriesTable.jsx, admin/src/tables/SerpTopDomainsTable.jsx, admin/src/tables/SerpUrlsTable.jsx, admin/src/tables/URLRelationTable.jsx, admin/src/tables/UsageTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
filter editing saves as multiple filters. Fix for reloading old data on filtering
Close QualityUnit/web-issues#1889
=> [1889] fix: filter editing saves as multiple filters

admin/src/elements/RefreshTableButton.jsx, admin/src/elements/Tooltip_SortingFiltering.jsx, admin/src/hooks/useInfiniteFetch.jsx, admin/src/hooks/useTableStore.jsx, admin/src/tables/GeneratorResultTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx
show results button in ai shortcode table
Close QualityUnit/web-issues#1854
=> [1854] show results

includes/class-urlslab.php
**Checklist**
Close QualityUnit/web-issues#1960
=> bugfix#1960

admin/src/assets/styles/components/_OverviewTemplate.scss, admin/src/overview/Cache.jsx, admin/src/overview/CustomHtml.jsx, admin/src/overview/Faqs.jsx, admin/src/overview/Generator.jsx, admin/src/overview/HtmlOptimizer.jsx, admin/src/overview/ImageAltAttribute.jsx, admin/src/overview/KeywordsLinks.jsx, admin/src/overview/LazyLoading.jsx, admin/src/overview/LinkEnhancer.jsx, admin/src/overview/MediaOffloader.jsx, admin/src/overview/MetaTag.jsx, admin/src/overview/Optimize.jsx, admin/src/overview/Redirects.jsx, admin/src/overview/RelatedResources.jsx, admin/src/overview/Schedules.jsx, admin/src/overview/Screenshot.jsx, admin/src/overview/SearchAndReplace.jsx, admin/src/overview/Serp.jsx
rewrite overview texts
**Checklist**
Close QualityUnit/web-issues#1901
=> [1901] feat: rewrite overview texts

admin/src/assets/styles/components/_DateRangePicker.scss, admin/src/components/ChangesPanel/ChangesPanel.jsx, admin/src/components/ImageCompare.jsx, admin/src/elements/SingleSelectMenu.jsx, admin/src/hooks/useChangeRow.jsx
Fixed bug with Show Difference
**Checklist**
Close QualityUnit/web-issues#1925
Close QualityUnit/web-issues#1843
=> Bug fix show difference

admin/src/assets/styles/components/_DateRangePicker.scss, admin/src/components/ChangesPanel/ChangesPanel.jsx, admin/src/components/ImageCompare.jsx
**Checklist**
Close QualityUnit/web-issues#1843
=> Fixed bugs in changes panel

admin/src/assets/styles/components/_Panel.scss, admin/src/components/EditRowPanel.jsx, admin/src/tables/CustomHtmlTable.jsx
section split in code injection
**Checklist**
Close QualityUnit/web-issues#1916
=> [1916] feat: section split in code injection

admin/src/components/SettingsOption.jsx, admin/src/lib/filterOperators.js, includes/api/class-urlslab-api-table-sql.php, includes/driver/class-urlslab-driver.php, includes/widgets/class-urlslab-html-optimizer.php
Bug fixes
**Checklist**
Close QualityUnit/web-issues#1970
Close QualityUnit/web-issues#1905
Close QualityUnit/web-issues#1904
Close QualityUnit/web-issues#1896
Close QualityUnit/web-issues#1879
=> Bug Fixes Backend

admin/src/tables/GeneratorResultTable.jsx, includes/api/class-urlslab-api-cache-rules.php, includes/api/class-urlslab-api-content-cache.php, includes/api/class-urlslab-api-cron.php, includes/api/class-urlslab-api-css-cache.php, includes/api/class-urlslab-api-custom-html.php, includes/api/class-urlslab-api-faq-urls.php, includes/api/class-urlslab-api-files.php, includes/api/class-urlslab-api-generators.php, includes/api/class-urlslab-api-gsc-sites.php, includes/api/class-urlslab-api-js-cache.php, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-labels.php, includes/api/class-urlslab-api-modules.php, includes/api/class-urlslab-api-not-found-log.php, includes/api/class-urlslab-api-redirects.php, includes/api/class-urlslab-api-schedules.php, includes/api/class-urlslab-api-serp-competitors.php, includes/api/class-urlslab-api-serp-domains.php, includes/api/class-urlslab-api-serp-gap.php, includes/api/class-urlslab-api-serp-queries.php, includes/api/class-urlslab-api-serp-urls.php, includes/api/class-urlslab-api-settings.php, includes/api/class-urlslab-api-shortcodes.php, includes/api/class-urlslab-api-table-sql.php, includes/api/class-urlslab-api-table.php, includes/api/class-urlslab-api-urls.php, includes/class-urlslab-available-widgets.php, includes/exceptions/class-urlslab-bad-request-exception.php
**Checklist**
Close QualityUnit/web-issues/issues/1976
=> Added bugfix database error response

includes/api/class-urlslab-api-urls.php
**Checklist**
Close QualityUnit/web-issues#1951
=> Fix SEO Rank

admin/src/tables/GeneratorResultTable.jsx, includes/api/class-urlslab-api-generators.php
Generator Bug fix
**Checklist**
=> bug fix for generator

admin/src/components/DetailsPanel.jsx, admin/src/components/TablePanels.jsx, admin/src/elements/SuggestInputField.jsx, admin/src/tables/GeneratorResultTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/NotFoundTable.jsx
Close QualityUnit/web-issues#1952
Close QualityUnit/web-issues#1964
=> fix: #1952, #1964

includes/widgets/class-urlslab-cache.php, includes/widgets/class-urlslab-lazy-loading.php
=> Comment rewritten

admin/src/components/EditRowPanel.jsx, admin/src/elements/TagsMenu.jsx, admin/src/tables/CacheRulesTable.jsx, admin/src/tables/CustomHtmlTable.jsx, admin/src/tables/RedirectsTable.jsx
Close QualityUnit/web-issues#1940
Close QualityUnit/web-issues#1959
=> fix: #1940, #1959

admin/src/assets/styles/common/_global.scss, admin/src/assets/styles/components/_Panel.scss
Please try tall modals on small screens
Close QualityUnit/web-issues#1883
=> [1883] fix: modal panel not centered vertically on scroll

admin/src/assets/styles/common/_colorClasses.scss, admin/src/assets/styles/common/_variables.scss, admin/src/components/SettingsOption.jsx, admin/src/components/TableFilterPanel.jsx, admin/src/elements/Editor.jsx, admin/src/elements/InputField.jsx, admin/src/elements/MultiSelectMenu.jsx, admin/src/elements/SingleSelectMenu.jsx, admin/src/elements/TagsFilterMenu.jsx, admin/src/elements/TagsMenu.jsx, admin/src/elements/TextAreaEditable.jsx, admin/src/elements/Textarea.jsx, admin/src/modules/static/Modules.jsx
Close QualityUnit/web-issues#1982
Close QualityUnit/web-issues#1983
Close QualityUnit/web-issues#1984
Close QualityUnit/web-issues#1987
=> Bugfixes september v8

includes/api/class-urlslab-api-shortcodes.php
=> fix shortcode

includes/api/class-urlslab-api-faq-urls.php, includes/class-urlslab-augment-connection.php, includes/class-urlslab-serp-connection.php, includes/class-urlslab-summaries-helper.php, includes/class-urlslab-yt-helper.php
**Checklist**
Close QualityUnit/web-issues#2003
=> bugfix ai generator and faq

admin/src/app/mui_joy/theme.js, admin/src/components/generator/ContentGeneratorConfigPanel.jsx, admin/src/components/generator/manual/ContentGeneratorManual.jsx, admin/src/components/generator/manual/StepFirst.jsx, admin/src/components/generator/manual/StepSecond.jsx, admin/src/components/generator/manual/StepThird.jsx, admin/src/components/generator/scalable/ContentGeneratorScalable.jsx, admin/src/components/generator/scalable/StepFirst.jsx, admin/src/components/generator/scalable/StepSecond.jsx, admin/src/components/generator/usePromptTemplateEditorRow.jsx, admin/src/hooks/useAIGenerator.jsx, admin/src/hooks/useAIGeneratorManualInit.jsx, admin/src/lib/aiGeneratorPanel.js, admin/src/lib/serpQueries.js, admin/src/lib/tableImports.js, admin/src/queries/usePromptTemplateQuery.jsx, admin/src/tables/FaqsTable.jsx, includes/api/class-urlslab-api-generators.php, includes/api/class-urlslab-api-serp-queries.php
Fixed generator in popup to generate answers for FAQ questions.
First release, there are still things to improve...
Close QualityUnit/web-issues#2010
=> FAQ popup Answer Generation 

includes/cron/class-urlslab-related-resources-cron.php
**Checklist**
Close QualityUnit/web-issues#1605
=> Added filtering of related articles for index pages

admin/src/assets/styles/components/_ChangesPanel.scss, admin/src/assets/styles/components/_ColorPicker.scss, admin/src/elements/DateTimeFormat.jsx, admin/src/elements/TagsMenu.jsx, admin/src/hooks/useTags.jsx, admin/src/modules/static/TagsLabels.jsx, admin/src/tables/GeneratorProcessesTable.jsx, admin/src/tables/GscSitesTable.jsx, admin/src/tables/UsageTable.jsx
Close QualityUnit/web-issues#2008
Close QualityUnit/web-issues#2015
Close QualityUnit/web-issues#2016
Close QualityUnit/web-issues#2017
Close QualityUnit/web-issues#2018
Close QualityUnit/web-issues#2019
=> fix: #2008, #2015, #2016, #2017, #2018, #2019

admin/src/app/mui_joy/theme.js, admin/src/tables/SerpGapTable.jsx
Fixed error on SERP Content Gap table. Error was present when `Create Content` button was available in row.
Close QualityUnit/web-issues#2022
=> SERP Content Gap table error

includes/widgets/class-urlslab-content-generator-widget.php
Close https://github.com/QualityUnit/web-issues/issues/2024
=> fix: php fatal error

includes/api/class-urlslab-api-gsc-sites.php, includes/api/class-urlslab-api-table-sql.php, includes/widgets/class-urlslab-serp.php
Close QualityUnit/web-issues#1920
=> fix: php fatal error and deadlock

admin/src/components/TableFilterPanel.jsx, admin/src/lib/filterOperators.js, admin/src/tables/GeneratorShortcodeTable.jsx, includes/api/class-urlslab-api-generators.php, includes/api/class-urlslab-api-shortcodes.php, includes/api/class-urlslab-api-table-sql.php
Close https://github.com/QualityUnit/web-issues/issues/1829
=> fix: php fatal error and filters

admin/src/assets/styles/components/_MainMenu.scss, admin/src/assets/styles/components/_ModuleViewHeader.scss, admin/src/components/MainMenu.jsx, admin/src/components/ModuleViewHeader.jsx, admin/src/elements/SuggestInputField.jsx, admin/src/elements/TagsMenu.jsx, admin/src/hooks/useTableStore.jsx, admin/src/hooks/useTags.jsx, admin/src/modules/static/Modules.jsx, admin/src/modules/static/TagsLabels.jsx, admin/src/queries/usePrefetchQueries.jsx, admin/src/tables/CustomHtmlTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/MetaTagsTable.jsx
Close QualityUnit/web-issues#1994
Close QualityUnit/web-issues#2006
Close QualityUnit/web-issues#2017
Close QualityUnit/web-issues#2023
Close QualityUnit/web-issues#2025
Close QualityUnit/web-issues#2026
=> fix: #1994, #2006, #2017, #2023, #2025, #2026

admin/src/tables/MediaFilesTable.jsx, admin/src/tables/UsageTable.jsx
Close QualityUnit/web-issues#2013
Close QualityUnit/web-issues#2014
=> [2013] fix: pagination in usage table

admin/src/lib/helpers.js
=> bugfix with lang code parsing

includes/api/class-urlslab-api-cache-rules.php, includes/widgets/class-urlslab-cache.php
Close QualityUnit/web-issues#2032
=> fix: dropping all objects in cloudfront

table-names.php, uninstall.php
Close https://github.com/QualityUnit/web-issues/issues/2039
=> fix: duplicate table constant

includes/api/class-urlslab-api-serp-queries.php
Close https://github.com/QualityUnit/web-issues/issues/2040
=> fix: php warning

admin/src/assets/styles/elements/_Tooltip.scss, admin/src/elements/TooltipArray.jsx, admin/src/elements/TooltipUrls.jsx, admin/src/lib/tableImports.js, admin/src/tables/SerpQueriesTable.jsx, admin/src/tables/SerpUrlsTable.jsx, includes/api/class-urlslab-api-serp-queries.php, includes/api/class-urlslab-api-serp-urls.php
Close https://github.com/QualityUnit/web-issues/issues/2041
=> url rendering

admin/src/tables/LinkManagerTable.jsx, includes/api/class-urlslab-api-urls.php
Close QualityUnit/web-issues#2042
=> feat: show serp data in url monitoring

admin/src/tables/LinkManagerTable.jsx, admin/src/tables/SerpQueriesTable.jsx, admin/src/tables/SerpUrlsTable.jsx, includes/api/class-urlslab-api-serp-urls.php, includes/api/class-urlslab-api-urls.php, includes/class-urlslab-activator.php, includes/data/class-urlslab-keyword-row.php, includes/data/class-urlslab-serp-query-row.php, includes/data/class-urlslab-serp-url-row.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2043
=> feat: my urls ranking in top10 and top100

includes/api/class-urlslab-api-serp-queries.php
join problem
https://github.com/QualityUnit/web-issues/issues/2045
=> fix: column format for my_urls

admin/src/lib/helpers.js
=> Removed and rolled back the lang code

includes/widgets/class-urlslab-faq.php
Close https://github.com/QualityUnit/web-issues/issues/1847
=> feat: allow formatting of header

admin/src/lib/helpers.js
=> [2035] fix: error on wrong language

includes/cron/class-urlslab-serp-cron.php
Close https://github.com/QualityUnit/web-issues/issues/2055
=> fix: handling of query status in case of error

admin/src/components/MainMenu.jsx
main menu collapsing – could not reproduce anymore
Close QualityUnit/web-issues#2052
=> [2052] fix: main menu collapsing

admin/src/components/detailsPanel/QueryDetailPanel.jsx, admin/src/lib/serpQueries.js, admin/src/tables/GscSitesTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/SerpQueriesTable.jsx, admin/src/tables/SerpQueryDetailSimQueryTable.jsx, admin/src/tables/SerpQueryDetailTopUrlsTable.jsx, admin/src/tables/SerpUrlsTable.jsx, composer.lock, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-process.php, includes/api/class-urlslab-api-serp-queries.php, includes/api/class-urlslab-api-serp-urls.php, includes/api/class-urlslab-api-urls.php, includes/class-urlslab-activator.php, includes/class-urlslab-serp-connection.php, includes/class-urlslab.php, includes/cron/class-urlslab-gsc-cron.php, includes/cron/class-urlslab-serp-cron.php, includes/data/class-urlslab-gsc-position-row.php, includes/data/class-urlslab-serp-position-history-row.php, includes/data/class-urlslab-serp-position-row.php, includes/data/class-urlslab-serp-query-row.php, includes/data/class-urlslab-serp-url-row.php, includes/widgets/class-urlslab-serp.php, table-names.php, urlslab.php
**Checklist**
Close QualityUnit/web-issues#2058
=> SERP data changes

admin/src/components/EditRowPanel.jsx, admin/src/components/Header.jsx, admin/src/components/TableComponent.jsx, admin/src/components/TableRow.jsx, admin/src/elements/InputField.jsx, admin/src/tables/KeywordsTable.jsx
Moved table row to separate component.
Removed input lag in Add/Edit panel
=> Table performance improvements

admin/src/components/TableBody.jsx, admin/src/components/TableComponent.jsx, admin/src/components/TableHead.jsx, admin/src/components/TableRow.jsx
Optimized whole TableComponent rerenders during scroll in table.
=> fix:  unwanted table component rerenders during scroll

admin/src/components/TableComponent.jsx, admin/src/components/TableRow.jsx, admin/src/tables/CSSCacheTable.jsx, admin/src/tables/CacheRulesTable.jsx, admin/src/tables/ContentCacheTable.jsx, admin/src/tables/CustomHtmlTable.jsx, admin/src/tables/FaqUrlsTable.jsx, admin/src/tables/FaqsTable.jsx, admin/src/tables/GeneratorProcessesTable.jsx, admin/src/tables/GeneratorPromptTemplateTable.jsx, admin/src/tables/GeneratorResultTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx, admin/src/tables/GscSitesTable.jsx, admin/src/tables/JSCacheTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/MetaTagsTable.jsx, admin/src/tables/NotFoundTable.jsx, admin/src/tables/RedirectsTable.jsx, admin/src/tables/SchedulesTable.jsx, admin/src/tables/ScreenshotTable.jsx, admin/src/tables/SearchReplaceTable.jsx, admin/src/tables/SerpCompetitorsTable.jsx, admin/src/tables/SerpQueriesTable.jsx, admin/src/tables/SerpQueryDetailSimQueryTable.jsx, admin/src/tables/SerpTopDomainsTable.jsx, admin/src/tables/SerpUrlsTable.jsx, admin/src/tables/URLRelationTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
Implements loading more data before actually scrolling completely to the bottom, so user doesn't have to wait for more rows so long
=> feat: infinite fetching another page before scrolling to bottom

admin/src/components/TableComponent.jsx, admin/src/components/TableRow.jsx
moving individual cells to component
=> feat: moving individual cells to component

admin/src/tables/KeywordsTable.jsx, includes/api/class-urlslab-api-keywords.php
removed the column until we will find better way how to present information about keyword
Close QualityUnit/web-issues#2073
=> fix: removed serp intersection of keywords

admin/src/tables/SerpTopDomainsTable.jsx, admin/src/tables/SerpUrlsTable.jsx, includes/api/class-urlslab-api-table-sql.php
**Checklist**
Close QualityUnit/web-issues#2067
=> fix: filter validation and change of domain category name

admin/src/tables/SerpQueriesTable.jsx, includes/api/class-urlslab-api-serp-queries.php, includes/class-urlslab-activator.php, includes/data/class-urlslab-serp-query-row.php, urlslab.php
Close QualityUnit/web-issues#2074
=> feat: show number of internal links

includes/api/class-urlslab-api-serp-queries.php
Close QualityUnit/web-issues#2075
=> fix: fatal error with type

includes/class-urlslab-activator.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2077
=> fix: rename column again with different syntax

includes/widgets/class-urlslab-link-enhancer.php
Close https://github.com/QualityUnit/web-issues/issues/2076
=> fix: load title of page by rescanning the page in cron 

includes/widgets/class-urlslab-cache-widget.php, includes/widgets/class-urlslab-general.php, includes/widgets/class-urlslab-image-alt-text.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-link-enhancer.php, includes/widgets/class-urlslab-media-offloader-widget.php, includes/widgets/class-urlslab-widget.php
**Checklist**
Close QualityUnit/web-issues#2078
=> skip css classname setting to skip processing

admin/src/components/EditRowPanel.jsx
textarea and tinymce fix
Close QualityUnit/web-issues#2051
=> [2051] fix: textarea and tinymce fix

admin/src/components/TableRow.jsx
Fixed table rows after adding new columns into table.
Memoized TableRow didn't know about added columns, was not updated with parent...
Close QualityUnit/web-issues#2080
=> fix: memoized table row do not update after columns adding

admin/src/components/EditRowPanel.jsx, admin/src/components/TableComponent.jsx, admin/src/components/TableHead.jsx
Fixed error with adding new table row from last PR: https://github.com/QualityUnit/wp-urlslab/pull/1197
As a part of this pr fixed also QualityUnit/web-issues#2084
Table header cells width calculation extracted into TableHead component to ensure that cells calculation effect runs only if needed.
Close QualityUnit/web-issues#2083
Close QualityUnit/web-issues#2084
=> [i2083, i2084] fix: adding new table row error, table header cells width calculation

admin/src/components/EditRowPanel.jsx, includes/cron/executor/class-urlslab-generator-cron-executor.php, includes/widgets/class-urlslab-content-generator-widget.php
=> Fixed bug with shortcode generator

admin/src/api/fetchDataForProcessing.js, admin/src/components/RowCounter.jsx, admin/src/elements/RefreshTableButton.jsx, admin/src/elements/TableSortBy.jsx, admin/src/elements/Tooltip_SortingFiltering.jsx, admin/src/hooks/filteringSorting.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/hooks/useInfiniteFetch.jsx, admin/src/hooks/useTableStore.jsx, admin/src/lib/filtersArray.js, admin/src/lib/serpQueries.js, admin/src/tables/SerpQueryDetailSimQueryTable.jsx, admin/src/tables/SerpQueryDetailTopUrlsTable.jsx
Added support for sorting in secondary tables
=> feat: sorting support in secondary tables

admin/src/tables/SerpUrlDetailSimilarUrlsTable.jsx
=> fix: formatting

admin/src/components/ChangesPanel/ChangesPanel.jsx, admin/src/components/ImageCompare.jsx, admin/src/elements/DeleteSelectedButton.jsx, admin/src/elements/RefreshTableButton.jsx, admin/src/elements/RowActionButtons.jsx, admin/src/elements/Tooltip_SortingFiltering.jsx, admin/src/hooks/filteringSorting.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/hooks/useTableStore.jsx, admin/src/tables/SerpUrlDetailQueryTable.jsx, admin/src/tables/SerpUrlDetailSimilarUrlsTable.jsx, admin/src/tables/SerpUrlsTable.jsx
Fixed not defined default states for filters, sorting and selected rows, which caused optimistic update to fail
Close QualityUnit/web-issues#2088
=> [2088] tags deletion not working

admin/src/tables/NotFoundTable.jsx, admin/src/tables/RedirectsTable.jsx
Fixed infinite `useEffect` loop.
Fixed missing deps in effect for 404 Monitor table.
=> Bugfix infinite effect loop

admin/src/assets/styles/components/_ImageCompare.scss, admin/src/components/ChangesPanel/ChangesPanel.jsx, admin/src/components/ImageCompare.jsx, admin/src/tables/LinkManagerTable.jsx
**Checklist**
Close QualityUnit/web-issues#2094
=> Image Comparator Bug fixes

admin/package.json, admin/src/assets/styles/components/_TableComponent.scss, admin/src/components/DetailsPanel.jsx, admin/src/components/TableBody.jsx, admin/src/components/TableComponent.jsx, admin/yarn.lock
removed virtualization from table. Should also fix „flowing“ problem of rows in #2057
Close QualityUnit/web-issues#2057
=> feat: removed virtualization

admin/src/components/generator/manual/StepSecond.jsx, admin/src/lib/aiGeneratorPanel.js
**Checklist**
Close QualityUnit/web-issues#2099
=> Added AI Generator Fetch Top Urls bugfix

admin/src/components/DetailsPanel.jsx
Fixed undefined table data after removed virtualization in `DetailsPanel`
Close QualityUnit/web-issues#2098
=> Bug: undefined table data in DetailsPanel

admin/src/elements/Tooltip_SortingFiltering.jsx, admin/src/hooks/useChangeRow.jsx
Fixed rows deletion and update.
Added missing query key `fetchOptions` for optimistic query updates.
Close https://github.com/QualityUnit/web-issues/issues/2097
=> Bugfix: table rows deletion and updates doesn't work

admin/src/components/MainMenu.jsx, admin/src/components/ModuleViewHeader.jsx, admin/src/hooks/useTableStore.jsx
Removed global reset of tables store.
Close QualityUnit/web-issues#2100
=> fix: removed table reset

includes/class-urlslab-activator.php, includes/cron/class-urlslab-serp-cron.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2101
=> process manual serp queries faster as other types

admin/class-urlslab-admin.php
Close https://github.com/QualityUnit/web-issues/issues/2105
=> feat: inform user if api key is missing or no credits on account

admin/src/app/mui_joy/theme.js, admin/src/assets/styles/components/_Panel.scss
various small bugfixes
Close QualityUnit/web-issues#2107
Close QualityUnit/web-issues#2108
=> Various small bugfixes

admin/src/tables/GscSitesTable.jsx, includes/api/class-urlslab-api-gsc-sites.php
Close https://github.com/QualityUnit/web-issues/issues/2125
=> GSC properties as clickable domain names

includes/class-urlslab-activator.php, includes/cron/class-urlslab-serp-cron.php, includes/data/class-urlslab-serp-query-row.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2129
=> feat: store parent_query_id for SERP queries

admin/src/api/fetchDataForProcessing.js
Fixed stopped fetching results after first data returned in Export panel
Close QualityUnit/web-issues#2126
=> [2126] fix: export not working

admin/src/components/ChangesPanel/ChangesPanel.jsx, admin/src/components/ImageCompare.jsx, admin/src/components/TableComponent.jsx
Fixes for Columns menu, Show Changes panel in URL Monitoring
Close QualityUnit/web-issues#2136
Close QualityUnit/web-issues#2139
=> fix: #2136, #2139

admin/src/tables/SerpQueryDetailTopUrlsTable.jsx, admin/src/tables/SerpUrlDetailSimilarUrlsTable.jsx, includes/api/class-urlslab-api-serp-queries.php
Close https://github.com/QualityUnit/web-issues/issues/2163
=> feat: show domain type in all places where serp urls are displayed

includes/executor/class-urlslab-executor-url-intersection.php, includes/widgets/class-urlslab-cache-widget.php, includes/widgets/class-urlslab-optimize.php, includes/widgets/class-urlslab-widget.php
Close https://github.com/QualityUnit/web-issues/issues/2151
=> feat: add optimize db actions to admin menu

admin/class-urlslab-admin.php
https://github.com/QualityUnit/web-issues/issues/2066
=> feat: show cron notification in admin menu if is not running

includes/widgets/class-urlslab-html-optimizer.php
Close https://github.com/QualityUnit/web-issues/issues/2095
=> fix: including of css to html should not do htmlentities conversion

includes/cache/class-urlslab-cache.php, includes/widget/class-urlslab-widget-custom-html.php, includes/widget/class-urlslab-widget-redirects.php
all cache keys should have prefix the urlslab version
Close https://github.com/QualityUnit/web-issues/issues/2178
=> fix: Fatal error: Uncaught TypeError: Urlslab_Widget_Custom_Html::is_match()

admin/src/modules/WebVitals.jsx, admin/src/tables/WebVitalsTable.jsx, includes/api/class-urlslab-api-table.php, includes/api/class-urlslab-api-web-vitals.php, includes/data/class-urlslab-data-web-vital.php
=> web vitals log

includes/class-urlslab-activator.php, urlslab.php
task not ready, next PRs will come
https://github.com/QualityUnit/web-issues/issues/2180
=> add missing index in generator task

includes/api/class-urlslab-api-web-vitals.php, includes/widget/class-urlslab-widget-web-vitals.php
Close https://github.com/QualityUnit/web-issues/issues/2188
=> fix: regular expression validation

includes/api/class-urlslab-api-meta-tags.php, includes/api/class-urlslab-api-screenshots.php, includes/api/class-urlslab-api-serp-urls.php, includes/api/class-urlslab-api-table.php
Close https://github.com/QualityUnit/web-issues/issues/2189
=> fix: validation of filters array

includes/class-urlslab-activator.php, includes/cron/class-urlslab-cron-screenshots.php, includes/cron/class-urlslab-cron-summaries.php, includes/cron/executor/class-urlslab-cron-executor-generator.php, includes/widget/class-urlslab-widget-faq.php, urlslab.php
https://github.com/QualityUnit/web-issues/issues/2180
=> sql optimizations

includes/api/class-urlslab-api-serp-queries.php
Close https://github.com/QualityUnit/web-issues/issues/2196
=> fix: load max 15 unique urls from serp if query is not in db

includes/data/class-urlslab-data-serp-query.php, includes/data/class-urlslab-data-serp-url.php
https://github.com/QualityUnit/web-issues/issues/2180
=> fix: for now is fix to load less often the update

admin/src/api/fetching.js, admin/src/api/generatorApi.js, admin/src/api/importCsv.js, admin/src/api/settings.js, admin/src/assets/styles/common/_global.scss, admin/src/assets/styles/components/_NotificationsPanel.scss, admin/src/components/NotificationsPanel.jsx, admin/src/components/SettingsOption.jsx, admin/src/components/generator/generatorUtils.js, admin/src/hooks/useChangeRow.jsx, admin/src/lib/serpQueries.js, admin/src/onboarding/steps/StepApiKey.jsx, admin/src/onboarding/steps/StepModules.jsx, admin/src/tables/NotFoundTable.jsx, includes/api/class-urlslab-api-serp-gap.php
Close https://github.com/QualityUnit/web-issues/issues/2179
=> fix: max number of urls set as validator

includes/data/class-urlslab-data-faq.php, includes/data/class-urlslab-data.php
Close https://github.com/QualityUnit/web-issues/issues/2203
=> feat: handling of column updated

includes/api/class-urlslab-api-table-sql.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/2205
=> fix: sql syntax error

admin/src/api/generatorApi.js, admin/src/components/detailsPanel/GapDetailPanel.jsx, admin/src/components/generator/ContentGeneratorEditor.jsx, admin/src/components/generator/manual/StepSecond.jsx, admin/src/elements/DataBox.jsx, admin/src/hooks/useAIGeneratorManualInit.jsx, admin/src/lib/aiGeneratorPanel.js, admin/src/lib/serpQueries.js, admin/src/modules/static/TagsLabels.jsx, admin/src/queries/usePostTypesQuery.jsx
1. Fixed hanging loading information after serp queries api return 404.
2. Added "nothing found" text when serp queries api doesn't find any urls.
3. Unified serp fetch functions returns, to work with all fetch function same way and allow correct general server error response handling (some functions returned a promise, another parsed json response etc...)
Close QualityUnit/web-issues#2198
=> i2198: fixed serp query-urls loading, unified serp fetch functions returns

admin/src/tables/SerpQueriesTable.jsx, admin/src/tables/SerpUrlDetailQueryTable.jsx
Tables Serp Queries and Serp URL detail table shows full country name.
Close QualityUnit/web-issues#2211
=> fix: full country text in table

admin/src/components/ChangesPanel/ChangesPanel.jsx, admin/src/components/detailsPanel/GapDetailPanel.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/tables/FaqUrlsTable.jsx, admin/src/tables/NotFoundTable.jsx, admin/src/tables/SerpContentGapTable.jsx, admin/src/tables/SerpQueriesTable.jsx, admin/src/tables/SerpTopDomainsTable.jsx, admin/src/tables/WebVitalsTable.jsx
Fixed non working delete and update when defaultSorting activated, non working filters in Serp Query
Close QualityUnit/web-issues#2193
Close QualityUnit/web-issues#2208
=> fix: #2193, #2208, semicolon in serp gap

admin/src/tables/NotFoundTable.jsx, admin/src/tables/WebVitalsTable.jsx, composer.json, composer.lock, includes/data/class-urlslab-data-web-vital.php, includes/tool/class-urlslab-tool-geoip.php, includes/widget/class-urlslab-widget-general.php, includes/widget/class-urlslab-widget-redirects.php
geoip added to web vitals and 404 logging
=> feat: geoip

admin/src/hooks/useChangeRow.jsx
Corrected hook definition to accept default undefined object.
=> fix: useChangeRow definition

includes/tool/class-urlslab-tool-geoip.php, includes/widget/class-urlslab-widget-general.php
Close https://github.com/QualityUnit/web-issues/issues/2215
=> fix: changed city geoip to country - much smaller

admin/src/hooks/useSerpGapCompare.jsx
Close https://github.com/QualityUnit/web-issues/issues/2216
=> fix: Content gap button not working

includes/class-urlslab-activator.php, includes/cron/class-urlslab-cron-download-css.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2217
=> css cache cron - sql speed improved

includes/class-urlslab-activator.php, includes/cron/class-urlslab-cron-download-js.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2218
=> fix: improved speed of sql in js cache cron

includes/api/class-urlslab-api-serp-gap.php, includes/data/class-urlslab-data.php
not ready, but implemented some ideas, which could solve the problem.
https://github.com/QualityUnit/web-issues/issues/2219
=> fix: few things to optimize and test in real life

admin/src/assets/styles/common/_global.scss, admin/src/components/detailsPanel/GapDetailPanel.jsx, admin/src/components/detailsPanel/QueryDetailPanel.jsx, admin/src/elements/Tooltip_SortingFiltering.jsx, admin/src/tables/GscSitesTable.jsx, admin/src/tables/NotFoundTable.jsx, admin/src/tables/SerpCompetitorsTable.jsx, admin/src/tables/SerpQueryDetailSimQueryTable.jsx, admin/src/tables/SerpQueryDetailTopUrlsTable.jsx, admin/src/tables/SerpUrlDetailQueryTable.jsx, admin/src/tables/SerpUrlDetailSimilarUrlsTable.jsx, admin/src/tables/WebVitalsTable.jsx
removing add record buttons from tables, row counter fix
Close QualityUnit/web-issues#2210
=> [2210] fix: removing add record buttons from tables, row counter fix

includes/tool/class-urlslab-tool-geoip.php
moj debug riadok som zabudol v pr
Close https://github.com/QualityUnit/web-issues/issues/2225
=> fix: removed forgotten test ip

includes/api/class-urlslab-api-web-vitals.php
just optimization of space in db table
=> dont store attribution and entries if rating is good 

admin/src/assets/styles/components/_FloatingPanel.scss, admin/src/components/detailsPanel/GapDetailPanel.jsx, admin/src/elements/RefreshTableButton.jsx, admin/src/elements/TableSortBy.jsx, admin/src/tables/SerpContentGapTable.jsx, admin/src/tables/SerpQueryDetailSimQueryTable.jsx, admin/src/tables/SerpQueryDetailTopUrlsTable.jsx, admin/src/tables/SerpUrlDetailQueryTable.jsx, admin/src/tables/SerpUrlDetailSimilarUrlsTable.jsx
floating panel for urls in serp content gap to make panel more compact
=> feat: floating panel for urls in serp content gap

admin/apps/ai-content-assistant/src/elements/JSXElements.tsx, admin/src/assets/styles/components/_Notifications.scss, admin/src/assets/styles/components/_NotificationsPanel.scss, admin/src/components/Notifications.jsx, admin/src/components/TableFilter.jsx, admin/src/elements/InputField.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/hooks/useNotifications.jsx, admin/src/tables/KeywordsTable.jsx
#2197 Fixes for notificatios disappearing too fast – granular notifications by row ID, not module slug, stop disappear on hover
#2224 Fixes for inputs sending request to server even if empty or not changed value used.
#2229 Filters taking values from other filter menu instead of string if type of menu is string
Close QualityUnit/web-issues#2197
Close QualityUnit/web-issues#2224
Close QualityUnit/web-issues#2229
=> 2197 2224 2229 bugfixes

admin/src/elements/SingleSelectMenu.jsx
Fixed issue with numbered option keys in single select component, described in detail inside issue: #2234
Close QualityUnit/web-issues#2234
=> fix: type check for single select options keys

admin/src/tables/SerpContentGapTable.jsx, admin/src/tables/SerpQueriesTable.jsx, composer.lock, includes/api/class-urlslab-api-serp-gap.php, includes/api/class-urlslab-api-serp-queries.php, includes/class-urlslab-activator.php, includes/connection/class-urlslab-connection-serp.php, includes/cron/class-urlslab-cron-convert-avif-images.php, includes/cron/class-urlslab-cron-convert-webp-images.php, includes/cron/class-urlslab-cron-download-css.php, includes/cron/class-urlslab-cron-download-js.php, includes/cron/class-urlslab-cron-faq.php, includes/cron/class-urlslab-cron-generator.php, includes/cron/class-urlslab-cron-gsc.php, includes/cron/class-urlslab-cron-manager.php, includes/cron/class-urlslab-cron-offload-background-attachments.php, includes/cron/class-urlslab-cron-offload-enqueue-files.php, includes/cron/class-urlslab-cron-offload-transfer-files.php, includes/cron/class-urlslab-cron-redirects.php, includes/cron/class-urlslab-cron-related-resources.php, includes/cron/class-urlslab-cron-screenshots.php, includes/cron/class-urlslab-cron-serp-volumes.php, includes/cron/class-urlslab-cron-serp.php, includes/cron/class-urlslab-cron-summaries.php, includes/cron/class-urlslab-cron-update-url-http-status.php, includes/cron/class-urlslab-cron-youtube.php, includes/cron/class-urlslab-cron.php, includes/data/class-urlslab-data-serp-query.php, includes/widget/class-urlslab-widget-serp.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2235
Close QualityUnit/web-issues#1783
=> serp volumes

includes/api/class-urlslab-api-serp-gap.php, includes/api/class-urlslab-api-serp-queries.php, includes/api/class-urlslab-api-serp-urls.php
Close https://github.com/QualityUnit/web-issues/issues/2244
=> fix: fixed php warnings

admin/src/tables/SerpQueriesTable.jsx, composer.lock, includes/api/class-urlslab-api-serp-queries.php, includes/class-urlslab-activator.php, includes/data/class-urlslab-data-serp-query.php, includes/data/class-urlslab-data-serp-url.php, includes/widget/class-urlslab-widget-serp.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2245
=> query intent categorization

includes/api/class-urlslab-api-serp-queries.php, includes/data/class-urlslab-data-serp-query.php
Close https://github.com/QualityUnit/web-issues/issues/2249
=> fix: php warnings

includes/class-urlslab-activator.php, includes/cron/class-urlslab-cron-serp-volumes.php, includes/data/class-urlslab-data-serp-query.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/2250
=> fix: sql optimization

includes/api/class-urlslab-api-serp-gap.php, includes/executor/class-urlslab-executor-download-url.php, includes/executor/class-urlslab-executor-download-urls-batch.php, includes/executor/class-urlslab-executor-url-intersection.php, includes/executor/class-urlslab-executor.php
- prepare api call will be required (@ihdk is working on it right now)
Close https://github.com/QualityUnit/web-issues/issues/2251
=> fix: content gap rework

admin/src/components/detailsPanel/QueryDetailPanel.jsx, admin/src/tables/SerpQueryDetailClusterUrlsTable.jsx, admin/src/tables/SerpQueryDetailQueryClusterTable.jsx, admin/src/tables/SerpQueryDetailRankedUrlsTable.jsx, includes/api/class-urlslab-api-serp-queries.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/2241
=> Cluster URLs

admin/src/tables/CreditsTable.jsx, admin/src/tables/UsageTable.jsx
**Checklist**
Close QualityUnit/web-issues#2157
=> added installation id column

includes/cron/class-urlslab-cron-serp-volumes.php, includes/widget/class-urlslab-widget-serp.php
Close https://github.com/QualityUnit/web-issues/issues/2256
=> fix: add message about missing data from serp volumes

includes/cron/class-urlslab-cron-serp-volumes.php
Close https://github.com/QualityUnit/web-issues/issues/2259
=> fix: add more blacklisted characters to serp volume search

admin/src/components/detailsPanel/QueryDetailPanel.jsx, admin/src/tables/SerpContentGapTable.jsx, includes/api/class-urlslab-api-serp-gap.php, includes/api/class-urlslab-api-serp-queries.php, includes/executor/class-urlslab-executor-url-intersection.php
Close https://github.com/QualityUnit/web-issues/issues/2263
Close https://github.com/QualityUnit/web-issues/issues/2262
=> fix: show also searching query

includes/class-urlslab-activator.php, includes/cron/class-urlslab-cron-serp-volumes.php, includes/cron/class-urlslab-cron.php, includes/data/class-urlslab-data-serp-query.php, urlslab.php
=> Bug fix keyword analysis

admin/apps/ai-content-assistant/src/components/AdvancedSettings.tsx, admin/src/tables/GeneratorPromptTemplateTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx, composer.lock, includes/api/class-urlslab-api-shortcodes.php, includes/connection/class-urlslab-connection-augment.php, includes/cron/executor/class-urlslab-cron-executor-generator.php, includes/default/class-urlslab-default-prompt-template.php, includes/executor/class-urlslab-executor-generate.php, includes/widget/class-urlslab-widget-content-generator.php, includes/widget/class-urlslab-widget-faq.php
=> Added new open AI models

admin/apps/ai-content-assistant/src/app/stateReducer.ts, admin/apps/ai-content-assistant/src/components/AdvancedSettings.tsx, admin/src/hooks/useAIGenerator.jsx, admin/src/tables/GeneratorPromptTemplateTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx, composer.lock, includes/api/class-urlslab-api-shortcodes.php, includes/connection/class-urlslab-connection-augment.php, includes/cron/class-urlslab-cron-generator.php, includes/cron/class-urlslab-cron.php, includes/cron/executor/class-urlslab-cron-executor-generator.php, includes/data/class-urlslab-data-generator-task.php, includes/default/class-urlslab-default-prompt-template.php, includes/executor/class-urlslab-executor-generate.php, includes/widget/class-urlslab-widget-content-generator.php, includes/widget/class-urlslab-widget-faq.php
=> bug fix for faqs

includes/cron/class-urlslab-cron-faq.php
=> faq answer scheduling bugfix

includes/cron/class-urlslab-cron-optimize.php
Close QualityUnit/web-issues#2280
=> fix: optimization task locking

includes/api/class-urlslab-api-optimize.php, includes/class-urlslab-activator.php, includes/cron/class-urlslab-cron-serp-volumes.php, includes/widget/class-urlslab-widget-optimize.php, urlslab.php
Close QualityUnit/web-issues#2282
=> fixed deleting transient options

includes/cron/class-urlslab-cron-serp-volumes.php
**Checklist**
Close QualityUnit/web-issues#2283
=> extended blacklist

admin/src/lib/serpQueryColumns.js
Close https://github.com/QualityUnit/web-issues/issues/2284
=> fix: changed name of column competition index

includes/class-urlslab-user-widget.php
=> feat: activate all widgets on first installation

includes/widget/class-urlslab-widget-general.php, includes/widget/class-urlslab-widget.php
Close https://github.com/QualityUnit/web-issues/issues/2286
=> encrypt sensitive settings

admin/src/components/EditRowPanel.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/tables/CustomHtmlTable.jsx, admin/src/tables/FaqUrlsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/URLRelationTable.jsx
-- fixed saving table row on checkbox option uncheck.
-- fixed optimistic update of table row for tables with `querySelector`
Close QualityUnit/web-issues#2269
=> I2269 checkbox in table bug

admin/src/hooks/useFilteringSorting.jsx
Fixed a bug when column key was not taken into account on sorting between different columns
Close QualityUnit/web-issues#2268
=> [2268] fix: sorting when changing sorting columns

admin/src/tables/NotFoundTable.jsx
Close https://github.com/QualityUnit/web-issues/issues/2302
=> fix: remove tags from 404 log table

includes/api/class-urlslab-api-table.php, includes/class-urlslab-activator.php, urlslab.php
Close QualityUnit/web-issues#2303
=> fix: memory limit reached when adding tag to media files

includes/class-urlslab-activator.php, includes/cron/class-urlslab-cron-update-url-http-status.php, includes/widget/class-urlslab-widget-link-enhancer.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2305
=> sql speed improvements

admin/src/tables/MediaFilesTable.jsx, includes/api/class-urlslab-api-files.php, includes/class-urlslab-activator.php, includes/data/class-urlslab-data-file.php, includes/widget/class-urlslab-widget-media-offloader.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2306
=> fix: improve speed of files table api

admin/src/tables/LinkManagerTable.jsx, includes/api/class-urlslab-api-meta-tags.php, includes/api/class-urlslab-api-screenshots.php, includes/api/class-urlslab-api-urls.php, includes/class-urlslab-activator.php, includes/data/class-urlslab-data-url.php, includes/widget/class-urlslab-widget-link-enhancer.php, includes/widget/class-urlslab-widget-screenshot.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2311
=> fix: precompute usage of urls and screenshots

includes/driver/class-urlslab-driver-file.php
Close https://github.com/QualityUnit/web-issues/issues/2313
=> fix: hide warning in file driver

includes/executor/class-urlslab-executor-download-url.php, includes/executor/class-urlslab-executor-url-intersection.php
Close https://github.com/QualityUnit/web-issues/issues/2312
=> fix: special characters in content gap

includes/executor/class-urlslab-executor-url-intersection.php
increase number of words in ngrams to 1-5
=> feat: generate just unique strings in content gap,

includes/api/class-urlslab-api-redirects.php, includes/data/class-urlslab-data-redirect.php
UI is not ready
Close QualityUnit/web-issues#2318
=> fix: return capabilities and roles as array and not string

includes/api/class-urlslab-api-faq-urls.php, includes/api/class-urlslab-api-files.php, includes/api/class-urlslab-api-generators.php, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-shortcodes.php, includes/api/class-urlslab-api-table.php, includes/api/class-urlslab-api-url-relations.php, includes/api/class-urlslab-api-urls.php, includes/api/class-urlslab-api-youtube-cache.php
Close https://github.com/QualityUnit/web-issues/issues/1825
=> fix: url_name filter should not have protocol

includes/widget/class-urlslab-widget-html-optimizer.php
Close https://github.com/QualityUnit/web-issues/issues/1962
=> fix: added warning, that minification can corrupt HTML

includes/api/class-urlslab-api-modules.php, includes/widget/class-urlslab-widget-cache.php, includes/widget/class-urlslab-widget-content-generator.php, includes/widget/class-urlslab-widget-custom-html.php, includes/widget/class-urlslab-widget-faq.php, includes/widget/class-urlslab-widget-html-optimizer.php, includes/widget/class-urlslab-widget-image-alt-text.php, includes/widget/class-urlslab-widget-lazy-loading.php, includes/widget/class-urlslab-widget-link-builder.php, includes/widget/class-urlslab-widget-media-offloader.php, includes/widget/class-urlslab-widget-optimize.php, includes/widget/class-urlslab-widget-redirects.php, includes/widget/class-urlslab-widget-related-resources.php, includes/widget/class-urlslab-widget-search-replace.php, includes/widget/class-urlslab-widget-serp.php, includes/widget/class-urlslab-widget-urls.php, includes/widget/class-urlslab-widget-web-vitals.php, includes/widget/class-urlslab-widget.php
https://github.com/QualityUnit/web-issues/issues/2148
=> fix: added group information for each widget

admin/src/lib/serpContentGapHelpers.js, includes/executor/class-urlslab-executor-download-url.php
Close https://github.com/QualityUnit/web-issues/issues/2339
=> fix: define timeout for URL download, show mesage in content gap

includes/api/class-urlslab-api-gsc-sites.php, includes/api/class-urlslab-api-serp-queries.php, includes/cron/class-urlslab-cron-update-url-http-status.php, includes/data/class-urlslab-data-serp-query.php, includes/data/class-urlslab-data-serp-url.php, includes/widget/class-urlslab-widget-serp.php, includes/widget/class-urlslab-widget-urls.php
Close https://github.com/QualityUnit/web-issues/issues/2342
=> fix: remove not needed settings

includes/widget/class-urlslab-widget-html-optimizer.php
Close https://github.com/QualityUnit/web-issues/issues/2344
=> fix: skip html optimization for logged in users

includes/class-urlslab-activator.php
Close https://github.com/QualityUnit/web-issues/issues/2343
=> fix: sql errors

admin/src/tables/UrlsTable.jsx, includes/api/class-urlslab-api-urls.php, includes/class-urlslab-activator.php, includes/class-urlslab.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2346
=> fix: fix urls

includes/cron/class-urlslab-cron-serp.php, includes/widget/class-urlslab-widget-serp.php
Close https://github.com/QualityUnit/web-issues/issues/2351
=> fix: limits in serp module

admin/src/components/ContentGapMonitoringPanel.jsx, admin/src/components/EditRowPanel.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/components/TablePanels.jsx, admin/src/components/detailsPanel/GapDetailPanel.jsx, admin/src/hooks/useInfiniteFetch.jsx, admin/src/lib/helpers.js, admin/src/tables/SerpContentGapTable.jsx, admin/src/tables/SerpQueriesTable.jsx
Adding selected Content Gap queries into Queries table.
Close QualityUnit/web-issues#2327
=> I2327 content gap monitoring

composer.json, composer.lock, includes/widget/class-urlslab-widget-lazy-loading.php
@mvstepanek pls test if it works as you expected
Close https://github.com/QualityUnit/web-issues/issues/2358
=> fix: lazy loading - support css selectors

admin/src/components/Credits.jsx, admin/src/components/Header.jsx, admin/src/modules/Serp.jsx, admin/src/tables/FaqsTable.jsx, admin/src/tables/SerpContentGapTable.jsx, composer.lock, includes/api/class-urlslab-api-serp-queries.php, includes/connection/class-urlslab-connection-serp.php, includes/cron/class-urlslab-cron-serp.php, includes/widget/class-urlslab-widget-general.php
Close https://github.com/QualityUnit/web-issues/issues/2361
=> requesting serp data with adding query api call

includes/widget/class-urlslab-widget-urls.php
Close QualityUnit/web-issues#2347
=> fix: add missing title and description for current page

admin/apps/ai-content-assistant/src/elements/JSXElements.tsx, admin/src/api/fetchLangs.js, admin/src/api/importCsv.js, admin/src/app/mui_joy/themes/tableTheme.js, admin/src/components/DeleteFilteredPanel.jsx, admin/src/components/DeletePanel.jsx, admin/src/components/ImportPanel.jsx, admin/src/components/SettingsOption.jsx, admin/src/components/TableFilterPanel.jsx, admin/src/elements/CapabilitiesMenu.jsx, admin/src/elements/DateTimeFormat.jsx, admin/src/elements/InputField.jsx, admin/src/elements/LangMenu.jsx, admin/src/elements/RolesMenu.jsx, admin/src/elements/Switch.jsx, admin/src/elements/TextAreaEditable.jsx, admin/src/elements/Textarea.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/hooks/useFilteringSorting.jsx, admin/src/queries/usePrefetchQueries.jsx, admin/src/tables/CustomHtmlTable.jsx, admin/src/tables/FaqsTable.jsx, admin/src/tables/GeneratorProcessesTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/RedirectsTable.jsx, admin/src/tables/YouTubeCacheTable.jsx, includes/api/class-urlslab-api-permissions.php
Close https://github.com/QualityUnit/web-issues/issues/2296
Close https://github.com/QualityUnit/web-issues/issues/2297
Close https://github.com/QualityUnit/web-issues/issues/2300
Close https://github.com/QualityUnit/web-issues/issues/2301
Close https://github.com/QualityUnit/web-issues/issues/2315
Close https://github.com/QualityUnit/web-issues/issues/2320
Close https://github.com/QualityUnit/web-issues/issues/2326
=> feat: fixes from v3, cherrypicked

admin/src/app/mui_joy/themes/tooltipTheme.js, admin/src/assets/styles/common/_global.scss, admin/src/components/TableRow.jsx, admin/src/hooks/useFilteringSorting.jsx, admin/src/tables/GeneratorPromptTemplateTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx
Close QualityUnit/web-issues#2323
Close QualityUnit/web-issues#2324
Close QualityUnit/web-issues#2334
=> Bugfixes november v4

includes/api/class-urlslab-api-files.php, includes/api/class-urlslab-api-tasks.php, includes/cron/class-urlslab-cron-generator.php, includes/data/class-urlslab-data-task.php
Close https://github.com/QualityUnit/web-issues/issues/2364
=> fatal error - variable type

includes/api/class-urlslab-api-labels.php, includes/cron/class-urlslab-cron-generator.php, includes/cron/class-urlslab-cron-serp.php, includes/cron/executor/class-urlslab-cron-executor-generator.php, includes/widget/class-urlslab-widget-faq.php
=> ai generator bugfix processing

admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/components/TableFilterPanel.jsx, admin/src/components/TableRow.jsx, admin/src/hooks/useFilteringSorting.jsx, admin/src/tables/GeneratorProcessesTable.jsx, includes/api/class-urlslab-api-process.php
#2353 Filter panel slow rendering, #2348 Regenerate button on failed AI process
Close QualityUnit/web-issues#2348
Close QualityUnit/web-issues#2353
=> Bugfixes november v5

README.md
=> Installation via Git

includes/class-urlslab-activator.php, includes/class-urlslab.php, urlslab.php
**Checklist**
Close QualityUnit/web-issues#2372
Close QualityUnit/web-issues#2371
=> Bugfixes with plugin installation and update steps

includes/api/class-urlslab-api-serp-queries.php
Close https://github.com/QualityUnit/web-issues/issues/2373
=> fix: on insert of duplicate query update the status to reupdate the query data

includes/widget/class-urlslab-widget-optimize.php, uninstall.php
Close https://github.com/QualityUnit/web-issues/issues/2367
=> fix: deleting plugin transient data and fix uninstall

admin/src/tables/UrlsTable.jsx, includes/data/class-urlslab-data-url.php, includes/widget/class-urlslab-widget-related-resources.php, includes/widget/class-urlslab-widget-urls.php
Close https://github.com/QualityUnit/web-issues/issues/2376
=> fix: hide links pointing to 404

includes/class-urlslab-public.php
Close https://github.com/QualityUnit/web-issues/issues/2386
=> fix: path to urlslab-lazyload.js

admin/src/assets/styles/components/_Panel.scss, admin/src/assets/styles/elements/_BackButton.scss, admin/src/components/detailsPanel/QueryDetailPanel.jsx, admin/src/components/detailsPanel/UrlDetailPanel.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/tables/SerpQueriesTable.jsx, admin/src/tables/SerpUrlDetailQueryTable.jsx, admin/src/tables/SerpUrlDetailSimilarUrlsTable.jsx, admin/src/tables/UrlsTable.jsx
Delete selected in Query fixed, query and URL details UI fixes
Close QualityUnit/web-issues#2314
Close QualityUnit/web-issues#2316
Close QualityUnit/web-issues#2325
=> fix: #2314, #2316, #2325

includes/cron/class-urlslab-cron-serp-volumes.php
=> Added more symbols to volume blacklist

includes/cron/class-urlslab-cron-related-resources.php, includes/data/class-urlslab-data-url.php
cron and scheduling fixed
Close https://github.com/QualityUnit/web-issues/issues/2388
=> fix: skip processing of blacklisted domains

includes/connection/class-urlslab-connection-serp.php
Close https://github.com/QualityUnit/web-issues/issues/2349
=> fix: apply limit on all queries, not just valid

admin/src/tables/CacheRulesTable.jsx, admin/src/tables/CustomHtmlTable.jsx, admin/src/tables/SearchReplaceTable.jsx, includes/api/class-urlslab-api-cache-rules.php, includes/api/class-urlslab-api-custom-html.php, includes/api/class-urlslab-api-search-replace.php, includes/class-urlslab-activator.php, includes/data/class-urlslab-data-cache-rule.php, includes/data/class-urlslab-data-custom-html.php, includes/data/class-urlslab-data-search-replace.php, includes/widget/class-urlslab-widget-cache.php, includes/widget/class-urlslab-widget-custom-html.php, includes/widget/class-urlslab-widget-search-replace.php, urlslab.php
post types we will do in another PR
https://github.com/QualityUnit/web-issues/issues/2387
=> feat: complex conditions for html injection, caching or search and replace

includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-urls.php, includes/class-urlslab-url.php, includes/cron/class-urlslab-cron-related-resources.php, includes/cron/class-urlslab-cron-update-url-http-status.php, includes/data/class-urlslab-data-url-fetcher.php, includes/data/class-urlslab-data-url.php, includes/widget/class-urlslab-widget-content-generator.php, includes/widget/class-urlslab-widget-faq.php, includes/widget/class-urlslab-widget-general.php, includes/widget/class-urlslab-widget-lazy-loading.php, includes/widget/class-urlslab-widget-link-builder.php, includes/widget/class-urlslab-widget-urls.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/2036
=> skip blacklisted urls

includes/api/class-urlslab-api-faq.php, includes/api/class-urlslab-api-files.php, includes/api/class-urlslab-api-generators.php, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-shortcodes.php, includes/api/class-urlslab-api-table.php, includes/api/class-urlslab-api-urls.php, includes/data/class-urlslab-data-file-url.php, includes/data/class-urlslab-data-keyword-map.php, includes/data/class-urlslab-data-url-map.php, includes/data/class-urlslab-data.php
deleting rows by 500 entries
Close QualityUnit/web-issues#2352
=> Optimize delete api

includes/widget/class-urlslab-widget-link-builder.php
Close https://github.com/QualityUnit/web-issues/issues/2395
=> fix: fatal error is_blacklisted

includes/widget/class-urlslab-widget-link-builder.php, includes/widget/class-urlslab-widget-media-offloader.php, includes/widget/class-urlslab-widget-urls.php
Close https://github.com/QualityUnit/web-issues/issues/1985
Close https://github.com/QualityUnit/web-issues/issues/2397
=> fix: don't track urls for logged in user and search

includes/api/class-urlslab-api-files.php, includes/cron/class-urlslab-cron-convert-images.php, includes/cron/class-urlslab-cron-offload-background-attachments.php, includes/driver/class-urlslab-driver.php
Close QualityUnit/web-issues#2356
=> fix: media files were not uploaded to db driver

includes/class-urlslab-activator.php, urlslab.php
Close QualityUnit/web-issues#2356
=> fix: reprocess files with missing file pointer

admin/src/modules/WebVitals.jsx, admin/src/overview/WebVitals.jsx, admin/src/tables/WebVitalsTable.jsx, includes/widget/class-urlslab-widget-web-vitals.php
improvements for texts in web vitals
**Checklist**
=> feat: improvements for texts in web vitals

includes/cron/class-urlslab-cron-generator.php
Close https://github.com/QualityUnit/web-issues/issues/2400
=> fix: fatal error - task_row is empty if video

includes/api/class-urlslab-api-urls.php, includes/class-urlslab-url.php, includes/widget/class-urlslab-widget-cache.php, includes/widget/class-urlslab-widget-lazy-loading.php, includes/widget/class-urlslab-widget-link-builder.php
Close https://github.com/QualityUnit/web-issues/issues/2404
=> fix: fatal error - url name empty

admin/src/tables/WebVitalsTable.jsx, includes/api/class-urlslab-api-web-vitals.php, includes/class-urlslab-activator.php, includes/cron/class-urlslab-cron-optimize.php, includes/data/class-urlslab-data-web-vital.php, includes/widget/class-urlslab-widget-optimize.php, includes/widget/class-urlslab-widget-web-vitals.php, urlslab.php
https://github.com/QualityUnit/web-issues/issues/2152
=> fix: don't measure web vitals for logged in user, search and 404 page

admin/src/components/ChangesPanel/ChangesPanel.jsx
**Checklist**
Close QualityUnit/web-issues#2329
=> Bug fix for caching  in image comparison

includes/class-urlslab.php, includes/widget/class-urlslab-widget-cache.php
even we used caching, multiple SQLs were executed each time we hit the cache (e.g. elementor or other plugins)
should be solved now
=> feat: improve speed of caching

includes/class-urlslab-url.php, includes/widget/class-urlslab-widget-cache.php
Close QualityUnit/web-issues#2407
=> feat: blacklist too long url paths or query parameters

includes/class-urlslab-activator.php, urlslab.php
**Checklist**
Close QualityUnit/web-issues#2399
=> Fixed bug with serp queries wrong status

admin/src/api/fetchDataForProcessing.js, admin/src/components/ChangesPanel/ChangesPanel.jsx, admin/src/components/DeleteFilteredPanel.jsx, admin/src/components/DetailsPanel.jsx, admin/src/components/ExportPanel.jsx, admin/src/elements/ExportCSVButton.jsx, admin/src/elements/TableActionsMenu.jsx, admin/src/tables/GeneratorResultTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/ScreenshotTable.jsx, admin/src/tables/UrlsTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
further optimizing export, no count fetch request if already counted rows, straight export if <=50 items in table
Export panel in tables and URL details (ie URLs table > chain icon)
Close QualityUnit/web-issues#2402
=> [2402] Export optimalizations

admin/src/elements/LangMenu.jsx
Keyword prefill on adding, table rerender on filter Language change etc
Close QualityUnit/web-issues#2411
=> [2411] fix: table rerendering, keyword prefilling

includes/executor/class-urlslab-executor-download-url.php, includes/widget/class-urlslab-widget-optimize.php
Close https://github.com/QualityUnit/web-issues/issues/2412
=> fix: set fixed user agent to download url

admin/src/tables/UrlsTable.jsx, includes/cron/class-urlslab-cron-update-url-http-status.php, includes/widget/class-urlslab-widget-related-resources.php
Close https://github.com/QualityUnit/web-issues/issues/1823
=> fix: evaluate correct status for url

admin/src/components/TableFilter.jsx, admin/src/components/TableFilterPanel.jsx, admin/src/hooks/useFilteringSorting.jsx, admin/src/lib/filterOperators.js, admin/src/tables/SerpContentGapTable.jsx, admin/src/tables/SerpQueriesTable.jsx, admin/src/tables/SerpQueryDetailQueryClusterTable.jsx, admin/src/tables/SerpUrlDetailQueryTable.jsx, admin/src/tables/WebVitalsTable.jsx
Added CountrySelect component into table filters panel.
Default value of select is `us`
Fixed other small issues in language filter displayed in list of already selected filters.
Close QualityUnit/web-issues#2292
=> I2292 country select filter

includes/class-urlslab-activator.php, includes/cron/class-urlslab-cron-generator.php, urlslab.php
**Checklist**
Close QualityUnit/web-issues#2417
=> fixed bug for inserting correct data in generator shortcode res

admin/src/tables/BacklinksTable.jsx, includes/api/class-urlslab-api-backlinks.php, includes/class-urlslab-activator.php, includes/data/class-urlslab-data-backlink-monitor.php, includes/data/class-urlslab-data-url.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2420
=> backlink monitoring - status icons, first_seen column

includes/widget/class-urlslab-widget-urls.php
=> add target _blank to external links

admin/src/modules/Urls.jsx, admin/src/tables/URLMapTable.jsx, includes/api/class-urlslab-api-url-map.php, includes/data/class-urlslab-data-url.php, includes/widget/class-urlslab-widget-general.php
Close QualityUnit/web-issues#2422
=> feat: map between urls

admin/src/components/StepNavigation.jsx, admin/src/components/generator/manual/StepFirst.jsx, admin/src/tables/KeywordsTable.jsx
back to queries button (if coming from Queries to AI generator), select/deselect all in ai generator
Close QualityUnit/web-issues#2194
=> [2194] feat: back to queries button, select/deselect all in ai generator

includes/class-urlslab-activator.php
=> fix upgrade steps

admin/src/tables/BacklinksTable.jsx, includes/api/class-urlslab-api-backlinks.php, includes/class-urlslab-url.php, includes/data/class-urlslab-data-url.php
https://github.com/QualityUnit/web-issues/issues/2424
=> fix: backlinks table errors

includes/data/class-urlslab-data-url.php
=> fix: php warning undefined array key url

admin/src/assets/styles/components/_Panel.scss, admin/src/lib/helpers.js, admin/src/tables/KeywordsTable.jsx
Added datepicker for valid_until in Keywords table edit/add row options.
Close QualityUnit/web-issues#2418
=> fix: datepicker for valid_until in keywords table

includes/data/class-urlslab-data-url.php
Close https://github.com/QualityUnit/web-issues/issues/2430
=> fix: url matching improved

includes/data/class-urlslab-data-url.php
Close https://github.com/QualityUnit/web-issues/issues/2433
=> fix: database error: duplicate entry

admin/src/tables/BacklinksTable.jsx, includes/data/class-urlslab-data-url.php
Close https://github.com/QualityUnit/web-issues/issues/2432
=> fix: backlinks - url attribute, backlink status if url failed to load

includes/api/class-urlslab-api-serp-queries.php, includes/api/class-urlslab-api-table.php
Close https://github.com/QualityUnit/web-issues/issues/2429
=> fix: prepare filter for url name

includes/widget/class-urlslab-widget.php
Close https://github.com/QualityUnit/web-issues/issues/2427
=> fix: removed default values - fix depreceated error

admin/src/components/DetailsPanel.jsx, admin/src/lib/helpers.js, admin/src/tables/BacklinksTable.jsx, admin/src/tables/FaqUrlsTable.jsx, admin/src/tables/URLMapTable.jsx, admin/src/tables/URLRelationTable.jsx, admin/src/tables/UrlsTable.jsx, includes/api/class-urlslab-api-backlinks.php, includes/api/class-urlslab-api-faq-urls.php, includes/api/class-urlslab-api-files.php, includes/api/class-urlslab-api-table.php, includes/api/class-urlslab-api-url-map.php, includes/api/class-urlslab-api-url-relations.php, includes/api/class-urlslab-api-urls.php, includes/class-urlslab-activator.php, includes/data/class-urlslab-data-url.php, includes/widget/class-urlslab-widget-urls.php, urlslab.php
- edit link next to url doesn't work
Close https://github.com/QualityUnit/web-issues/issues/2434
=> feat: store postid with url, edit post where possible

includes/data/class-urlslab-data-url.php, includes/widget/class-urlslab-widget-urls.php
Close https://github.com/QualityUnit/web-issues/issues/2426
=> feat: 403 links include in content

admin/src/app/router.jsx, admin/src/assets/styles/components/_MainMenu.scss, admin/src/components/DashboardModule.jsx, admin/src/components/MainMenu.jsx, admin/src/hooks/useModuleGroups.jsx, admin/src/hooks/useOnloadRedirect.jsx, admin/src/hooks/usePageTitle.jsx, admin/src/modules/static/Modules.jsx, includes/class-urlslab-available-widgets.php, includes/widget/class-urlslab-widget-content-generator.php, includes/widget/class-urlslab-widget-faq.php, includes/widget/class-urlslab-widget-link-builder.php, includes/widget/class-urlslab-widget-optimize.php, includes/widget/class-urlslab-widget-related-resources.php, includes/widget/class-urlslab-widget-serp.php, includes/widget/class-urlslab-widget-urls.php, includes/widget/class-urlslab-widget-web-vitals.php
Module categories in menu, each category shows only modules for given category
Close QualityUnit/web-issues#2148
=> [2148] Module categorization

includes/driver/class-urlslab-driver-file.php
fixed error with directory
QualityUnit/web-issues#2440
=> fix: don't create directory

includes/cron/class-urlslab-cron-manager.php, includes/widget/class-urlslab-widget-cache.php
Close https://github.com/QualityUnit/web-issues/issues/2447
=> feat: cache 404

includes/driver/class-urlslab-driver-db.php, includes/driver/class-urlslab-driver-file.php, includes/driver/class-urlslab-driver-s3.php, includes/driver/class-urlslab-driver.php
Close QualityUnit/web-issues#2452
=> fix: removed unsecure implementation of file driver

admin/src/app/mui_joy/themes/sheetTheme.js, admin/src/app/mui_joy/themes/tableTheme.js, admin/src/app/router.jsx, admin/src/components/DashboardModule.jsx, admin/src/components/MainMenu.jsx, admin/src/components/TableBody.jsx, admin/src/components/TableComponent.jsx, admin/src/components/TableHead.jsx, admin/src/hooks/useModuleGroups.jsx, admin/src/hooks/useOnloadRedirect.jsx, admin/src/hooks/usePageTitle.jsx, admin/src/modules/static/Modules.jsx, admin/src/tables/UrlsTable.jsx, includes/widget/class-urlslab-widget-cache.php, includes/widget/class-urlslab-widget-content-generator.php, includes/widget/class-urlslab-widget-custom-html.php, includes/widget/class-urlslab-widget-faq.php, includes/widget/class-urlslab-widget-html-optimizer.php, includes/widget/class-urlslab-widget-lazy-loading.php, includes/widget/class-urlslab-widget-link-builder.php, includes/widget/class-urlslab-widget-media-offloader.php, includes/widget/class-urlslab-widget-optimize.php, includes/widget/class-urlslab-widget-redirects.php, includes/widget/class-urlslab-widget-related-resources.php, includes/widget/class-urlslab-widget-search-replace.php, includes/widget/class-urlslab-widget-serp.php, includes/widget/class-urlslab-widget-urls.php, includes/widget/class-urlslab-widget-web-vitals.php, includes/widget/class-urlslab-widget.php
Fixes for rowactions toggler position, small menu bugfixes, group translations
Close QualityUnit/web-issues#2445
Close QualityUnit/web-issues#2448
Close QualityUnit/web-issues#2455
=> [2445] Rowactions sidebar fixes

includes/api/class-urlslab-api-user-info.php, includes/widget/class-urlslab-widget-faq.php, includes/widget/class-urlslab-widget-general.php, includes/widget/class-urlslab-widget-urls.php
Added User Info endpoint for Onboarding
**Checklist**
Close QualityUnit/web-issues#2490
=> Added User Info endpoint for Onboarding

admin/src/lib/aiGeneratorPanel.js, includes/default/class-urlslab-default-prompt-template.php
**Checklist**
Close QualityUnit/web-issues#2285
Close QualityUnit/web-issues#2472
Close QualityUnit/web-issues#2103
Close QualityUnit/web-issues#2309
=> Content AI and prompt template bugfixes

includes/widget/class-urlslab-widget-faq.php, includes/widget/class-urlslab-widget-serp.php
**Checklist**
Close QualityUnit/web-issues#2484
=> bugfixes with exploding fn

includes/widget/class-urlslab-widget-general.php
Close https://github.com/QualityUnit/web-issues/issues/2485
=> feat: default blacklisted class names extended

admin/src/assets/styles/components/_Panel.scss, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/components/TableFilter.jsx, admin/src/components/TableFilterPanel.jsx, admin/src/elements/TreeView.jsx, admin/src/lib/helpers.js, admin/src/modules/static/Settings.jsx, admin/src/tables/GeneratorProcessesTable.jsx, admin/src/tables/GeneratorResultTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx, includes/widget/class-urlslab-widget-redirects.php, includes/widget/class-urlslab-widget-serp.php
Object parsing in all tables, fixes to edit row panel formatting, urls parsing in description, filter panel closing on click outside
Close QualityUnit/web-issues#2500
=> [2500] Object parser in tables

includes/widget/class-urlslab-widget-link-builder.php
Close https://github.com/QualityUnit/web-issues/issues/2507
=> fix: replacement of links in style tags fixed

admin/src/lib/helpers.js
url regex fix
Close QualityUnit/web-issues#2504
=> [2504] fix: url regex fix

admin/src/lib/helpers.js, includes/class-urlslab-available-widgets.php, includes/widget/class-urlslab-widget-security.php
=> I2504 fix url regex

includes/widget/class-urlslab-widget-cache.php
Close https://github.com/QualityUnit/web-issues/issues/2515
=> fix: hide warning when write is not possible

admin/src/components/OverviewTemplate.jsx, admin/src/overview/Cache.jsx, admin/src/overview/CustomHtml.jsx, admin/src/overview/Faqs.jsx, admin/src/overview/Generator.jsx, admin/src/overview/HtmlOptimizer.jsx, admin/src/overview/ImageAltAttribute.jsx, admin/src/overview/KeywordsLinks.jsx, admin/src/overview/LazyLoading.jsx, admin/src/overview/MediaOffloader.jsx, admin/src/overview/Optimize.jsx, admin/src/overview/Redirects.jsx, admin/src/overview/RelatedResources.jsx, admin/src/overview/Schedules.jsx, admin/src/overview/SearchAndReplace.jsx, admin/src/overview/Security.jsx, admin/src/overview/Serp.jsx, admin/src/overview/Urls.jsx, admin/src/overview/WebVitals.jsx
overview pages translateable
Close QualityUnit/web-issues#2503
=> [2504] fix: overview pages translateable

includes/tool/class-urlslab-tool-htaccess.php
Close https://github.com/QualityUnit/web-issues/issues/2514
=> fix: set correct cache control headers

includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-security.php
Close https://github.com/QualityUnit/web-issues/issues/2512
=> fix: add missing security headers

admin/src/api/fetching.js, admin/src/app/mui_joy/themes/buttonTheme.js, admin/src/components/SettingsOption.jsx, admin/src/components/TableFilters.jsx, includes/api/class-urlslab-api-cache-rules.php, includes/api/class-urlslab-api-faq.php, includes/api/class-urlslab-api-files.php, includes/api/class-urlslab-api-generators.php, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-optimize.php, includes/api/class-urlslab-api-permissions.php, includes/api/class-urlslab-api-process.php, includes/api/class-urlslab-api-serp-queries.php, includes/api/class-urlslab-api-serp-urls.php, includes/api/class-urlslab-api-shortcodes.php, includes/api/class-urlslab-api-table.php, includes/api/class-urlslab-api-tasks.php, includes/api/class-urlslab-api-url-relations.php, includes/api/class-urlslab-api-urls.php, includes/api/class-urlslab-api-web-vitals.php, includes/api/class-urlslab-api-youtube-cache.php, includes/widget/class-urlslab-widget.php
error message handling, #2511 query filter not working
Close QualityUnit/web-issues#2517
Close QualityUnit/web-issues#2511
=> fix: #2517 error message handling, #2511 query filter not working

includes/widget/class-urlslab-widget-security.php
Close https://github.com/QualityUnit/web-issues/issues/2521
=> fix: default csp values

includes/widget/class-urlslab-widget-cache.php
Close https://github.com/QualityUnit/web-issues/issues/2518
=> fix: db files not loaded with cache switched on

includes/tool/class-urlslab-tool-htaccess.php
Close https://github.com/QualityUnit/web-issues/issues/2520
=> fix: compute path to htaccess file

includes/api/class-urlslab-api-serp-gap.php
Close https://github.com/QualityUnit/web-issues/issues/2527
=> fix: name of columns function

admin/src/components/TableFilterPanel.jsx, admin/src/tables/FaqUrlsTable.jsx, admin/src/tables/FaqsTable.jsx
filters closing on autoselect menus (lang, country), sorting
Close QualityUnit/web-issues#2522
=> [2522] fix: filters closing on autoselect menus (lang, country), sorting

admin/src/App.jsx, admin/src/hooks/useOnboarding.jsx, admin/src/onboarding/steps/StepChooseKeywords.jsx, admin/src/onboarding/steps/StepModules.jsx, admin/src/onboarding/steps/StepPlanChoice.jsx, admin/src/onboarding/steps/StepSchedule.jsx
Ability to skip defined onboarding steps, generalized state setter function to mark correctly skipped steps.
Close QualityUnit/web-issues#2524
=> Onboarding fixes

admin/src/tables/FaqsTable.jsx
Close https://github.com/QualityUnit/web-issues/issues/2460
=> fix: add missing answer column

includes/api/class-urlslab-api-faq-urls.php
Close https://github.com/QualityUnit/web-issues/issues/2526
=> fix: faq urls - add missing columns

includes/api/class-urlslab-api-process.php
https://github.com/QualityUnit/web-issues/issues/2525
=> fix: add missing endpoint

includes/api/class-urlslab-api-user-info.php, includes/class-urlslab-activator.php, urlslab.php
=> Configured to not show Onboarding for Old Users

includes/cron/class-urlslab-cron-cache-garbage-collector.php, includes/cron/class-urlslab-cron-manager.php, includes/widget/class-urlslab-widget-cache.php
cron garbage collection - maybe we should clean cache also by standard requests????
Close https://github.com/QualityUnit/web-issues/issues/2528
=> fix: garbage collector for cron

includes/tool/class-urlslab-tool-config.php, includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-cache.php, includes/widget/class-urlslab-widget-link-builder.php
Close https://github.com/QualityUnit/web-issues/issues/2529
=> cache - show htaccess and config status

includes/api/class-urlslab-api-faq.php
Close https://github.com/QualityUnit/web-issues/issues/2535
=> fix: count of assigned urls was not correct

admin/src/App.jsx, admin/src/AppRoot.jsx, admin/src/app/router.jsx, admin/src/components/DashboardModule.jsx, admin/src/components/Header.jsx, admin/src/components/MainMenu.jsx, admin/src/hooks/useDisabledModuleRedirect.jsx, admin/src/hooks/useModuleGroups.jsx, admin/src/hooks/useModulesGroups.jsx, admin/src/hooks/useOnloadRedirect.jsx, admin/src/hooks/usePageTitle.jsx, admin/src/lib/helpers.js, admin/src/modules/static/Modules.jsx, admin/src/modules/static/Page404.jsx
Fixed access to inactive modules via direct route.
Modules groups added to router instead of state management of already opened group page.
Fixed minor issues described in QualityUnit/web-issues#2489 
Close QualityUnit/web-issues#2489
=> I2489 inactive modules routes

includes/class-urlslab-activator.php, table-names.php, uninstall.php, urlslab.php
https://github.com/QualityUnit/web-issues/issues/2544
=> fix: remove not needed table error_log

admin/src/elements/TreeView.jsx
Allow TreeView component to render string as simple text, if is provided instead of json string.
If input string is not valid json, will render that text.
ie.:
Close QualityUnit/web-issues#2516
=> fix: allow non-json string to show instead of tree view

includes/tool/class-urlslab-tool-config.php
**Checklist**
Close QualityUnit/web-issues#2530
=> fix: compute path to config

includes/api/class-urlslab-api-process.php, includes/connection/class-urlslab-connection-augment.php, includes/executor/class-urlslab-executor-generate-url-context.php, includes/executor/class-urlslab-executor-generate.php, includes/tool/class-urlslab-tool-config.php
Close https://github.com/QualityUnit/web-issues/issues/2542
=> fix: fix advanced cache code and remove markdown from generator

admin/src/components/TableFilterPanel.jsx
removed condition for save button disabled
Close QualityUnit/web-issues#2533
=> [2533] fix: removed condition for save button disabled

advanced-cache.php, includes/api/class-urlslab-api-cache-rules.php, includes/tool/class-urlslab-tool-config.php, includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-cache.php
- we need to resolve case, when it is logged in user ... in such case we don't send the case header
Close QualityUnit/web-issues#2448
=> fix: set cache also based on the other rules

includes/api/class-urlslab-api-cache-rules.php, includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-cache.php, includes/widget/class-urlslab-widget-redirects.php, uninstall.php
Close QualityUnit/web-issues#2548
=> feat: add redirects to htaccess

includes/api/class-urlslab-api-process.php, includes/class-urlslab-activator.php, includes/executor/class-urlslab-executor-generate.php, urlslab.php
**Checklist**
Close QualityUnit/web-issues#2539
Close QualityUnit/web-issues#2540
Close QualityUnit/web-issues#2546
=> bug fixes generator

admin/src/components/generator/manual/StepFirst.jsx, admin/src/components/generator/manual/StepSecond.jsx, admin/src/hooks/useAIGeneratorManualInit.jsx, admin/src/lib/aiGeneratorPanel.js, admin/src/lib/serpQueries.js
Country selection moved to the first step of manual AI Generator.
Payload for `query-cluster` request in the first step has to include `country` key.
Close QualityUnit/web-issues#2506
=> fix: ai generator country selection in first step

includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-cache.php
Close https://github.com/QualityUnit/web-issues/issues/2552
=> feat: fix www to nonwww redirects

includes/api/class-urlslab-api-cache-rules.php, includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-cache.php
Close QualityUnit/web-issues#2553
=> feat: drop cache for edited page

includes/api/class-urlslab-api-files.php, includes/api/class-urlslab-api-urls.php, includes/class-urlslab-activator.php, includes/cron/class-urlslab-cron-manager.php, includes/cron/class-urlslab-cron-update-usage-stats.php, includes/data/class-urlslab-data-url.php, includes/widget/class-urlslab-widget-media-offloader.php, includes/widget/class-urlslab-widget-urls.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2554
=> fix: performance problems with usage stats

includes/api/class-urlslab-api-cache-rules.php, includes/api/class-urlslab-api-configs.php, includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-cache.php, includes/widget/class-urlslab-widget-general.php, includes/widget/class-urlslab-widget-redirects.php, includes/widget/class-urlslab-widget-security.php
**Checklist**
Close QualityUnit/web-issues#2556
=> fix: htaccess rules

includes/class-urlslab-public.php
**Checklist**
Close QualityUnit/web-issues#2555
=> fix: duplicated js code in footer

includes/api/class-urlslab-api-serp-urls.php, includes/api/class-urlslab-api-table.php
Close https://github.com/QualityUnit/web-issues/issues/2562
=> fix: fatal error in query columns

includes/tool/class-urlslab-tool-htaccess.php
Close https://github.com/QualityUnit/web-issues/issues/2558
=> fix: empty htaccess rewrite section

includes/widget/class-urlslab-widget-security.php
Close https://github.com/QualityUnit/web-issues/issues/2564
=> fix: rate limit should not lock download requests

admin/src/charts/WebVitalsCharts.jsx, admin/src/components/charts/elements.jsx, admin/src/lib/helpers.js
charts show last 7 days results by default
=> fix: web vitals charts last 7 days by default

includes/connection/class-urlslab-connection-related-urls.php, includes/cron/class-urlslab-cron-generator.php, includes/cron/class-urlslab-cron-related-resources.php, includes/cron/class-urlslab-cron-serp-volumes.php, includes/cron/class-urlslab-cron-serp.php, includes/cron/class-urlslab-cron-youtube.php
Close https://github.com/QualityUnit/web-issues/issues/2565
=> fix: refactoring init_client (not used anymore), catch connection exception

includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-cache.php
Close https://github.com/QualityUnit/web-issues/issues/2567
=> fix: stop preloading same url if difference is just / at the end of url

includes/widget/class-urlslab-widget-cache.php
Close QualityUnit/web-issues#2569
=> fix: send 404 header for not found cached page.

admin/src/tables/SearchReplaceTable.jsx
menu in search replace
Close QualityUnit/web-issues#2560
=> [2560] fix: menu in search replace

README.md, includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-serp.php, readme.txt
Close https://github.com/QualityUnit/web-issues/issues/2570
=> feat: default settings for serp

includes/tool/class-urlslab-tool-htaccess.php
Close QualityUnit/web-issues#2571
=> fix: change http to https redirect

includes/api/class-urlslab-api-serp-competitors.php, includes/data/class-urlslab-data-serp-domain.php
Close https://github.com/QualityUnit/web-issues/issues/2577
=> fix: add missing filter value for domain type

includes/api/class-urlslab-api-faq.php, includes/api/class-urlslab-api-files.php, includes/api/class-urlslab-api-generators.php, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-shortcodes.php, includes/api/class-urlslab-api-url-relations.php, includes/api/class-urlslab-api-urls.php
Close https://github.com/QualityUnit/web-issues/issues/2574
=> fix: deleting related resources

admin/src/components/TableFilterPanel.jsx, admin/src/elements/RefreshTableButton.jsx
Fixes date filtering on time select not working, forces all recordset (query cache) to refresh when Refresh button clicked (multiple fetch called!!!)
Close QualityUnit/web-issues#2573
Close QualityUnit/web-issues#2575
=> fix: #2573, #2575

includes/data/class-urlslab-data-redirect.php, includes/data/class-urlslab-data.php
Close https://github.com/QualityUnit/web-issues/issues/2585
=> fix: add missing filter enum types to redirects table

admin/src/assets/styles/components/_ModuleViewHeader.scss
added underline for active button in tables
Close QualityUnit/web-issues#2582
=> [2582] fix: added underline for active button in tables

includes/api/class-urlslab-api-faq.php
Close https://github.com/QualityUnit/web-issues/issues/2584
=> fix: sorting in faqs api

includes/class-urlslab-public.php
Close QualityUnit/web-issues#2598
=> fix: defer loading of lazy loading script

includes/api/class-urlslab-api-configs.php, includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-cache.php, includes/widget/class-urlslab-widget-general.php, includes/widget/class-urlslab-widget-security.php
Close QualityUnit/web-issues#2605
=> fix: update htaccess when something changed, send csp headers also without htaccess

includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-cache.php
Close QualityUnit/web-issues#2609
=> fix: refactoring htaccess rules

includes/api/class-urlslab-api-security.php, includes/widget/class-urlslab-widget-security.php
Close QualityUnit/web-issues#2615
=> fix: CSP validation

includes/api/class-urlslab-api-web-vitals.php, includes/data/class-urlslab-data-web-vital.php
Close QualityUnit/web-issues#2599
=> fix: validate input value of web vitals

admin/src/elements/BrowserSelect.jsx, admin/src/hooks/useChangeRow.jsx
filter panel closing on bot selection
Should fix FAQ updates UI Bug decoder error
Close QualityUnit/web-issues#2616
Close QualityUnit/web-issues#2607
=> [2616] fix: filter panel closing on bot selection

admin/src/components/detailsPanel/GapDetailPanel.jsx, admin/src/components/detailsPanel/gapDetailPanelParts/GapDetailUrlsSettings.jsx, admin/src/elements/TableSortBy.jsx, admin/src/tables/SerpContentGapTable.jsx
1. allowed submit of content gap changes without defined `query` param
2. improved displaying of proper state icons in urls inputs according to current input value
3. fixed read minified error bug on `SortBy` component while table header is not defined in global state
Close QualityUnit/web-issues#2619
=> Content gap bugfixes

includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-cache.php
Close https://github.com/QualityUnit/web-issues/issues/2568
=> fix: static files were missing cache headers

includes/tool/class-urlslab-tool-config.php, includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-cache.php, includes/widget/class-urlslab-widget-general.php, includes/widget/class-urlslab-widget-security.php
Close https://github.com/QualityUnit/web-issues/issues/2623
=> fix: update htaccess file each time we discover requirement to update it

includes/class-urlslab-activator.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2632
=> fix: add again update steps to add missing columns

includes/tool/class-urlslab-tool-htaccess.php
Close https://github.com/QualityUnit/web-issues/issues/2637
=> fix: lock htaccess file during locking

advanced-cache.php, includes/widget/class-urlslab-widget-html-optimizer.php, includes/widget/class-urlslab-widget-lazy-loading.php, includes/widget/class-urlslab-widget-media-offloader.php, includes/widget/class-urlslab-widget-security.php
Close https://github.com/QualityUnit/web-issues/issues/2631
=> fix: duplicate headers fix

includes/api/class-urlslab-api-serp-gap.php, includes/api/class-urlslab-api-serp-queries.php, includes/api/class-urlslab-api-serp-urls.php, includes/data/class-urlslab-data-gsc-site.php, includes/data/class-urlslab-data-serp-query.php
=> fix: column types

admin/src/app/mui_joy/themes/tableTheme.js, admin/src/components/DeletePanel.jsx, admin/src/components/TableComponent.jsx
Fixing various small bugs (not related to UI speed)
=> I2586 speed of UI

advanced-cache.php, includes/tool/class-urlslab-tool-htaccess.php
Close QualityUnit/web-issues#2659
=> fix: advanced cache moved to app

includes/api/class-urlslab-api-redirects.php
Close https://github.com/QualityUnit/web-issues/issues/2653
=> fix: ip address field validation

includes/data/class-urlslab-data-not-found-log.php, includes/widget/class-urlslab-widget-cache.php
Close https://github.com/QualityUnit/web-issues/issues/2661
=> fix: insert log not found

includes/cron/class-urlslab-cron-serp.php, includes/driver/class-urlslab-driver-file.php, includes/widget/class-urlslab-widget-html-optimizer.php, includes/widget/class-urlslab-widget-lazy-loading.php, includes/widget/class-urlslab-widget-media-offloader.php
Close QualityUnit/web-issues#2663
=> offloaded images not found

admin/src/components/DynamicModule.jsx, admin/src/elements/ColumnsMenu.jsx, admin/src/elements/MenuInput.jsx, admin/src/elements/MultiSelectMenu.jsx, admin/src/elements/RangeSlider.jsx, admin/src/elements/SingleSelectMenu.jsx, admin/src/elements/SuggestInputField.jsx, admin/src/elements/TableActionsMenu.jsx, admin/src/elements/TagsFilterMenu.jsx, admin/src/hooks/useCloseModal.jsx
Fixed adding and removal of events listener added by components.
Close QualityUnit/web-issues#2586
=> I2586 UI speed - resolved events listeners adding/removing

admin/src/components/TableFilter.jsx
Fixed condition in TableFilter component to render filtered value.
Close QualityUnit/web-issues#2666
=> fix: table filter condition

includes/data/class-urlslab-data-not-found-log.php
Close QualityUnit/web-issues#2667
=> fix: logging

admin/src/charts/web-vitals/MetricChart.jsx, admin/src/charts/web-vitals/MetricCountryChart.jsx, admin/src/components/charts/AreaChart.jsx, admin/src/components/charts/WorldMapChart.jsx, admin/src/lib/metricChartsHelpers.jsx, admin/src/tables/WebVitalsTable.jsx, includes/api/class-urlslab-api-web-vitals.php, includes/class-urlslab-activator.php, includes/data/class-urlslab-data-web-vital.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/2599
=> fix: convert ms to seconds for some web vitals

admin/src/onboarding/steps/StepChooseCompetitors.jsx, admin/src/onboarding/steps/StepModules.jsx
Fixed activation of modules on onboarding finish for free plan.
Fixed width of table cell for domain type in choose competitor step.
Close QualityUnit/web-issues#2673
=> fix: onboarding free user modules activation

admin/src/tables/GeneratorPromptTemplateTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx
Fix: changing layout of edit row panels for wide area editors like TextArea and TinyMCE
=> fix: changing layout of more edit panels

includes/api/class-urlslab-api-keywords.php, includes/data/class-urlslab-data-keyword.php
@ihdk try if it solves your problem
Close https://github.com/QualityUnit/web-issues/issues/2675
=> fix: hide kw_hash from api results

includes/widget/class-urlslab-widget-general.php
Close https://github.com/QualityUnit/web-issues/issues/2680
=> fix: init rewrite rules with each init event

includes/api/class-urlslab-api-serp-queries.php
**Checklist**
Close QualityUnit/web-issues#2678
=> fix: creating new serp queries

blocks/src/blocks/ai-content/edit.js
not possible to change shortcode in ai content widget
Close QualityUnit/web-issues#2480
=> [2480[ fix: not possible to change shortcode in ai content widget

admin/src/elements/RefreshTableButton.jsx
Fix for refresh launches count fetch 2x
Close QualityUnit/web-issues#2686
=> [2686] fix: refresh launches count fetch 2x

includes/driver/class-urlslab-driver.php, includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-media-offloader.php, includes/widget/class-urlslab-widget-redirects.php
Close https://github.com/QualityUnit/web-issues/issues/2684
=> fix: recognition of local system files

uninstall.php
Close https://github.com/QualityUnit/web-issues/issues/2689
=> fix: fix uninstall process

includes/data/class-urlslab-data-serp-query.php
Close https://github.com/QualityUnit/web-issues/issues/2690
=> fix: serp types

includes/class-urlslab-admin.php, includes/tool/class-urlslab-tool-config.php, includes/tool/class-urlslab-tool-htaccess.php, includes/widget/class-urlslab-widget-cache.php, includes/widget/class-urlslab-widget-media-offloader.php, uninstall.php
Close https://github.com/QualityUnit/web-issues/issues/2689
=> deactivation of plugin

includes/cron/class-urlslab-cron-convert-avif-images.php, includes/cron/class-urlslab-cron-convert-webp-images.php, includes/driver/class-urlslab-driver-file.php, includes/driver/class-urlslab-driver.php
Close https://github.com/QualityUnit/web-issues/issues/2688
=> fix: webp images were not created on local filesystem

admin/src/tables/CSPViolationsTable.jsx
Close https://github.com/QualityUnit/web-issues/issues/2693
=> fix: delete with full primary column

admin/src/modules/static/Settings.jsx
Refetch settings on mount
Close QualityUnit/web-issues#2620
=> [2620] fix: refetching settings

includes/data/class-urlslab-data-file.php
Close https://github.com/QualityUnit/web-issues/issues/2695
=> fix: remove hash in file name

composer.lock, includes/api/class-urlslab-api-url-map.php, includes/api/class-urlslab-api-urls.php, includes/class-urlslab-activator.php, includes/class-urlslab-url.php, includes/data/class-urlslab-data-url-fetcher.php, includes/data/class-urlslab-data-url-map.php, includes/data/class-urlslab-data-url.php, includes/data/class-urlslab-data.php, includes/widget/class-urlslab-widget-urls.php, index.php, urlslab.php
Close QualityUnit/web-issues#2697
=> compute correct links for corrupted wpml links

includes/cron/class-urlslab-cron-convert-avif-images.php, includes/cron/class-urlslab-cron-convert-webp-images.php, includes/data/class-urlslab-data.php
Close QualityUnit/web-issues#2699
=> fix: duplicate error warning.

includes/api/class-urlslab-api-generators.php, includes/api/class-urlslab-api-security.php, includes/widget/class-urlslab-widget-related-resources.php
Close QualityUnit/web-issues#2705
Close https://github.com/QualityUnit/web-issues/issues/2703
=> related resources, ai generator small fixes

composer.lock, includes/api/class-urlslab-api-serp-queries.php, includes/api/class-urlslab-api-serp-urls.php, includes/api/class-urlslab-api-table-sql.php, includes/api/class-urlslab-api-table.php
Close https://github.com/QualityUnit/web-issues/issues/2717
=> fix sql error

includes/cron/class-urlslab-cron-offload-enqueue-files.php, includes/data/class-urlslab-data-file.php, includes/driver/class-urlslab-driver-db.php, includes/driver/class-urlslab-driver-file.php, includes/driver/class-urlslab-driver.php
Close QualityUnit/web-issues#2726
=> fix: system files

includes/data/class-urlslab-data-url-fetcher.php
Close QualityUnit/web-issues#2715
=> fix: improve speed of sql

admin/src/tables/UrlsTable.jsx, includes/class-urlslab-url.php, includes/data/class-urlslab-data-url-fetcher.php, includes/data/class-urlslab-data-url.php, includes/widget/class-urlslab-widget-cache.php, includes/widget/class-urlslab-widget-html-optimizer.php, includes/widget/class-urlslab-widget-link-builder.php, includes/widget/class-urlslab-widget-media-offloader.php, includes/widget/class-urlslab-widget-related-resources.php, includes/widget/class-urlslab-widget-urls.php
Close QualityUnit/web-issues#2730
=> fir repeating urls

includes/data/class-urlslab-data-url.php
Close https://github.com/QualityUnit/web-issues/issues/2737
=> fix: sql error

includes/data/class-urlslab-data-url.php
visibility seems to be ok, type fixed
Close https://github.com/QualityUnit/web-issues/issues/2761
=> fix: update correctly url type when checking url status

includes/widget/class-urlslab-widget-html-optimizer.php
Close https://github.com/QualityUnit/web-issues/issues/2764
Close https://github.com/QualityUnit/web-issues/issues/2765
Close https://github.com/QualityUnit/web-issues/issues/2766
=> feat: remove wp emoji

includes/api/class-urlslab-api-cache-rules.php, includes/api/class-urlslab-api-custom-html.php, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-redirects.php, includes/api/class-urlslab-api-search-replace.php, includes/api/class-urlslab-api-serp-queries.php, includes/api/class-urlslab-api-table.php, includes/api/class-urlslab-api-urls.php, includes/data/class-urlslab-data-url.php
Close QualityUnit/web-issues#2769
=> fix: 404 case of single slug

includes/class-urlslab.php, includes/widget/class-urlslab-widget-html-optimizer.php
Close https://github.com/QualityUnit/web-issues/issues/2763
=> fix: never exceed html file size

includes/class-urlslab-url.php, includes/class-urlslab.php, includes/widget/class-urlslab-widget-related-resources.php
Close https://github.com/QualityUnit/web-issues/issues/2771
=> end tag of html was missing

admin/src/components/ContentGapMonitoringPanel.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/components/RowCounter.jsx, admin/src/components/TableToolbar.jsx, admin/src/components/detailsPanel/QueryDetailPanel.jsx, admin/src/components/detailsPanel/UrlDetailPanel.jsx, admin/src/elements/Tooltip_SortingFiltering.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/hooks/useInfiniteFetch.jsx, admin/src/hooks/useTableStore.jsx, admin/src/modules/Serp.jsx, admin/src/tables/SerpContentGapTable.jsx, admin/src/tables/SerpQueriesTable.jsx, admin/src/tables/SerpQueryDetailClusterUrlsTable.jsx, admin/src/tables/SerpQueryDetailQueryClusterTable.jsx, admin/src/tables/SerpQueryDetailRankedUrlsTable.jsx, admin/src/tables/SerpUrlDetailQueryTable.jsx, admin/src/tables/SerpUrlDetailSimilarUrlsTable.jsx, admin/src/tables/SerpUrlsTable.jsx
1) editing Serp Queries table rows from other tables: Serp Query detail Cluster, Serp Query content gap, Serp URLs detail.
- passing required api information from these tables using `sourceTableInfo` table state, so `useChangeRow()` hook can use correct api details even the hook is called from another table
- passing `relatedQueries` information with table state, so `useChangeRow()` hook can invalidate also other queries which are possibly already cached and showing this row.
2) `useChangeRow()`
- accept api details from table state `sourceTableInfo` if currently active table is another than table which slug, paginationId and optionalSelector are used for api calls.
- in mutation methods added try-catch to log possible errors. Errors thrown in …
=> I2709 serp queries detail panel

includes/cron/class-urlslab-cron-download-css.php, includes/cron/class-urlslab-cron-download-js.php, includes/widget/class-urlslab-widget-cache.php, includes/widget/class-urlslab-widget-html-optimizer.php
Close https://github.com/QualityUnit/web-issues/issues/2763
=> remove useless settings in html optimization

composer.lock, includes/widget/class-urlslab-widget-html-optimizer.php
Close https://github.com/QualityUnit/web-issues/issues/2766
=> feat: new section for removed elements

includes/class-urlslab-url.php
Close https://github.com/QualityUnit/web-issues/issues/2745
=> fix: redirects without protocol evaluated as 404

includes/widget/class-urlslab-widget-search-replace.php
https://github.com/QualityUnit/web-issues/issues/2780
=> fix: matching url in search and replace

includes/widget/class-urlslab-widget-search-replace.php
Close https://github.com/QualityUnit/web-issues/issues/2780
=> fix: search and replace in content before our processing

admin/src/tables/SearchReplaceTable.jsx
Close https://github.com/QualityUnit/web-issues/issues/2781
=> fix: login_status was not possible to change in table

includes/cron/class-urlslab-cron-generator.php, includes/cron/class-urlslab-cron-related-resources.php, includes/cron/class-urlslab-cron-serp.php, includes/cron/class-urlslab-cron-summaries.php, includes/cron/class-urlslab-cron-youtube.php, includes/executor/class-urlslab-executor-generate.php
Close QualityUnit/web-issues#2820
=> postpone cron if urlslab service dies

blocks/includes/blocks/class-urlslab-blocks-ai-content.php, blocks/includes/blocks/class-urlslab-blocks-faqs-elementor.php, blocks/includes/blocks/class-urlslab-blocks-faqs.php, blocks/includes/blocks/class-urlslab-blocks-related-articles-elementor.php, blocks/includes/blocks/class-urlslab-blocks-related-articles.php, blocks/includes/blocks/class-urlslab-blocks-screenshot-elementor.php, blocks/includes/blocks/class-urlslab-blocks-screenshot.php, blocks/includes/blocks/class-urlslab-blocks-tableofcontents.php, blocks/includes/blocks/class-urlslab-blocks-youtubedata-elementor.php, blocks/includes/blocks/class-urlslab-blocks-youtubedata.php, composer.lock, includes/api/class-urlslab-api-generators.php, includes/connection/class-urlslab-connection-augment.php
removed not used code, but deprecated functions were not replaced yet
QualityUnit/web-issues#2821
=> chore: removed not used api call, updated composer

includes/widget/class-urlslab-widget-related-resources.php
Close QualityUnit/web-issues#2851
=> chore: add alt text to default image

includes/widget/class-urlslab-widget-urls.php
Close https://github.com/QualityUnit/web-issues/issues/2805
=> fix: hidden links removed also text of the link

includes/widget/class-urlslab-widget-media-offloader.php
Close https://github.com/QualityUnit/web-issues/issues/2836
=> feat: convert background images to next gen formats

includes/widget/class-urlslab-widget-media-offloader.php
=> feat: replace file just if it is smaller

includes/class-urlslab-public.php, includes/widget/class-urlslab-widget-content-generator.php
Removing plugin jQuery dependencies which blocked Lazyload and other plugin features
=> fix: removing jquery dependencies

admin/apps/ai-content-assistant/package.json, admin/apps/ai-content-assistant/yarn.lock, admin/yarn.lock, blocks/package.json, blocks/yarn.lock, package.json, yarn.lock
Upgrading node packages for better compatibility with Node 20
Close QualityUnit/web-issues#2863
=> [2863] feat: upgrading node packages

includes/widget/class-urlslab-widget-urls.php
Close https://github.com/QualityUnit/web-issues/issues/2861
=> fix: relative path should not open in new window

includes/widget/class-urlslab-widget-cache.php
Close https://github.com/QualityUnit/web-issues/issues/2872
=> fix: logged in user will not use cache

includes/cron/class-urlslab-cron-serp.php
Close https://github.com/QualityUnit/web-issues/issues/2922
=> fix: fatal error explode

includes/data/class-urlslab-data-file.php, includes/driver/class-urlslab-driver.php
Close QualityUnit/web-issues#2935
=> fix: add extension to file without extension based on the content type

includes/api/class-urlslab-api-serp-domains.php
Close https://github.com/QualityUnit/web-issues/issues/2929
=> fix: increase limit when we ignore domains without serp positions

includes/tool/class-urlslab-tool-config.php
Close https://github.com/QualityUnit/web-issues/issues/2911
=> fix: ensure the cache feature is disabled when the cache module is turned off

includes/data/class-urlslab-data-file.php
Close QualityUnit/urlslab-issues#115
=> feat: fix - missing extension in image file

includes/widget/class-urlslab-widget-lazy-loading.php
Close https://github.com/QualityUnit/urlslab-issues/issues/113
=> feat: fix lazyloading for carousel

includes/api/class-urlslab-api-serp-queries.php, includes/api/class-urlslab-api-table.php
Close https://github.com/QualityUnit/urlslab-issues/issues/132
=> fix: sql error in queries cluster

includes/widget/class-urlslab-widget-general.php, includes/widget/class-urlslab-widget-lazy-loading.php, includes/widget/class-urlslab-widget-related-resources.php
Close QualityUnit/urlslab-issues#218
=> debug messages

blocks/src/blocks/tableofcontents/edit.js
table of contents bug due to changes in wp api
Close QualityUnit/urlslab-issues#419
=> [419] fix: table of contents bug due to changes in wp api

includes/widget/class-urlslab-widget-link-builder.php
Close QualityUnit/urlslab-issues#924
=> linkbuilding fix

includes/widget/class-urlslab-widget-general.php
Close QualityUnit/urlslab-issues#979
=> fix: allow to unset api key

readme.txt
increased version of the plugin
**Checklist**
=> chore: change readme

.github/scripts/build-files.sh
https://github.com/QualityUnit/urlslab-issues/issues/995
**Checklist**
Close QualityUnit/urlslab-issues#[ISSUE_NUMBER]
=> exclude deleting of identity

composer.lock, includes/api/class-urlslab-api-billing.php
Close https://github.com/QualityUnit/urlslab-issues/issues/1019
=> fix: urlslab incorrect credits

admin/src/overview/Generator.jsx, composer.lock, includes/connection/class-urlslab-connection-related-urls.php, includes/cron/class-urlslab-cron-faq.php, includes/cron/class-urlslab-cron-generator.php, includes/data/class-urlslab-data-task.php, includes/executor/class-urlslab-executor-generate.php, includes/widget/class-urlslab-widget-content-generator.php, includes/widget/class-urlslab-widget-related-resources.php
Close QualityUnit/urlslab-issues#1017
=> filter related articles by domains

includes/class-urlslab-url.php, includes/cron/class-urlslab-cron-screenshots.php, includes/cron/class-urlslab-cron-summaries.php, includes/widget/class-urlslab-widget-general.php
Close https://github.com/QualityUnit/urlslab-issues/issues/1069
=> fix: blacklist path in urls

admin/src/tables/UrlsTable.jsx, includes/class-urlslab-activator.php, includes/cron/class-urlslab-cron-screenshots.php, includes/cron/class-urlslab-cron-summaries.php, includes/data/class-urlslab-data-url.php, readme.txt, urlslab.php
Close QualityUnit/urlslab-issues#1120
=> fix: check content type of request to process summary

includes/data/class-urlslab-data-serp-query.php, includes/data/class-urlslab-data-serp-url.php
Close QualityUnit/urlslab-issues#1129
=> fix: decrease number of updated rows in one sql

includes/connection/class-urlslab-connection-youtube.php
Close QualityUnit/urlslab-issues#1127
=> fix: handle failed youtube tasks correctly

includes/executor/class-urlslab-executor-generate.php
Close QualityUnit/urlslab-issues#1123
=> fix: fix ratelimit when generating texts

admin/src/tables/GeneratorShortcodeTable.jsx, includes/api/class-urlslab-api-shortcodes.php, includes/class-urlslab-activator.php, includes/cron/class-urlslab-cron-generator.php, includes/data/class-urlslab-data-generator-shortcode.php, includes/widget/class-urlslab-widget-content-generator.php, urlslab.php
Close QualityUnit/urlslab-issues#986
=> fix: auto approve per shortcode

blocks/includes/blocks/class-urlslab-blocks-youtubedata-elementor.php, blocks/includes/blocks/class-urlslab-blocks-youtubedata.php, composer.lock, includes/data/class-urlslab-data-youtube.php, includes/widget/class-urlslab-widget-content-generator.php, includes/widget/class-urlslab-widget-lazy-loading.php
Close QualityUnit/urlslab-issues#1139
=> fix: fix youtube date

includes/cron/class-urlslab-cron-generator.php
Close https://github.com/QualityUnit/urlslab-issues/issues/1148
=> fix: null result

includes/class-urlslab-url.php, includes/widget/class-urlslab-widget-urls.php
Close QualityUnit/urlslab-issues#1153
=> fix: fix doubleslashess

admin/js/urlslab-wpml.js
When tinyMCE editor not initialized or not stored in window object, fallback to store translated value into textarea.
tinyMCE editor is not initialized and all editors are not stored in window object when admin page loads with "Text" version of editors turned on by default, necessary is even switch to Visual version of editor, or fallback implemented in this pr will be applied.
Close QualityUnit/urlslab-issues#1186
=> fix: not initialized tinyMCE fallback to textarea

admin/src/assets/styles/components/_Panel.scss, admin/src/components/EditRowPanel.jsx, admin/src/tables/GeneratorResultTable.jsx
customized Generator Results edit row modal content. Textarea gets most height as can in viewport.
Close QualityUnit/urlslab-issues#1202
=> feat: generator results edit modal full height textarea

admin/js/urlslab-wpml.js, includes/api/class-urlslab-api-generators.php
Refactored translations script.
Fixed general bulk translation, divided into separated batches, automated transaltion retry when pending for translation or failed because of too many requests.
Fixed "translate all empty" functionality.
Added buttons with functionality:
Translate all not completed translations (all fields not marked as completed).
Translate all fields (including these marked as completed).
Close QualityUnit/urlslab-issues#1223
=> I1223 translations

admin/src/tables/KeywordsTable.jsx, composer.lock, includes/api/class-urlslab-api-keywords.php
replaced keyword input with textarea
Close QualityUnit/urlslab-issues#1248
=> [1248] fix: replaced keyword input with textarea

includes/api/class-urlslab-api-generators.php
Close QualityUnit/urlslab-issues#1287
=> fix: if there is nothing to translate, skip translation

includes/api/class-urlslab-api-generators.php
Close QualityUnit/urlslab-issues#1291
=> fix: translation loops

includes/connection/class-urlslab-connection-related-urls.php
Close https://github.com/QualityUnit/urlslab-issues/issues/1246
=> fix: if url not indexed yet, search by query text

includes/widget/class-urlslab-widget-lazy-loading.php
Close https://github.com/QualityUnit/urlslab-issues/issues/1359
=> fix: fatal error in css decoration of yt video

includes/class-urlslab-admin.php
Close https://github.com/QualityUnit/urlslab-issues/issues/1358
=> fix: hide useless message in admin toolbar

admin/js/urlslab-wpml.js
wysiwyg editor update synch with related textarea
Close QualityUnit/urlslab-issues#1370
=> fix: wysiwyg editor update synch with related textarea

includes/widget/class-urlslab-widget-link-builder.php
Close https://github.com/QualityUnit/urlslab-issues/issues/1599
=> fix: linkbuilding skipped words with invalid value valid_until

admin/src/api/fetchLangs.js, composer.lock
Close QualityUnit/urlslab-issues#1709
=> feat: allow change link language back to all

admin/js/urlslab-wpml.js
added small changes in urlslab-wpml script
**Checklist**
=> fix: added small changes in urlslab-wpml script

readme.txt
=> chore: increase version

includes/widget/class-urlslab-widget-urls.php
https://github.com/QualityUnit/flowhunt-issues/issues/1753
=> set nofollow norefferrer noopener

blocks/includes/blocks/class-urlslab-blocks-tableofcontents.php
Added anchor for heading if was not filled for correct working of toc block
- Go to any post with TOC block and check correct work
**Checklist**
Close QualityUnit/urlslab-issues#3368
=> [3368] - fix: table of contents doesn’t work properly

includes/api/class-urlslab-api-files.php
with all other files will be deleted also contents table
=> feat: delete all should delete also file contents
