includes/driver/class-urlslab-driver.php
during upload of file to driver we can update image dimensions
**Checklist**
Close QualityUnit/web-issues/issues/675
=> fix: set image height and width if missing during transfer

composer.json, composer.lock, includes/class-urlslab-activator.php, includes/class-urlslab.php, includes/cron/class-urlslab-convert-images-cron.php, includes/cron/class-urlslab-offload-cron.php, includes/cron/class-urlslab-screenshot-cron.php, includes/driver/class-urlslab-driver.php, includes/services/class-urlslab-file-data.php, includes/widgets/class-urlslab-media-offloader-widget.php, urlslab.php
webp files are generated on the background and served as picture alternative
**Checklist**
Close QualityUnit/web-issues/issues/669
=> feat: convert images to webp and serve them as alternative

includes/class-urlslab.php
added meta tags functionality. added the feature to add the corresponding WP action only if the widget is activated
From now on in LA installations, the meta tags widget should be deactivated in order to avoid incompatiblities with LA theme and urlslab plugin. The header action is called multiple times from the code in urlslab plugin which is addressed in https://github.com/QualityUnit/web-issues/issues/761
**Checklist**
Close QualityUnit/web-issues/issues/760
=> added meta tags functionality

includes/widgets/class-urlslab-image-alt-text.php, includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-media-offloader-widget.php
fixed lazy loading of videos by changing the order of widget evaluation on content
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/833
=> fix: lazy loading for videos

includes/class-urlslab.php
changed order of hook template_redirect evaluation
downloads should be handled before the redirect
Close https://github.com/QualityUnit/web-issues/issues/1309
=> fix: don't log urlslab download files as 404

admin/src/components/SettingsOption.jsx, includes/api/class-urlslab-api-files.php, includes/driver/class-urlslab-driver-s3.php, includes/widgets/class-urlslab-media-offloader-widget.php
I still don't know exact names of ENV variables for AWS, currently is possible to use env variables:
urlslab_AWS_S3_bucket
urlslab_AWS_S3_region
urlslab_AWS_S3_access_key
urlslab_AWS_S3_secret
Close https://github.com/QualityUnit/web-issues/issues/1474
=> fix: fatal error to read env variable, s3 connection validation

includes/cron/class-urlslab-generators-cron.php, includes/widgets/class-urlslab-content-generator-widget.php
- track shortcode from first view
- don't store computed variables in shortcode
=> fix: don't store in attributes computed variables of shortcode

includes/data/class-urlslab-redirect-row.php
- insert fixed
- still not working UI ... when I insert new row and switch to Redirects table, count is updated, but list of rows is not refreshed and new row is not visible in the table
=> fix: recompute hash before insert

admin/src/components/OverviewTemplate.jsx, admin/src/modules/Schedule.jsx, admin/src/overview/Schedules.jsx
Overview for schedules fixed. No /wp-json/urlslab/v1/billing/credits/events/count endpoint, add it please and counting will work (it HAS to be /wp-json/urlslab/v1/billing/credits/events/count as slug for table is /wp-json/urlslab/v1/billing/credits/events)
Close QualityUnit/web-issues#1524
=> [1524] fix: overview

admin/src/components/SettingsOption.jsx
Allowing to use Textarea element in Settings.
Type coming from api should be set to 'textarea'.
Options are same as for Inputfield
=> feat: textarea in settings

admin/src/tables/ScreenshotTable.jsx
removed sorting on screenshot column - it is not possible to sort on computed column
filter should be removed as well (not done yet)
https://github.com/QualityUnit/web-issues/issues/1585
=> fix: screenshot url is computed value, it can not be used for sorting

includes/cron/class-urlslab-convert-avif-images-cron.php, includes/cron/class-urlslab-convert-webp-images-cron.php
added validation if module is activated
Close https://github.com/QualityUnit/wp-urlslab/issues/903
=> fix: if media offloader module not active, cron crashed

admin/src/assets/styles/components/_MainMenu.scss
fixed main menu width to fill wanted space even there are no so long menu items
Close QualityUnit/web-issues#1721
=> [Bug]: Wrong width of side menu when is nothing activated

admin/src/components/ChangesPanel/ChangesPanel.jsx, admin/src/modules/static/Schedule.jsx
#1801:
Fixed error in Schedules module.
There was missing moduleId as it was loaded automatically for all modules. Schedules module isn't included in api response with other modules, thus loaded id was undefined.
#1797:
Fixed checking for success table query result. Query always returned empty array this was considered as success even thats not true. 
Updated checking for query success on all places where result data could be manipulated.
#1801:
Should not be present error in console while switching between subpages on module page.
Last visited subpage on module should be saved in internal db.
#1797:
Should be displayed notification message if table query to get results failed.
Close QualityUnit/web-issues#1801
Close …
=> [Bug]: Schedules JS Error & URL Monitoring popup notification

admin/src/elements/Editor.jsx
missing media plugin in TinyMCE when media btn configured caused slow initialization of TinyMCE
=> fix: missing media plugin when media btn configured

admin/src/components/TableFilterPanel.jsx
Reverting back disabled parameter for column selection filter on edit
Close QualityUnit/web-issues#1889
=> [1889] fix: reverting disabled for existing filter

admin/src/app/router.jsx, admin/src/components/MainMenu.jsx, admin/src/components/ModuleViewHeader.jsx, admin/src/hooks/useModuleDataByRoute.jsx, admin/src/hooks/useModuleSectionRoute.jsx, admin/src/hooks/usePageTitle.jsx, admin/src/lib/helpers.js, admin/src/modules/Cache.jsx, admin/src/modules/CssOptimizer.jsx, admin/src/modules/CustomHtml.jsx, admin/src/modules/Faq.jsx, admin/src/modules/Generator.jsx, admin/src/modules/ImageAltAttribute.jsx, admin/src/modules/KeywordsLinks.jsx, admin/src/modules/LazyLoading.jsx, admin/src/modules/LinkEnhancer.jsx, admin/src/modules/MediaOffloader.jsx, admin/src/modules/MetaTag.jsx, admin/src/modules/Optimize.jsx, admin/src/modules/Redirects.jsx, admin/src/modules/RelatedResources.jsx, admin/src/modules/Screenshot.jsx, admin/src/modules/SearchAndReplace.jsx, admin/src/modules/Serp.jsx, admin/src/modules/static/Schedule.jsx, admin/src/tables/SerpGapTable.jsx
Modules sections in tabs are handled using react router.
Every tab has own route that can be used to access directly wanted module tab, ie. `/LinkEnhancer/settings`
- app should still remember last visited tab
- last visited tab is opened only when direct module url is visited, ie. `/LinkEnhancer`
- if accessed tab route like `/LinkEnhancer/settings`, last visited tab is ignored
- non existing tab routes leads to Overview tab, ie. route like `/LinkEnhancer/xxxxxx` results to default Overview tab.
Close QualityUnit/web-issues#1864
=> [#1864] Add Tab navigation to React Router 

admin/src/components/SettingsOption.jsx, admin/src/components/TableFilterPanel.jsx, admin/src/elements/DateRangeButton.jsx, admin/src/lib/helpers.js
Added conversion fn from wp format to format needed by datepickers.
Datapickers and DateRange picker show date and time in Wordpress format.
Also start of week defined in wp settings should be reflected in pickers.
All datepickers have to use defined wp format and week start day.
Close QualityUnit/web-issues#1834
=> Date and time formats in pickers follow wp settings

admin/src/app/mui_joy/theme.js, admin/src/assets/styles/components/_TableComponent.scss
Table wrapper height reverted back to fill maximum height as before to allow dropdowns overflow out of table.
Close QualityUnit/web-issues#2069
=> fix: dropdowns overflow in table

admin/src/components/TableComponent.jsx, admin/src/tables/SerpQueryDetailTopUrlsTable.jsx
Removed Add Query button from missing table placeholder in SerpQueryDetailTopUrlsTable
Added ability to disable add new table record also via parameter in cases when we cannot reset global table store.
Close QualityUnit/web-issues#2071
=> 2071: allow disable add new table record using parameter

admin/class-urlslab-admin.php
Fixed conflict with ACF plugin.
Added spaces to `urlslab-admin-page` body class to make sure it doesn't connect with other plugins custom classes.
=> fix: admin body class

admin/src/components/generator/manual/StepThird.jsx, admin/src/hooks/useAIGenerator.jsx, admin/src/hooks/useAIGeneratorManualInit.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/queries/usePromptTemplateQuery.jsx, admin/src/tables/GeneratorPromptTemplateTable.jsx, includes/api/class-urlslab-api-prompt-template.php, includes/class-urlslab-activator.php, includes/data/class-urlslab-prompt-template-row.php, includes/defaults/class-urlslab-default-prompt-template.php, urlslab.php
Remove Prompt Template type General. (Now just Using two Prompt Template types Blog Creation and Question Answering)
Using only Blog Creation in the AI Generator Section
Using only Question answering in FAQ
Added Proper Validation
**Checklist**
=> Refactor Prompt Template - redundant removal

admin/src/components/ModuleViewHeaderBottom.jsx
Fixed condition to show `TableActionsMenu` component above tables.
=> fix: missing table actions button

admin/src/hooks/useFilteringSorting.jsx, admin/src/lib/helpers.js, admin/src/tables/SerpCompetitorsTable.jsx
#2138:
Fixed tags in table filter.
As type of input for selected column is recognized from first row cells, if first row doesn't include any tags, this cell was considered as `number` cell.
Conditions that check exactly for key name in conditions hierarchy were moved early before checking for number cell.
`if ( ! isNaN( initialRow?.original[ key ] )` condition for empty tags cell was considered as `number` and returned this type early.
#2133:
added checking for protocol in domains, in Serp Monitoring Competitors > Domains column.
as values can be any strings, if there is no protocol in cell value, added is simply https to make correct links
Close QualityUnit/web-issues#2138
Close QualityUnit/web-issues#2133
=> Bugfixes: #2138 #2133

includes/api/class-urlslab-api-serp-gap.php
This PR will solve the problem, but we don't need the check for empty urls on this place - it should be done with proper validator
https://github.com/QualityUnit/wp-urlslab/pull/1274
Close https://github.com/QualityUnit/web-issues/issues/2181
=> fix: SQL when no urls enetered was incorrect, validator will solve it

admin/src/tables/SerpUrlDetailSimilarUrlsTable.jsx, includes/api/class-urlslab-api-serp-urls.php, includes/cron/class-urlslab-cron-serp-volumes.php
`domain_type` parameter for `similar-urls` and `count` query in SERP Url detail
Close QualityUnit/web-issues#2243
=> fix: domain_type parameter for similar-urls and count query

admin/src/tables/SerpQueriesTable.jsx
Fixed wrong cell value for `country_volume` in SERP Queries table.
Close QualityUnit/web-issues#2254
=> fix: incorrect country_volume table cell

admin/src/components/TableComponent.jsx
Fixed tables width, table foot cell `colSpan` parameter coutns only visible cells.
Close QualityUnit/web-issues#2278
=> fix: table footer width

admin/src/elements/SingleSelectMenu.jsx
Fixed selection of select option which is represented with empty string key like `System Default` below:
```
export const queryScheduleIntervals = {
D: __( 'Daily' ),
W: __( 'Weekly' ),
M: __( 'Monthly' ),
Y: __( 'Yearly' ),
O: __( 'Once' ),
'': __( 'System Default' ),
};
```
Close QualityUnit/web-issues#2332
=> fix: empty string object key in select input

admin/src/components/detailsPanel/QueryDetailPanel.jsx, admin/src/components/detailsPanel/UrlDetailPanel.jsx, admin/src/hooks/useTableStore.jsx, admin/src/tables/SerpQueriesTable.jsx, admin/src/tables/SerpUrlsTable.jsx
Querys and URLs detail tables management.
Detail states cleared on unmount using effect cleanup function, so states are reseted even the user left table other way than click on back button.
Close QualityUnit/web-issues#2362
=> fix: query and url detail tables

admin/src/hooks/useSerpGapCompare.jsx
Prefill words combination option with all values when come from Queries table.
Close QualityUnit/web-issues#2336
=> fix: word combination prefill with all values

admin/src/app/mui_joy/theme.js, admin/src/assets/styles/layouts/ContentGapTableCells.scss, admin/src/components/detailsPanel/GapDetailPanel.jsx, admin/src/components/detailsPanel/gapDetailPanelParts/GapDetailMainSettings.jsx, admin/src/components/detailsPanel/gapDetailPanelParts/GapDetailUrlsSettings.jsx, admin/src/hooks/useSerpGapCompare.jsx, admin/src/hooks/useTablePanels.jsx, admin/src/tables/SerpContentGapTable.jsx
-- changes in Compare Gap options are thrown only after submission using `Update Results` button to avoid sending api requests after every change of some option.
-- options extracted to custom state to avoid changing of `fetchOptions` state that triggers tables rerender, `fetchOptions` updated after click on submit button.
-- Content Gap page loaded from another page (ie. Queries table after click on Content Gap button) runs requests immediately as data are prefilled to show wanted table
-- options in Content Gap recognize which option was changes - so if is needed to run preprocess of urls first and then update table, or if option which is not used by `prepare` query was changed, then only table is updated without `prepare` request.
Maybe improve …
=> Content gap fixes

includes/class-urlslab-admin.php
Hiding AI Content Assistant
Close QualityUnit/web-issues#2031
=> [2031] fix: hiding ai content assistant in header of gutenberg and elementor

admin/src/tables/BacklinksTable.jsx
block editing backlink monitor urls, allow only when adding
Create new Backlink monitor in Link Building > Backlink monitoring.
After adding new record to table, click edit pen icon. Both URLs should be disabled for editing
Close QualityUnit/web-issues#2424
=> [2424] block editing backlink monitor urls, allow only when adding

admin/.eslintrc, admin/src/elements/Editor.jsx
Allowed pasting in TinyMCE editor
Close QualityUnit/web-issues#2509
=> [2509] fix: paste in tinymce editor, eslint fix

admin/src/tables/FaqsTable.jsx, includes/api/class-urlslab-api-faq-urls.php
Following bugs needs to be fixed:
- design of button in FAQs table - we can add any nice icon to suggest url (if no url is assigned)
- if in faqs table the suggest button is pushed, row is not updated when the response is returned from server - reload the data from server pls
- in FAQ detail: if data is loaded from server, input field doesn't update the data from recordset even if internaly it is set correctly ... just UI doesn't render it
Close https://github.com/QualityUnit/web-issues/issues/2534
=> feat: faq - suggest url

admin/src/onboarding/steps/StepApiKey.jsx, admin/src/onboarding/steps/StepChooseKeywords.jsx, admin/src/onboarding/steps/StepModules.jsx
-- onboarding Search query input changed to textarea for multiple queries
-- fixed empty response from `serp-queries/create` api
-- additional keywords selection is still disabled in `Choose search query` step per request in pr https://github.com/QualityUnit/wp-urlslab/pull/1492
Close QualityUnit/web-issues#2550
=> feat: onboarding search query options as textarea

admin/src/app/mui_joy/theme.js, admin/src/app/mui_joy/themes/tooltipTheme.js, admin/src/assets/styles/components/_FloatingPanel.scss, admin/src/assets/styles/components/_ModuleViewHeader.scss, admin/src/assets/styles/components/datepicker/datepicker.scss, admin/src/assets/styles/elements/_IconButton.scss, admin/src/charts/WebVitalsCharts.jsx, admin/src/components/TableFilterPanel.jsx, admin/src/components/TablePanel.jsx, admin/src/components/charts/AreaChart.jsx, admin/src/components/charts/WorldMapChart.jsx, admin/src/elements/AbsoluteCoverBox.jsx, admin/src/elements/RefreshButton.jsx, admin/src/elements/RefreshTableButton.jsx, admin/src/modules/WebVitals.jsx
1. switching between charts and table using button tabs
2. fixed datepicker in filters, filters panel was closed after click on day outside the month currently displayed in datepicker (ie. datepicker shows December month and selected was 1st of January)
Click event target element didn't exist in dom anymore so click event was considered as outside click to close panel. Datepicker component rerenders after selection of day outside displayed month to show the month related to already selected day.
3. fixed usage of datepicker default value in filters panel, issue [#2604](https://github.com/QualityUnit/web-issues/issues/2604)
value of datepicker was dispatched to filters global state only on change event, thus `undefined` value was saved into filters …
=> Web vitals charts changes & bugfixes

admin/src/onboarding/steps/StepChooseCompetitors.jsx, admin/src/tables/SerpTopDomainsTable.jsx
Single select dropdown replaced with buttons options in SERP Domains table Type column.
`Uncategorized` option is ignored and not available, as it should not be selected by user.
Close QualityUnit/web-issues#2551
=> feat: serp domains table type column with buttons

admin/src/elements/ColumnsMenu.jsx
Fixed toggling of `visible` class after closing columns menu using some action button Hide All, Select All etc....
Close QualityUnit/web-issues#2679
=> fix: columns menu fixed closing

admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/tables/MediaFilesTable.jsx
Disabled filtering and sorting for `Offloaded URL` in Media table.
Close QualityUnit/web-issues#2676
=> fix: disabled filtering and sorting for Offloaded URL

admin/src/components/ChangesPanel/ChangesPanel.jsx, admin/src/elements/TableSelectCheckbox.jsx, admin/src/hooks/useChangeRow.jsx
Fixed selection of rows in changes panel table. 
When two rows were selected, it was not possible to select any other previous checkbox because the first checkbox was immediately deselected when three rows were selected.
- removing of first selected checkbox is done directly before the state of selected rows is saved => do not need to update state with three checkboxes selected and immediately update state again with removed first checkbox
- `selectRows()` method accept maxRows parameter to limit selected rows before they are saved into state
Close QualityUnit/web-issues#2718
=> fix: fixed selection of rows in changes panel to show diff

admin/src/components/EditRowPanel.jsx, admin/src/elements/MultiSelectMenu.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/hooks/useTablePanels.jsx, admin/src/modules/static/TagsLabels.jsx
- improved old code of Tags table,
- implemented optional success callbacks after edit, delete and insert actions on table row - used to refresh tags throught whole app after change of tag in tags table,
- fixed `undefined` text displayed in modules selection inside tag edit/insert panel,
- fixed throwing new api requests after every closing of modules selection, even the chosen modules were not changed,
- implemented controlled option for `MultiSelectMenu` component to properly update value of changed selected modules in table row,
- live update for `MultiSelectMenu`, fix for tag edit row panel when selected modules in panel for edited or new tag were not saved until select dropdown was not closed before submitting edit row panel using save/edit …
=> I2729 Tags table improvements and fixes

admin/src/tables/MediaFilesTable.jsx, includes/data/class-urlslab-data-file.php
Fixes not defined download_url column type in Media Files table > filter not available
Close QualityUnit/web-issues#2823
=> [2823] fix: download_url column type not defined, filter not working

includes/widget/class-urlslab-widget-cache.php
Close https://github.com/QualityUnit/web-issues/issues/2927
=> fix: php warning array to string conversion

admin/src/App.jsx, admin/src/app/router.jsx, admin/src/components/ModuleViewHeader.jsx, admin/src/components/TableBody.jsx, admin/src/components/TableComponent.jsx, admin/src/components/TableHead.jsx, admin/src/components/TableRow.jsx, admin/src/elements/ColumnsMenu.jsx, admin/src/elements/DescriptionBox.jsx, admin/src/hooks/useModuleSectionRoute.jsx, admin/src/hooks/useOnloadRedirect.jsx, admin/src/hooks/useUserLocalData.jsx
User data from internal browser database are loaded just once on app load and saved into global store.
benefits:
-- no need to repeatedly call async reading from internal db while user working with app,
-- removed unnecessary rerenders of components which read from internal db because of async read,
-- removed tricky handling of component visibility using css opacity until data from internal db are read to show finally loaded component
-- user data are read instantly from global store
Data are saved into internal db beside the action which save data into store.
Close QualityUnit/urlslab-issues#2
=> feat: user local data handled by global store

assets/scss/urlslab_youtube_loader_decorated.scss, includes/widget/class-urlslab-widget-lazy-loading.php
Fixes CLS issue with later appending CSS for youtube decorated window
Close [QualityUnit/urlslab-issues#[ISSUE_NUMBER]](https://github.com/QualityUnit/web-issues/issues/3232)
=> [3232] fix: prepends youtube css before element for cls

admin/src/tables/YouTubeCacheTable.jsx
Fixed error after click to button "Show URLs where used"
- Go to urlslab plugin "Lazy Loading"->"YouTube Videos" and click
"Show URLs where used" button and check console to error and should
to show popup window
**Checklist**
Close QualityUnit/urlslab-issues#1546
=> [1546] - fix: fixed error after click to button "Show URLs where used"
