QualityUnit/wp-urlslab

.github/workflows/release.yml, urlslab.php
Adjusted build script for urlslab plugin
removed yarn install in plugin
**Checklist**
Close QualityUnit/web-issues/issues/585
=> Adjusted build script git worflow

admin/partials/tables/class-urlslab-screenshot-table.php, includes/class-urlslab-activator.php, includes/class-urlslab-url.php, includes/cron/class-urlslab-screenshot-cron.php, includes/helpers/class-urlslab-status.php, includes/helpers/urlslab-helpers.php, includes/services/api/class-urlslab-api.php, includes/services/api/class-urlslab-screenshot-api.php, includes/services/class-urlslab-url-data-fetcher.php, includes/widgets/class-urlslab-screenshot-widget.php, urlslab.php
There are repeating urls requested in multiple requests. The changes garantuee the following: 
- The status date of the each url is updated before the request is made. that ensures that the same urls will be requested again after all other requests and it will move to the end of the list.
- Adjusted the categorization of Blocked and Broken URLs correctly so that there are no confusions in there.
**Checklist**
Close QualityUnit/web-issues/issues/590
=> bug fix for cron job requesting repeating urls

includes/services/class-urlslab-url-data.php
changed screenshot serving paths
**Checklist**
Close QualityUnit/web-issues/issues/607
=> screenshot path changed

commitlint.config.js, includes/class-urlslab-activator.php, includes/services/class-urlslab-url-keyword-data.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-related-resources-widget.php, webpack.config.js
Generate sample data for related resources and keywords
**Checklist**
Close QualityUnit/web-issues/issues/603
=> Generate sample data for related resources and keywords

admin/partials/tables/class-urlslab-keyword-link-table.php, commitlint.config.js, includes/class-urlslab-activator.php, includes/services/class-urlslab-url-keyword-data.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-screenshot-widget.php, urlslab.php, webpack.config.js
added primary key for row
**Checklist**
Close QualityUnit/web-issues/issues/604
=> feat: add kwMd5 column as primary key

includes/widgets/class-urlslab-keywords-links.php
number of keywords used in iterations reduced just to those, which are in the page content
**Checklist**
Close QualityUnit/web-issues/issues/605
=> optimize speed of replacements with big dataset of keywords

includes/services/api/class-urlslab-screenshot-api.php, includes/services/class-urlslab-url-data-fetcher.php
**Checklist**
Close QualityUnit/web-issues/issues/627
=> Bug fix for illegal parsing of error response from urlslab

admin/includes/menu/class-urlslab-content-widgets-page.php, admin/includes/menu/class-urlslab-page-factory.php, admin/includes/menu/class-urlslab-ui-elements-page.php, admin/partials/urlslab-admin-content-widgets.php, admin/partials/urlslab-admin-screenshot.php, admin/partials/urlslab-admin-ui-elements.php, includes/class-urlslab.php
Added menu page to Urlslab plugin for UI Elements
**Checklist**
Close QualityUnit/web-issues/issues/640
=> restructuring ui elements page

includes/class-urlslab.php, includes/cron/class-urlslab-offload-cron.php, includes/driver/class-urlslab-driver-db.php, includes/driver/class-urlslab-driver-file.php, includes/driver/class-urlslab-driver-s3.php, includes/driver/class-urlslab-driver.php, includes/services/class-urlslab-file-data.php, includes/widgets/class-urlslab-media-offloader-widget.php
option to transfer content of file between drivers on the background
**Checklist**
Close QualityUnit/web-issues/issues/646
=> transfer of file content between drivers

includes/widgets/class-urlslab-media-offloader-widget.php
srcset attribute can contain multiple values separated by comma
**Checklist**
Close QualityUnit/web-issues/issues/648
=> feat: process srcset attribute correctly

includes/driver/class-urlslab-driver-s3.php, includes/services/class-urlslab-url-data-fetcher.php
bug fix for offloader plugin
**Checklist**
Close QualityUnit/web-issues/issues/654
=> offloader bug fix

admin/includes/menu/class-urlslab-offloader-page.php, includes/driver/class-urlslab-driver-s3.php, includes/services/class-urlslab-url-data-fetcher.php, includes/widgets/class-urlslab-media-offloader-widget.php, includes/widgets/class-urlslab-meta-tag.php
Offloader Bug fix and new settings
**Checklist**
Close QualityUnit/web-issues/issues/654
=> Bug fix for Offloader

includes/class-urlslab-activator.php, includes/widgets/class-urlslab-link-enhancer.php, urlslab.php
urls map table will contain relations between urls found in page
**Checklist**
Close QualityUnit/web-issues/issues/660
=> feat: collect data about url relations

admin/includes/menu/class-urlslab-admin-page.php, admin/includes/menu/class-urlslab-header-widgets-page.php, admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/menu/class-urlslab-link-management-subpage.php, admin/includes/menu/class-urlslab-offloader-page.php, admin/includes/menu/class-urlslab-related-resource-subpage.php, admin/includes/tables/class-urlslab-screenshot-table.php, admin/js/urlslab-admin.js, admin/partials/urlslab-admin-related-resource-subpage.php, includes/class-urlslab-url.php, includes/services/class-urlslab-url-keyword-data.php, includes/widgets/class-urlslab-meta-tag.php
added anchor and validation for forms
**Checklist**
Close QualityUnit/web-issues/issues/683
Close QualityUnit/web-issues/issues/682
=> Added validation and anchor for better ux and ui

admin/partials/urlslab-admin-header.php
bug fix for linking to integration page
**Checklist**
Close QualityUnit/web-issues/issues/688
=> Bug fix for the api key notice

admin/includes/menu/class-urlslab-offloader-page.php, includes/class-urlslab-activator.php, includes/class-urlslab.php, includes/cron/class-urlslab-convert-avif-images-cron.php, includes/cron/class-urlslab-convert-images-cron.php, includes/cron/class-urlslab-convert-webp-images-cron.php, includes/services/class-urlslab-file-data.php, includes/widgets/class-urlslab-media-offloader-widget.php
separate crons for each alternative image format
**Checklist**
Close QualityUnit/web-issues/issues/703
=> fix: split image processing crons

.github/workflows/release.yml, urlslab.php
- fix release script
**Checklist**
=> chore: fix release script

includes/class-urlslab-activator.php, urlslab.php
migration for LA staging
**Checklist**
=> table schema migration fix

admin/includes/tables/class-urlslab-offloader-table.php, includes/cron/class-urlslab-convert-avif-images-cron.php, includes/cron/class-urlslab-convert-webp-images-cron.php
added option to filter files by webp and avif alternative availability
**Checklist**
Close QualityUnit/web-issues/issues/707
=> feat: files filter

admin/includes/menu/class-urlslab-offloader-page.php, composer.json, composer.lock, includes/class-urlslab.php, includes/cron/class-urlslab-convert-avif-images-cron.php, includes/cron/class-urlslab-convert-images-cron.php, includes/cron/class-urlslab-convert-webp-images-cron.php, includes/widgets/class-urlslab-link-enhancer.php
add support for imagick
**Checklist**
Close QualityUnit/web-issues/issues/705
=> add support for imagick

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, includes/widgets/class-urlslab-keywords-links.php
**Checklist**
Close QualityUnit/web-issues/issues/704
=> option to define minimum paragraph size for keywords replacement

composer.json, composer.lock, includes/cron/class-urlslab-convert-images-cron.php, urlslab.php
imagemagic can not be required library ... it is just nice to have lib
**Checklist**
Close QualityUnit/web-issues/issues/710
=> fix paletter images

admin/css/urlslab-admin.css, admin/js/urlslab-admin.js, admin/templates/page/urlslab-admin-header-widgets.php, admin/templates/page/urlslab-admin-image-seo-widgets.php, admin/templates/page/urlslab-admin-keyword-linking-subpage.php, admin/templates/page/urlslab-admin-link-management.php, admin/templates/page/urlslab-admin-media-offloader.php, admin/templates/page/urlslab-admin-related-resource-subpage.php, admin/templates/page/urlslab-admin-screenshot.php
Dialog bug fix for admin
**Checklist**
Close QualityUnit/web-issues/issues/713
=> Bug fix for urlslab dialog

admin/includes/tables/class-urlslab-offloader-table.php
- added generated url to the table
- fixed bug with query params
**Checklist**
Close QualityUnit/web-issues/issues/715
=> offloader bug fix for urls with query params

includes/class-urlslab-activator.php, includes/driver/class-urlslab-driver-db.php, includes/driver/class-urlslab-driver-file.php, includes/driver/class-urlslab-driver-s3.php, includes/driver/class-urlslab-driver.php, includes/services/class-urlslab-file-data.php, urlslab.php
- filename will not contain query parameters
- drop all data and create empty tables
**Checklist**
Close QualityUnit/web-issues/issues/716
=> queary params in filename

includes/cron/class-urlslab-screenshot-cron.php, includes/driver/class-urlslab-driver-file.php
**Checklist**
Close QualityUnit/web-issues/issues/720
=> fix warning and notices

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/menu/class-urlslab-link-building-page.php, admin/js/urlslab-admin.js
fixed bugs in keyword validation and added shceduling
**Checklist**
Close QualityUnit/web-issues/issues/719
=> Fixed bugs in keywords widget

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/menu/class-urlslab-offloader-page.php, admin/templates/settings/class-urlslab-setting-input.php, includes/class-urlslab-activator.php, includes/class-urlslab.php, includes/cron/class-urlslab-youtube-cron.php, includes/services/class-urlslab-youtube-data.php, includes/widgets/class-urlslab-media-offloader-widget.php, public/js/urlslab-lazyload.js, urlslab.php
css not ready yet, youtube offloading
**Checklist**
Close QualityUnit/web-issues/issues/689
=> youtube offloading

admin/includes/menu/class-urlslab-keyword-linking-subpage.php
Fix for keyword scheduling
**Checklist**
Close QualityUnit/web-issues/issues/723
=> Keyword scheduling fix

admin/js/urlslab-admin.js, includes/class-urlslab.php, includes/widgets/class-urlslab-keywords-links.php
bug fix for keywords
**Checklist**
Close QualityUnit/web-issues/issues/738
=> fixed bug with keywords prio and logic

includes/class-urlslab-activator.php, includes/class-urlslab-deactivator.php, includes/widgets/class-urlslab-media-offloader-widget.php
Youtube placeholder fixes
**Checklist**
Close QualityUnit/web-issues/issues/739
=> fix: youtube schema and placeholder

includes/widgets/class-urlslab-media-offloader-widget.php
[Describe what was changed in the Pull Request](fix: elementor video placeholder position)
**Checklist**
Close QualityUnit/web-issues/issues/741
=> fix: elementor video placeholder position

admin/css/urlslab-admin.css, admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/menu/class-urlslab-related-resource-subpage.php, admin/js/urlslab-admin.js
fixed the bugs in UI dialog
**Checklist**
Close QualityUnit/web-issues/issues/745
=> UI bug fix for dialogs

includes/widgets/class-urlslab-media-offloader-widget.php
offload also images from style linked through url()
**Checklist**
Close QualityUnit/web-issues/issues/742
=> fix: offload also images in style

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/menu/class-urlslab-related-resource-subpage.php
Fixed the Bug with sample data scheduling
**Checklist**
Close QualityUnit/web-issues/issues/744
=> Bug fix for sample data scheduling

admin/includes/menu/class-urlslab-offloader-page.php, includes/driver/class-urlslab-driver-db.php, includes/driver/class-urlslab-driver-file.php, includes/driver/class-urlslab-driver-s3.php, includes/driver/class-urlslab-driver.php, includes/widgets/class-urlslab-media-offloader-widget.php
delete of offloaded content from driver
**Checklist**
Close QualityUnit/web-issues/issues/747
=> feat: option to delete file from offloaded storage after transfer

urlslab.php
version increased to 1.11.1
**Checklist**
Close QualityUnit/web-issues/issues/[ISSUE_NUMBER]
=> version increase

includes/widgets/class-urlslab-image-alt-text.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-link-enhancer.php, includes/widgets/class-urlslab-media-offloader-widget.php, includes/widgets/class-urlslab-widget.php
**Checklist**
Close QualityUnit/web-issues/issues/749
=> feat: add urlslab-skip class checking

package.json, urlslab.php, yarn.lock
- bump plugin version 1.12
- fix css loader issue
**Checklist**
=> chore: bump plugin version 1.12

admin/includes/menu/class-urlslab-related-resource-subpage.php, admin/includes/tables/class-urlslab-related-resources-widget-table.php, admin/includes/tables/class-urlslab-screenshot-table.php, includes/class-urlslab-activator.php, includes/class-urlslab-url.php, includes/services/class-urlslab-url-data-fetcher.php, includes/widgets/class-urlslab-link-enhancer.php, urlslab.php
Bugfix for collation of joining tables. The IDs are all changed to integer instead of hex to prevent collation bugs
**Checklist**
Close QualityUnit/web-issues/issues/740
=> Changed all IDs to bigint

includes/services/class-urlslab-url-data-fetcher.php
minor bug fix for related resources
**Checklist**
Close QualityUnit/web-issues/issues/757
=> bugfix for undefined index

composer.lock, includes/widgets/class-urlslab-media-offloader-widget.php, package.json, urlslab.php, yarn.lock
Disabled lazy loading optimization for unknown lazy loading attributes
**Checklist**
Close QualityUnit/web-issues/issues/755
=> Disabled optimization of images with unknown lazy loading

includes/widgets/class-urlslab-media-offloader-widget.php, includes/widgets/class-urlslab-widget.php, urlslab.php
=> bug fix for media offloader

admin/css/urlslab-admin.css, admin/includes/menu/class-urlslab-dashboard-page.php, admin/templates/partials/urlslab-admin-activation-card-header.php, urlslab.php
Changed HTTP Method for activating/deactivating widget
**Checklist**
Close QualityUnit/web-issues/issues/766
=> bug fix for activating/deactivating widgets

includes/services/class-urlslab-url-data-fetcher.php, urlslab.php
Optimized DB Query for Link Enhancer widget
**Checklist**
Close QualityUnit/web-issues/issues/768
=> Optimization of DB query for link enhancer

includes/cron/class-urlslab-offload-enqueue-files-cron.php, includes/widgets/class-urlslab-media-offloader-widget.php, urlslab.php
offloader bugfix
**Checklist**
Close QualityUnit/wp-urlslab#228
=> Removed header params for offloader bugfix

admin/includes/menu/class-urlslab-offloader-page.php, includes/cron/class-urlslab-offload-enqueue-files-cron.php, includes/driver/class-urlslab-driver-db.php, includes/widgets/class-urlslab-media-offloader-widget.php
add option to define expire time
fix offloading to db
**Checklist**
=> fix: offloading file to db, expire time for media files

includes/widgets/class-urlslab-media-offloader-widget.php, urlslab.php
changed the headers to octet-stream
**Checklist**
=> changed headers

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, includes/widgets/class-urlslab-keywords-links.php
more detailed restrictions for adding links to page
**Checklist**
Close QualityUnit/web-issues/issues/776
=> feat: more detailed restrictions for adding links to page

includes/class-urlslab-activator.php, includes/widgets/class-urlslab-link-enhancer.php, urlslab.php
**Checklist**
Close [QualityUnit/wp-urlslab#[ISSUE_NUMBER]](https://github.com/QualityUnit/web-issues/issues/785)
=> fix: optimize speed of url tracking

includes/driver/class-urlslab-driver-db.php, includes/driver/class-urlslab-driver.php, includes/widgets/class-urlslab-media-offloader-widget.php, urlslab.php
changed the download from wordpress to php native download of resources
**Checklist**
=> bug fix for corrupted assets

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/tables/class-urlslab-keyword-link-table.php, includes/class-urlslab-activator.php, includes/helpers/urlslab-helpers.php, includes/services/class-urlslab-url-keyword-data.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-link-enhancer.php, urlslab.php
**Checklist**
Close QualityUnit/web-issues/issues/789
=> feat: keywords tracking

includes/cron/class-urlslab-youtube-cron.php
fixed path to constant
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/793
=> fix: lazy loading refactoring fixed

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/menu/class-urlslab-related-resource-subpage.php
insert data with one sql command only
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/748
=> fix: improved speed of import

includes/widgets/class-urlslab-media-offloader-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/794
=> fix: php notice

includes/driver/class-urlslab-driver-db.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/795
=> fix: wp_tempnam function missing

includes/cron/class-urlslab-offload-enqueue-files-cron.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/798
=> fix: fix looping error because of sql bug

includes/driver/class-urlslab-driver-db.php, urlslab.php
test if this will fix problem between logged in and not logged in user for downloading of files
**Checklist**
=> fix: try to avoid using admin functions

admin/includes/menu/class-urlslab-lazyload-subpage.php, admin/includes/menu/class-urlslab-media-offloader-subpage.php, includes/driver/class-urlslab-driver.php, includes/widgets/class-urlslab-media-offloader-widget.php, urlslab.php
generate missing resized image from original file
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/813
=> feat: generate resized images if urls is missing

admin/includes/menu/class-urlslab-media-offloader-subpage.php, includes/widgets/class-urlslab-media-offloader-widget.php
transferring bugfix for changing the drivers
**Checklist**
Close QualityUnit/web-issues#796
=> transferring bug fix

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/tables/class-urlslab-keyword-link-table.php, admin/includes/tables/class-urlslab-screenshot-table.php, includes/class-urlslab-url.php
changed location of actions in columns.
fixed bug with queries
**Checklist**
Close QualityUnit/web-issues#821
=> bug fix for wp tables

includes/cron/class-urlslab-convert-images-cron.php, includes/cron/class-urlslab-convert-webp-images-cron.php, includes/widgets/class-urlslab-media-offloader-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/823
=> fix: convert gif images

admin/includes/menu/class-urlslab-lazyload-subpage.php, admin/includes/menu/class-urlslab-media-offloader-subpage.php, composer.json, composer.lock, includes/cron/class-urlslab-youtube-cron.php, includes/driver/class-urlslab-driver-s3.php, includes/widgets/class-urlslab-lazy-loading.php
Settings are loaded from environement variables (youtube key, aws secret and aws key)
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/824
=> fix: load settings from environemnt variables

includes/class-urlslab-activator.php, includes/cron/class-urlslab-convert-avif-images-cron.php, includes/cron/class-urlslab-convert-webp-images-cron.php, includes/driver/class-urlslab-driver.php, includes/services/class-urlslab-file-data.php, includes/widgets/class-urlslab-media-offloader-widget.php, urlslab.php
- fixed generating of missing sizes of jpeg images
- fixed url of source image computation
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/826
=> fix: offloading and resizing jpg images

admin/class-urlslab-admin.php, admin/css/urlslab-admin.css, admin/includes/menu/class-urlslab-media-page.php, admin/includes/tables/class-urlslab-keyword-link-table.php, admin/includes/tables/class-urlslab-offloader-table.php, admin/includes/tables/class-urlslab-screenshot-table.php, admin/js/urlslab-admin.js, admin/templates/page/urlslab-admin-media.php, includes/services/class-urlslab-file-data.php, includes/widgets/class-urlslab-media-offloader-widget.php
Added image usage count in offloading table
**Checklist**
Close QualityUnit/web-issues#831]
=> Added image usage count in offloading table

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/tables/class-urlslab-keyword-link-table.php, admin/includes/tables/class-urlslab-screenshot-table.php, includes/class-urlslab-url.php, includes/services/class-urlslab-url-keyword-data.php
multiple bugfixes in UI
**Checklist**
Close QualityUnit/web-issues#832
=> bugfix in UI

urlslab.php
=> version release v1.33

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/menu/class-urlslab-related-resource-subpage.php, admin/includes/tables/class-urlslab-related-resources-widget-table.php, admin/js/urlslab-admin.js, includes/class-urlslab-activator.php, includes/services/class-urlslab-url-data-fetcher.php, urlslab.php
added new column in related resources used for sorting based on the AI algorithm 
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/847
=> feat: order position in related resources

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/tables/class-urlslab-keyword-link-table.php, admin/js/urlslab-admin.js, admin/templates/page/urlslab-admin-link-building.php, includes/widgets/class-urlslab-media-offloader-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/843
=> feat: hiding images and edit link next to url

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/tables/class-urlslab-keyword-link-table.php, includes/helpers/urlslab-helpers.php, includes/services/class-urlslab-url-data.php
Refactoring for url_to_post
**Checklist**
=> Refactoring for url_to_post

.github/workflows/release-nightly.yml
new release script
**Checklist**
=> chore: new release script

includes/helpers/urlslab-helpers.php, includes/widgets/class-urlslab-media-offloader-widget.php, urlslab.php, yarn.lock
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/852
=> fix: tracking of wepb images

composer.lock, urlslab.php
=> feat: new version 1.36

includes/widgets/class-urlslab-image-alt-text.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/856
=> fix alt text computation for images

admin/includes/tables/class-urlslab-keyword-link-table.php
Bugfix for keyword table
**Checklist**
=> keyword table bugfix

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/menu/class-urlslab-urls-page.php, admin/includes/tables/class-urlslab-screenshot-table.php
Changed join types where needed
**Checklist**
=> Fixes in SQL

includes/widgets/class-urlslab-image-alt-text.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-link-enhancer.php, includes/widgets/class-urlslab-media-offloader-widget.php, includes/widgets/class-urlslab-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/866
=> feat: add option to skip processing per widget type

composer.lock, includes/class-urlslab-available-widgets.php, includes/helpers/urlslab-helpers.php, includes/services/class-urlslab-url-data-fetcher.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-link-enhancer.php, includes/widgets/class-urlslab-media-offloader-widget.php, includes/widgets/class-urlslab-meta-tag.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/864
=> fix: add current page to urls when tracking page links

includes/widgets/class-urlslab-keywords-links.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/871
=> fix: kw replacements were not working correctly due to missing init

includes/widgets/class-urlslab-media-offloader-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/875
=> fix: sql error and php notice

includes/class-urlslab-url.php, includes/services/class-urlslab-url-data-fetcher.php, includes/services/class-urlslab-url-data.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-link-enhancer.php, includes/widgets/class-urlslab-meta-tag.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-screenshot-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/877
=> fix: performance issues

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/tables/class-urlslab-keyword-link-table.php, admin/includes/tables/class-urlslab-related-resources-widget-table.php, admin/includes/tables/class-urlslab-screenshot-table.php, admin/js/urlslab-admin.js, includes/class-urlslab-activator.php, includes/class-urlslab-available-widgets.php, includes/services/class-urlslab-url-data-fetcher.php, includes/services/class-urlslab-url-keyword-data.php, includes/widgets/class-urlslab-image-alt-text.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-link-enhancer.php, includes/widgets/class-urlslab-media-offloader-widget.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-widget.php, urlslab.php
Automatic import of keywords from page
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/886
=> Automatic import of keywords from page

composer.lock, includes/driver/class-urlslab-driver.php
stop processing smaller image if original file doesn't exist 
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/888
=> fix: if new image does not exist, stop processing

includes/class-urlslab-url.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-related-resources-widget.php
urls without protocol were taken as local urls even if they were external
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/899
=> fix: recognition of external urls

includes/widgets/class-urlslab-image-alt-text.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-link-enhancer.php, includes/widgets/class-urlslab-media-offloader-widget.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/903
=> fix: rename urlslab-skip to urlslab-skip-all

package.json
Changed webpack environment for Build script to production instead of development to minify JS & CSS files.
**Checklist**
Close QualityUnit/wp-urlslab#902
=> [902] fix: changed build script to production environment

admin/includes/tables/class-urlslab-offloader-table.php, includes/services/class-urlslab-url-data.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-media-offloader-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/909
=> fix: performance improvement

package.json
=> fix: changed production script too to just webpack --dev=production

includes/services/class-urlslab-youtube-data.php, includes/widgets/class-urlslab-lazy-loading.php, urlslab.php
=> fix: youtube video had no thumbnail image url

includes/services/class-urlslab-url-data.php, includes/widgets/class-urlslab-lazy-loading.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/911
=> fix: php 8.1 compatibility - fix deprecated

includes/widgets/class-urlslab-lazy-loading.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/921
=> fix: correctly skip img and iframes if parent elements contain skip class

admin/includes/menu/class-urlslab-lazyload-subpage.php, includes/widgets/class-urlslab-lazy-loading.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/923
=> feat: added option to disable default wordpress lazy loading for images

admin/includes/menu/class-urlslab-media-offloader-subpage.php, assets/js/urlslab-lazyload.js, includes/widgets/class-urlslab-media-offloader-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/931
=> 931 - min-width for images

includes/driver/class-urlslab-driver.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/954
=> fix: path can not be empty

includes/cron/class-urlslab-convert-avif-images-cron.php, includes/cron/class-urlslab-convert-webp-images-cron.php, includes/driver/class-urlslab-driver.php, includes/services/class-urlslab-url-data-fetcher.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/955
=> fix: correct return value types

includes/widgets/class-urlslab-related-resources-widget.php, urlslab.php
=> add debug message to related resources

includes/cron/class-urlslab-update-urls-cron.php, includes/services/class-urlslab-url-row.php, urlslab.php
mark 404 urls as broken
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/979
=> mark 404 urls as broken

includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-media-offloader-widget.php
don't process images, where is no url, but data:image value
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/961
=> fix: skip processing of images with data in src

includes/cron/class-urlslab-update-urls-cron.php, includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-media-offloader-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/963
=> error during uploading file to db driver

includes/widgets/class-urlslab-link-enhancer.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/981
=> fix: php warning Undefined property

admin/js/urlslab-admin.js, admin/templates/page/urlslab-admin-dashboard.php, includes/class-urlslab.php, includes/cron/class-urlslab-update-urls-cron.php, includes/widgets/class-urlslab-link-enhancer.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1010
=> update datetime from which will start cron scanning of all urls again

includes/class-urlslab-url.php, includes/class-urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1015
=> skip unsupported links

urlslab.php
=> version bump 1.43.3

includes/class-urlslab-url.php, includes/services/class-urlslab-url-data-fetcher.php
=> fix: skip handling whatsapp links

includes/class-urlslab-url.php, urlslab.php
=> version 1.43.4

includes/widgets/class-urlslab-screenshot-widget.php, urlslab.php
=> fix: catch invalid url exception

includes/widgets/class-urlslab-keywords-links.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1021
=> fix: unterminated entity reference

admin/includes/tables/class-urlslab-screenshot-table.php, admin/templates/page/urlslab-admin-dashboard.php, includes/services/class-urlslab-url-data-fetcher.php, urlslab.php
Bug fix for scheduling
**Checklist**
=> Scheduling bug fix in date query

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/tables/class-urlslab-keyword-link-table.php, urlslab.php
Added url filter in keywords table
**Checklist**
=> Added url filter in keywords table

admin/includes/tables/class-urlslab-offloader-table.php
bulk delete for media files
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1031
=> feat: add option to bulk delete media files

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, includes/widgets/class-urlslab-keywords-links.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1024
=> enhance h tags with id to allow addressing all paragraphs

urlslab.php
version bump to 1.43.10
**Checklist**
=> version bump to 1.43.10

admin/class-urlslab-admin.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1048
=> fix: fatal error - action must be of type string, array given

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/tables/class-urlslab-keyword-link-table.php, includes/widgets/class-urlslab-keywords-links.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1039
=> feat: setting to choose type of keywords replaced to links in content

admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/tables/class-urlslab-keyword-link-table.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1051
=> feat: add filters to keywords table

admin/includes/api/class-urlslab-api-modules.php, includes/class-urlslab-api-router.php, includes/class-urlslab.php, includes/widgets/class-urlslab-image-alt-text.php, includes/widgets/class-urlslab-link-enhancer.php, includes/widgets/class-urlslab-meta-tag.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-screenshot-widget.php, includes/widgets/class-urlslab-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1055
=> feat: first test of API call

includes/widgets/class-urlslab-lazy-loading.php, public/class-urlslab-public.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1067
=> feat: load youtube css just when needed

includes/class-urlslab-activator.php, includes/class-urlslab-available-widgets.php, includes/class-urlslab.php, includes/cron/class-urlslab-download-css-cron.php, includes/services/class-urlslab-css-cache-row.php, includes/services/class-urlslab-data.php, includes/widgets/class-urlslab-css-optimizer.php, includes/widgets/class-urlslab-lazy-loading.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1075
=> feat: render-blocking CSS into Inline CSS

includes/class-urlslab.php, includes/widgets/class-urlslab-css-optimizer.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1081
=> fix: fixed loading of header content

includes/class-urlslab.php, urlslab.php
=> Skip header error

includes/class-urlslab.php
=> fix: skip processing if no hook active

admin/includes/api/class-urlslab-api-css-cache.php, admin/includes/api/class-urlslab-api-youtube-cache.php, includes/class-urlslab-api-router.php, includes/cron/class-urlslab-download-css-cron.php, includes/cron/class-urlslab-youtube-cron.php, includes/services/class-urlslab-youtube-data.php, includes/widgets/class-urlslab-css-optimizer.php, includes/widgets/class-urlslab-lazy-loading.php
=> Api css cache

admin/includes/api/class-urlslab-api-settings.php, includes/widgets/class-urlslab-widget.php
=> True false handling

admin/includes/api/class-urlslab-api-css-cache.php, admin/includes/api/class-urlslab-api-youtube-cache.php
=> feat: api - update status for youtube cache and css cache

includes/widgets/class-urlslab-keywords-links.php
=> fix: settings definition bug

admin/class-urlslab-admin.php, admin/includes/api/class-urlslab-api-cron.php, admin/includes/menu/class-urlslab-admin-page.php, admin/includes/menu/class-urlslab-dashboard-page.php, admin/includes/menu/class-urlslab-header-widgets-page.php, admin/includes/menu/class-urlslab-image-seo-widgets-page.php, admin/includes/menu/class-urlslab-link-building-page.php, admin/includes/menu/class-urlslab-media-page.php, admin/includes/menu/class-urlslab-page-factory.php, admin/includes/menu/class-urlslab-ui-elements-page.php, admin/includes/menu/class-urlslab-urls-page.php, includes/class-urlslab-api-router.php, includes/class-urlslab-loader.php, includes/class-urlslab.php, includes/cron/class-urlslab-cron-manager.php, includes/cron/class-urlslab-cron.php, includes/cron/class-urlslab-download-css-cron.php, includes/widgets/class-urlslab-css-optimizer.php, includes/widgets/class-urlslab-general.php, includes/widgets/class-urlslab-image-alt-text.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-link-enhancer.php, includes/widgets/class-urlslab-media-offloader-widget.php, includes/widgets/class-urlslab-meta-tag.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-screenshot-widget.php, includes/widgets/class-urlslab-widget.php
=> feat: cron api

.github/workflows/build-test.yml, .github/workflows/eslint.yml, .github/workflows/stylelint.yml, admin/includes/api/class-urlslab-api-css-cache.php, admin/includes/api/class-urlslab-api-keywords.php, admin/includes/api/class-urlslab-api-youtube-cache.php, admin/includes/menu/class-urlslab-keyword-linking-subpage.php, admin/includes/tables/class-urlslab-keyword-link-table.php, includes/class-urlslab-api-router.php, includes/services/class-urlslab-url-keyword-data.php, includes/widgets/class-urlslab-keywords-links.php
=> feat: keywords api (not ready update)

admin/includes/api/class-urlslab-api-base.php, admin/includes/api/class-urlslab-api-cron.php, admin/includes/api/class-urlslab-api-css-cache.php, admin/includes/api/class-urlslab-api-keywords.php, admin/includes/api/class-urlslab-api-modules.php, admin/includes/api/class-urlslab-api-settings.php, admin/includes/api/class-urlslab-api-table.php, admin/includes/api/class-urlslab-api-youtube-cache.php, includes/class-urlslab-api-router.php, includes/class-urlslab.php, includes/services/class-urlslab-css-cache-row.php, includes/services/class-urlslab-keyword-data.php, includes/services/class-urlslab-youtube-data.php
=> chore: api refactoring

admin/templates/page/urlslab-admin-keyword-linking-subpage.php, includes/class-urlslab-url.php, includes/widgets/class-urlslab-keywords-links.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1088
=> replace page_id links with permalink

admin/includes/api/class-urlslab-api-css-cache.php, admin/includes/api/class-urlslab-api-keywords.php, admin/includes/api/class-urlslab-api-table.php, includes/class-urlslab.php, includes/services/class-urlslab-keyword-map-data.php
=> feat: keywords api enhancement

includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-link-enhancer.php
=> feat: delete page_id link if permalink is not found

admin/includes/api/class-urlslab-api-css-cache.php, admin/includes/api/class-urlslab-api-keywords.php, admin/includes/api/class-urlslab-api-table.php, admin/includes/api/class-urlslab-api-youtube-cache.php
=> feat: delete all api call

admin/includes/api/class-urlslab-api-keywords.php, admin/includes/api/class-urlslab-api-table.php, admin/includes/api/class-urlslab-api-url-relations.php, includes/services/class-urlslab-data.php, includes/services/class-urlslab-keyword-data.php, includes/services/class-urlslab-url-relation-row.php
=> Import api

includes/widgets/class-urlslab-lazy-loading.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1091
=> feat: use fixed empty image to decrease CLS time with lazy loaded images

includes/widgets/class-urlslab-lazy-loading.php, urlslab.php
=> chore: try svg image on place of png for lazyloading

includes/widgets/class-urlslab-link-enhancer.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1094
=> feat: enhance all links with fragment to link keywords

includes/widgets/class-urlslab-link-enhancer.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1096
=> feat: custom class to skip processing of fragments in links

includes/widgets/class-urlslab-widget.php
**Checklist**
Close https://github.com/QualityUnit/wp-urlslab/issues/432
=> Api settings - vave multicheckbox values

admin/includes/api/class-urlslab-api-content-cache.php, assets/js/urlslab-lazyload.js, includes/class-urlslab-activator.php, includes/class-urlslab-api-router.php, includes/services/class-urlslab-content-cache-row.php, includes/services/class-urlslab-data.php, includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-widget.php, public/class-urlslab-public.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1100
=> feat: content lazy loading

includes/widgets/class-urlslab-widget.php
=> fix: handle multicheckbox setting values

includes/widgets/class-urlslab-widget.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1111
=> fix: value type error

admin/src/api/menuValues.js, admin/src/components/SettingsOption.jsx, admin/src/components/TableViewHeader.jsx, admin/src/elements/FilterMenu.jsx, admin/src/elements/SortMenu.jsx, admin/src/main.jsx, admin/src/modules/KeywordsLinks.jsx, admin/src/modules/LazyLoading.jsx, admin/src/modules/LinkEnhancer.jsx, admin/src/modules/MediaOffloader.jsx, admin/src/modules/RelatedResources.jsx, admin/src/tables/CSSCacheTable.jsx, admin/src/tables/ContentCache.jsx, admin/src/tables/ContentCacheTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/URLRelationTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
Multiple tables added to admin
=> I#986 04 react admin Multiple tables

includes/cron/class-urlslab-optimize-cron.php, includes/widgets/class-urlslab-optimize.php, urlslab.php
=> deleting not needed WP content

admin/src/assets/styles/components/_TableComponent.scss, admin/src/assets/styles/elements/_Inputs.scss, admin/src/components/SettingsOption.jsx, admin/src/tables/ContentCacheTable.jsx
Content cache, datetime element with time showing
=> I#986 05 react admin

admin/src/assets/styles/components/_TableComponent.scss, admin/src/assets/styles/elements/_FilterMenu.scss, admin/src/assets/styles/layouts/_AppLayout.scss, admin/src/assets/styles/layouts/_DynamicModule.scss, admin/src/components/SettingsOption.jsx, admin/src/elements/FilterMenu.jsx, admin/src/modules/Settings.jsx
Multicheck attribute to show items in title with comma, css fixes
=> I#986 06 react admin

includes/cron/class-urlslab-optimize-cron.php, includes/widgets/class-urlslab-optimize.php
=> Wp optimizations

includes/cron/class-urlslab-optimize-cron.php, includes/widgets/class-urlslab-optimize.php
=> Optimization tasks

includes/cron/class-urlslab-download-css-cron.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1128
=> fix: fatal error

includes/widgets/class-urlslab-lazy-loading.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1135
=> fix: php warning undefined array key

admin/package.json, admin/src/App.jsx, admin/src/api/exportCsv.js, admin/src/assets/styles/components/_TableComponent.scss, admin/src/assets/styles/layouts/_AppLayout.scss, admin/src/components/Header.jsx, admin/src/components/Notifications.jsx, admin/src/components/TableComponent.jsx, admin/src/components/TableViewHeaderBottom.jsx, admin/src/constants/contextProvider.js, admin/src/elements/ExportCSVButton.jsx, admin/src/elements/MenuInput.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/yarn.lock
=> I#986 08 react admin

includes/widgets/class-urlslab-lazy-loading.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1139
=> fix: video should load correct thumbnail url and not svg image

admin/.eslintrc, admin/src/assets/styles/common/_mixins.scss, admin/src/assets/styles/components/_TableComponent.scss, admin/src/assets/styles/layouts/_AppLayout.scss, admin/src/components/TableComponent.jsx, admin/src/tables/LinkManagerTable.jsx
Screenshot to link management, big table automatic resizing with horizontal scroll
=> I#986 09 react admin

admin/includes/api/class-urlslab-api-table-sql.php, admin/includes/api/class-urlslab-api-table.php, includes/services/api/class-urlslab-screenshot-api.php, includes/services/class-urlslab-url-data-fetcher.php, includes/services/models/class-urlslab-screenshot-batch-request.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1151
=> fix: multiple fatal errors reported after refactoring

includes/cron/class-urlslab-screenshot-cron.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1155
=> fix: call to a member function get_url_id on string

admin/includes/api/class-urlslab-api-content-cache.php, admin/includes/api/class-urlslab-api-css-cache.php, admin/includes/api/class-urlslab-api-files.php, admin/includes/api/class-urlslab-api-keywords.php, admin/includes/api/class-urlslab-api-table-sql.php, admin/includes/api/class-urlslab-api-table.php, admin/includes/api/class-urlslab-api-url-relations.php, admin/includes/api/class-urlslab-api-urls.php, admin/includes/api/class-urlslab-api-youtube-cache.php
=> fix of delete api and added count api

admin/includes/api/class-urlslab-api-keywords.php, admin/includes/api/class-urlslab-api-url-relations.php, includes/services/class-urlslab-css-cache-row.php, includes/services/class-urlslab-url-row.php, includes/widgets/class-urlslab-css-optimizer.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-media-offloader-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1161
=> fix: url parsing exceptions

includes/services/class-urlslab-url-data-fetcher.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1162
=> fix: scheduling of urls

admin/includes/api/class-urlslab-api-css-cache.php, admin/includes/api/class-urlslab-api-files.php, admin/includes/api/class-urlslab-api-keywords.php, admin/includes/api/class-urlslab-api-table-sql.php, admin/includes/api/class-urlslab-api-table.php, admin/includes/api/class-urlslab-api-url-relations.php, admin/includes/api/class-urlslab-api-urls.php, admin/includes/api/class-urlslab-api-youtube-cache.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1163
=> feat: complex api filters

admin/includes/api/class-urlslab-api-search-replace.php, includes/class-urlslab-activator.php, includes/class-urlslab-api-router.php, includes/class-urlslab-available-widgets.php, includes/class-urlslab.php, includes/services/class-urlslab-search-replace-row.php, includes/widgets/class-urlslab-search-replace.php, urlslab.php
=> feat: search and replace

admin/src/App.jsx, admin/src/api/fetchLangs.js, admin/src/elements/LangMenu.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/tables/KeywordsTable.jsx
=> I#986 14 react admin

admin/includes/api/class-urlslab-api-search-replace.php, admin/includes/api/class-urlslab-api-table.php, includes/widgets/class-urlslab-search-replace.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1167
=> feat: import search and replace module

includes/class-urlslab-activator.php, includes/class-urlslab.php, urlslab.php
automatic update steps of plugin when admin interface opened
=> chore: update steps refactoring

admin/src/assets/images/icon-checkmark.svg, admin/src/assets/images/icon-minus.svg, admin/src/assets/styles/common/_typography.scss, admin/src/assets/styles/components/_OverviewTemplate.scss, admin/src/assets/styles/components/_TableComponent.scss, admin/src/assets/styles/elements/_Button.scss, admin/src/assets/styles/elements/_FilterMenu.scss, admin/src/assets/styles/elements/_Inputs.scss, admin/src/assets/styles/elements/_Switch.scss, admin/src/assets/styles/layouts/_Settings.scss, admin/src/components/DashboardModule.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/components/OverviewTemplate.jsx, admin/src/components/TableComponent.jsx, admin/src/elements/FilterMenu.jsx, admin/src/elements/LangMenu.jsx, admin/src/elements/MenuInput.jsx, admin/src/elements/SortMenu.jsx, admin/src/elements/Switch.jsx, admin/src/hooks/filteringSorting.jsx, admin/src/hooks/useTableUpdater.jsx, admin/src/modules/Settings.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
Small fixes to layout, table headers and filters functionality
=> I#986 16 react admin

includes/widgets/class-urlslab-search-replace.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1178
=> fix: error undefined constant str_replace

admin/src/overview/RelatedResources.jsx, includes/widgets/class-urlslab-related-resources-widget.php, urlslab.php
=> related resources - summary texts

composer.lock, includes/cron/class-urlslab-screenshots-cron.php, includes/widgets/class-urlslab-meta-tag.php
=> chore: refactoring meta tags widget

admin/src/assets/styles/components/_MainMenu.scss, admin/src/assets/styles/components/_Panel.scss, admin/src/assets/styles/components/_TableComponent.scss, admin/src/assets/styles/elements/_FilterMenu.scss, admin/src/assets/styles/elements/_Inputs.scss, admin/src/components/MainMenu.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/components/RowInserter.jsx, admin/src/components/TableComponent.jsx, admin/src/elements/InputField.jsx, admin/src/elements/LangMenu.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/hooks/useTableUpdater.jsx, admin/src/tables/CSSCacheTable.jsx, admin/src/tables/ContentCacheTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/SearchReplaceTable.jsx, admin/src/tables/URLRelationTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
New row adding supported, new columns
=> I#986 18 react admin

admin/src/assets/styles/components/_Loader.scss, admin/src/components/Loader.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/hooks/useChangeRow.jsx
=> feat: row counter in table header

admin/includes/api/class-urlslab-api-base.php, admin/includes/api/class-urlslab-api-schedules.php, composer.lock, includes/class-urlslab-api-router.php, includes/widgets/class-urlslab-general.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1201
=> feat: schedule management

admin/includes/api/class-urlslab-api-base.php, admin/includes/api/class-urlslab-api-keywords.php, admin/includes/api/class-urlslab-api-schedules.php, admin/includes/api/class-urlslab-api-search-replace.php, admin/includes/api/class-urlslab-api-table.php, admin/includes/api/class-urlslab-api-url-relations.php, composer.lock
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1203
=> feat: create item api

admin/src/assets/styles/components/_ModuleViewHeader.scss, admin/src/assets/styles/elements/_FilterMenu.scss, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/constants/exportWorker.js, admin/src/constants/tableFunctions.js, admin/src/elements/Checkbox.jsx, admin/src/elements/FilterMenu.jsx, admin/src/elements/SortMenu.jsx, admin/src/hooks/filteringSorting.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/modules/Screenshot.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/ScreenshotTable.jsx, admin/src/tables/SearchReplaceTable.jsx
Sorting Ascending/descending, rows count on filter
=> I#986 20 react admin

includes/class-urlslab.php, includes/cron/class-urlslab-summaries-cron.php, includes/widgets/class-urlslab-general.php
=> Summaries - load from urlslab

includes/cron/class-urlslab-convert-avif-images-cron.php, includes/cron/class-urlslab-convert-images-cron.php, includes/cron/class-urlslab-convert-webp-images-cron.php
=> fix: fatal error - return value must be of type array, string returned

admin/.eslintrc, admin/src/App.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/components/Notifications.jsx, admin/src/hooks/filteringSorting.jsx, admin/src/hooks/useInfiniteFetch.jsx, admin/src/hooks/useTableUpdater.jsx, admin/src/main.jsx, admin/src/modules/Settings.jsx, admin/src/tables/CSSCacheTable.jsx, admin/src/tables/ContentCacheTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/ScreenshotTable.jsx, admin/src/tables/SearchReplaceTable.jsx, admin/src/tables/URLRelationTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
Persisting table state (filters, sorting) on rerenders when clicking through components
=> I#986 21 react admin

admin/src/App.jsx, admin/src/assets/styles/elements/_FilterMenu.scss, admin/src/components/MainMenu.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/constants/tableImports.js, admin/src/modules/Schedule.jsx, admin/src/modules/Settings.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/SchedulesTable.jsx, admin/src/tables/ScreenshotTable.jsx
=> feat: added schedules table

admin/includes/api/class-urlslab-api-table-sql.php, admin/includes/api/class-urlslab-api-table.php, admin/includes/api/class-urlslab-api-url-relations.php, composer.lock, includes/cron/class-urlslab-offload-background-attachments-cron.php, includes/data/class-urlslab-data.php, includes/widgets/class-urlslab-keywords-links.php, package.json, urlslab.php
=> fix sql error in api

includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-link-enhancer.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1224
=> fix: move some settings from keyword manager to link manager

admin/src/App.jsx, admin/src/api/cron.js, admin/src/assets/images/icon-play.svg, admin/src/assets/styles/common/_global.scss, admin/src/assets/styles/common/_typography.scss, admin/src/assets/styles/components/_Notifications.scss, admin/src/assets/styles/components/_NotificationsPanel.scss, admin/src/assets/styles/elements/_Button.scss, admin/src/components/Header.jsx, admin/src/components/Notifications.jsx, admin/src/components/NotificationsPanel.jsx, admin/src/elements/ProgressBar.jsx
Cron start button with notifications panel
=> I#986 25 react admin

includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1227
=> feat: include related articles automatically in page

includes/widgets/class-urlslab-image-alt-text.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1232
=> feat: setting definition for image seo algorythm

Makefile, includes/class-urlslab.php, info.json, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1213
=> plugin auto updating

.github/scripts/generate-changelog.js, .github/scripts/get-changelog-from-readme-txt.js, .github/scripts/update-readme-stable-version.sh, .github/workflows/publish-release.yml
release first generation of auto changelog
**Checklist**
=> feat: release first generation of auto changelog

admin/class-urlslab-admin.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1238
=> fix: api nonce

includes/api/class-urlslab-api-languages.php, includes/class-urlslab-api-router.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1241
=> feat: languages api

includes/api/class-urlslab-api-languages.php, includes/api/class-urlslab-api-table-sql.php, includes/api/class-urlslab-api-table.php, includes/data/class-urlslab-url-row.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1163
=> fix: fix filter operators

includes/data/class-urlslab-data.php, includes/data/class-urlslab-keyword-row.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1240
=> fix: updating of rows in db objects

includes/data/class-urlslab-keyword-map-row.php, includes/data/class-urlslab-keyword-row.php, includes/data/class-urlslab-search-replace-row.php, includes/data/class-urlslab-youtube-row.php
=> fix: default values for data class

includes/api/class-urlslab-api-table-sql.php, includes/api/class-urlslab-api-table.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1246
=> feat: new filter string operators

includes/data/class-urlslab-url-row.php, includes/widgets/class-urlslab-screenshot-widget.php, includes/wp-widgets/class-urlslab-wp-widget-screenshot.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1253
=> Screenshot widget

admin/class-urlslab-admin.php, admin/src/App.jsx, admin/src/api/cron.js, admin/src/components/Header.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/modules/Modules.jsx, admin/src/tables/CSSCacheTable.jsx, admin/src/tables/ContentCacheTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/SchedulesTable.jsx, admin/src/tables/ScreenshotTable.jsx, admin/src/tables/SearchReplaceTable.jsx, admin/src/tables/URLRelationTable.jsx, admin/src/tables/YouTubeCacheTable.jsx, admin/vite.config.js
Fixing various bugs in cron error, missing module General.jsx and missing buttons 
Close QualityUnit/web-issues#1244
=> [1244] fix: cron error response, module missing, import export delete

admin/src/api/cron.js, admin/src/assets/styles/components/_NotificationsPanel.scss, admin/src/components/Header.jsx, admin/src/components/ImportPanel.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/components/TableFilter.jsx, admin/src/hooks/filteringSorting.jsx, admin/src/hooks/useInfiniteFetch.jsx
Fixed cron multiple executions due to setInterval, error message if status not in 200-299 range
Close QualityUnit/web-issues#1256
Close QualityUnit/web-issues#1259
Close QualityUnit/web-issues#1261
Close QualityUnit/web-issues#1262
Close QualityUnit/web-issues#1263
Close QualityUnit/web-issues#1265
Close QualityUnit/web-issues#1266
=> [1263] fix: cron multiple execution, #1261 cron error message

admin/src/App.jsx, admin/src/api/fetchLangs.js, admin/src/assets/styles/elements/_FilterMenu.scss, admin/src/components/ImportPanel.jsx, admin/src/components/TableFilter.jsx, admin/src/elements/FilterMenu.jsx, admin/src/elements/LangMenu.jsx, admin/src/elements/SortMenu.jsx, admin/src/tables/KeywordsTable.jsx
Fixes language menu missing items, uses /language endpoint instead of WPML, multibox values instead of keys
Close QualityUnit/web-issues#1230
Close QualityUnit/web-issues#1233
Close QualityUnit/web-issues#1245
=> fix: language menu, multicheckbox values

includes/api/class-urlslab-api-table-sql.php, includes/api/class-urlslab-api-urls.php, includes/data/class-urlslab-data.php, includes/data/class-urlslab-url-row.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1269
=> fix: replace E value with empty string in API

admin/src/api/cron.js, admin/src/assets/styles/elements/_Button.scss, admin/src/components/DangerPanel.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/components/RowInserter.jsx, admin/src/components/TableFilter.jsx, admin/src/constants/filterReducer.js, admin/src/constants/tableFunctions.js, admin/src/constants/tableImports.js, admin/src/hooks/filteringSorting.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/hooks/useInfiniteFetch.jsx, admin/src/hooks/useTableUpdater.jsx, admin/src/modules/CssOptimizer.jsx, admin/src/modules/KeywordsLinks.jsx, admin/src/modules/LazyLoading.jsx, admin/src/modules/Modules.jsx, admin/src/tables/CSSCacheTable.jsx, admin/src/tables/ContentCacheTable.jsx, admin/src/tables/GeneratorTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/SchedulesTable.jsx, admin/src/tables/ScreenshotTable.jsx, admin/src/tables/SearchReplaceTable.jsx, admin/src/tables/URLRelationTable.jsx, admin/src/tables/YouTubeCacheTable.jsx, admin/vite.config.js
Rewrite of table filtering, code cleanup
Close QualityUnit/web-issues#1244
=> I#986 33 react admin

includes/cron/class-urlslab-screenshots-cron.php, includes/cron/class-urlslab-summaries-cron.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1272
=> fix: missing class

includes/api/class-urlslab-api-cron.php, includes/class-urlslab.php, includes/cron/class-urlslab-cron-manager.php, includes/cron/class-urlslab-cron.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1277
=> fix: cron task manager execution

includes/data/class-urlslab-data.php, includes/data/class-urlslab-search-replace-row.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1284
=> load autoincremented value after insert

includes/widgets/class-urlslab-link-enhancer.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1288
=> fix: fatal error if current page url is not allowed or invalid

includes/api/class-urlslab-api-table.php, includes/data/class-urlslab-keyword-row.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1285
=> fix: corrent handling of create_item for keywords

admin/src/assets/styles/common/_global.scss, admin/src/assets/styles/components/_Panel.scss, admin/src/assets/styles/components/_TableComponent.scss, admin/src/assets/styles/components/_TableFilter.scss, admin/src/assets/styles/elements/_Button.scss, admin/src/assets/styles/elements/_FilterMenu.scss, admin/src/assets/styles/elements/_Inputs.scss, admin/src/assets/styles/elements/_MenuArrow.scss, admin/src/assets/styles/elements/_Tooltip.scss, admin/src/assets/styles/layouts/_AppLayout.scss, admin/src/components/InsertRowPanel.jsx, admin/src/components/ModuleViewHeader.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/components/TableComponent.jsx, admin/src/components/TableFilter.jsx, admin/src/components/TableFilterPanel.jsx, admin/src/elements/ColumnsMenu.jsx, admin/src/elements/InputField.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/modules/MetaTag.jsx, admin/src/modules/SearchAndReplace.jsx, admin/src/tables/GeneratorTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/MetaTagsTable.jsx, admin/src/tables/SearchReplaceTable.jsx, admin/src/tables/URLRelationTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
Multiple changes, table filtering
=> I#986 36 react admin

admin/src/api/fetching.js, admin/src/assets/styles/common/_global.scss, admin/src/assets/styles/common/_typography.scss, admin/src/assets/styles/components/_TableComponent.scss, admin/src/assets/styles/components/_TableFilter.scss, admin/src/assets/styles/elements/_Button.scss, admin/src/assets/styles/elements/_FilterMenu.scss, admin/src/components/TableFilter.jsx, admin/src/components/TableFilterPanel.jsx, admin/src/constants/filterReducer.js, admin/src/elements/SortMenu.jsx, admin/src/hooks/filteringSorting.jsx
preliminary editing of filters (not working yet), filter panel as component
=> feat: preliminary editing of filters (not working yet)

composer.lock, includes/cron/class-urlslab-generators-cron.php, includes/widgets/class-urlslab-widget.php
in case urlslab doesn't find documents related to urlfilter, it returns 404 .... it could mean there is no document indexed yet in the vector database
=> error handling of content generator

admin/.eslintrc, admin/src/components/TableFilter.jsx, admin/src/components/TableFilterPanel.jsx, admin/src/d3/D3WordCloud.jsx, admin/src/elements/FilterMenu.jsx, admin/src/elements/InputField.jsx, admin/src/elements/LangMenu.jsx, admin/src/elements/RangeInputs.jsx, admin/src/elements/SortMenu.jsx, admin/src/hooks/filteringSorting.jsx, admin/src/lib/filterOperators.js, admin/src/lib/filterReducer.js, admin/src/modules/KeywordsLinks.jsx, admin/src/modules/Screenshot.jsx, admin/src/tables/CSSCacheTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/MetaTagsTable.jsx, admin/src/tables/ScreenshotTable.jsx, admin/src/tables/SearchReplaceTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
Multiple filter bugfixes, menus in filters for ie. types, language etc.
=> I#986 39 react admin

includes/api/class-urlslab-api-redirects.php, includes/widgets/class-urlslab-redirects.php
=> feat: identify redirect client by urlslab name

admin/src/tables/NotFoundTable.jsx, includes/class-urlslab-activator.php, includes/data/class-urlslab-not-found-log-row.php, includes/widgets/class-urlslab-redirects.php, urlslab.php
logging of additional information about request 
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1307
=> feat: log request data if 404

admin/src/lib/filterOperators.js
Condition to call proper url for NOTIN operator)
=> fix: condition to call proper url for NOTIN operator

admin/src/tables/RedirectsTable.jsx, includes/api/class-urlslab-api-redirects.php, includes/data/class-urlslab-redirect-row.php
Close https://github.com/QualityUnit/web-issues/issues/1311
=> fix: changing of redirect status code number

admin/src/d3/D3WordCloud.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/ScreenshotTable.jsx, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-urls.php, includes/data/class-urlslab-redirect-row.php
Close https://github.com/QualityUnit/web-issues/issues/1312
Close https://github.com/QualityUnit/web-issues/issues/1313
=> fix: add protocol to urls, fix counts in urls, screenshots and keyword api

admin/package.json, admin/src/assets/styles/components/_Panel.scss, admin/src/assets/styles/components/_TableComponent.scss, admin/src/components/DetailsPanel.jsx, admin/src/elements/BrowserIcon.jsx, admin/src/tables/NotFoundTable.jsx, admin/src/tables/RedirectsTable.jsx
[Describe what was changed in the Pull Request](feat: browser icon images in 404 table, parsing ua)
=> feat: browser icon images in 404 table, parsing ua

admin/package.json, admin/src/assets/styles/elements/_Tooltip.scss, admin/src/elements/BrowserIcon.jsx, admin/src/tables/NotFoundTable.jsx
OS icons added, fallback to text if not found
=> feat: 404 table os icons

admin/src/api/cron.js, admin/src/api/deleteTableData.js, admin/src/api/fetchLangs.js, admin/src/api/fetching.js, admin/src/api/settings.js, admin/src/lib/exportWorker.js, includes/api/class-urlslab-api-urls.php
https://github.com/QualityUnit/web-issues/issues/1316
not ready, js part needs to be modified
=> fix: add from_dest_url_id and from_src_url_id

admin/.eslintrc, admin/src/assets/styles/components/_Panel.scss, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/d3/D3WordCloud.jsx, admin/src/elements/Tooltip_SortingFiltering.jsx, admin/src/hooks/useInfiniteFetch.jsx, admin/src/lib/helpers.js, admin/src/lib/tableImports.js, admin/src/tables/CSSCacheTable.jsx, admin/src/tables/ContentCacheTable.jsx, admin/src/tables/GeneratorTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/MetaTagsTable.jsx, admin/src/tables/NotFoundTable.jsx, admin/src/tables/RedirectsTable.jsx, admin/src/tables/SchedulesTable.jsx, admin/src/tables/ScreenshotTable.jsx, admin/src/tables/SearchReplaceTable.jsx, admin/src/tables/URLRelationTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
Performance improvements, usage modal fixes, filtering & sorting info Tooltip
=> I#986 48 react admin

includes/widgets/class-urlslab-redirects.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1335
=> fix: if multiple ips stored in log, analyze just first IP

includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-table-sql.php, includes/api/class-urlslab-api-urls.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1340
=> fix: filtering values with 0 or counts

includes/api/class-urlslab-api-not-found-log.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1341
=> fix: filtering values in request_data

includes/cron/class-urlslab-related-resources-cron.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1342
=> fix: request related resources just for valid urls

admin/src/App.jsx, admin/src/api/cron.js, admin/src/api/deleteTableData.js, admin/src/api/exportCsv.js, admin/src/api/fetchLangs.js, admin/src/api/fetching.js, admin/src/api/settings.js, admin/src/assets/styles/components/_Loader.scss, admin/src/assets/styles/components/datepicker/datepicker.scss, admin/src/components/ImportPanel.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/components/TableFilterPanel.jsx, admin/src/elements/Tooltip_SortingFiltering.jsx, admin/src/hooks/filteringSorting.jsx, admin/src/lib/filterOperators.js, admin/src/tables/CSSCacheTable.jsx, admin/src/tables/ContentCacheTable.jsx, admin/src/tables/GeneratorTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/MetaTagsTable.jsx, admin/src/tables/NotFoundTable.jsx, admin/src/tables/RedirectsTable.jsx, admin/src/tables/SchedulesTable.jsx, admin/src/tables/ScreenshotTable.jsx, admin/src/tables/SearchReplaceTable.jsx, admin/src/tables/URLRelationTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
Required/optional headers for csv import
Close QualityUnit/web-issues#1187
Close QualityUnit/web-issues#1188
Close QualityUnit/web-issues#1189
Close QualityUnit/web-issues#1190
=> feat: required/optional headers for csv import

admin/dist/assets/main.css, admin/src/modules/KeywordsLinks.jsx, admin/src/tables/CSSCacheTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/MetaTagsTable.jsx, admin/src/tables/ScreenshotTable.jsx
changed values to read only and added/removed columns
Media manager – driver column set to menu, endpoint in API to change it will be added by @vzeman 
Close QualityUnit/web-issues#1351
Close QualityUnit/web-issues#1352
Close QualityUnit/web-issues#1353
Close QualityUnit/web-issues#1354
Close QualityUnit/web-issues#1355
=> [1351] fix: changed values to read only and added/removed columns

includes/api/class-urlslab-api-content-cache.php, includes/api/class-urlslab-api-content-generators.php, includes/api/class-urlslab-api-css-cache.php, includes/api/class-urlslab-api-files.php, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-not-found-log.php, includes/api/class-urlslab-api-redirects.php, includes/api/class-urlslab-api-url-relations.php, includes/api/class-urlslab-api-urls.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1346
=> fix: error handling for get_items and empty table

admin/src/api/cron.js, admin/src/assets/styles/elements/_Tooltip.scss, admin/src/assets/styles/layouts/_Settings.scss, admin/src/components/Header.jsx, admin/src/components/SettingsOption.jsx, admin/src/lib/headerReducer.js
Settings validation on fetch success/fail
Close QualityUnit/web-issues#1302
=> [1302] feat: #1302 settings validation

includes/widgets/class-urlslab-meta-tag.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1214
=> feat: Twitter meta tags

includes/api/class-urlslab-api-search-replace.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1378
=> fix: update search and replace row

includes/class-urlslab-activator.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1377
=> fix: duplicate redirects after import

includes/api/class-urlslab-api-redirects.php, includes/api/class-urlslab-api-table.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1376
=> fix: import of redirect should reset cnt to 0

includes/class-urlslab-activator.php, includes/data/class-urlslab-data.php, includes/data/class-urlslab-redirect-row.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/1377
=> fix: redirect duplicates

includes/class-urlslab-activator.php, includes/cron/class-urlslab-related-resources-cron.php, includes/data/class-urlslab-data.php, includes/data/class-urlslab-redirect-row.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-widget.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1402
=> related resources not loaded, additional domains for related resources

admin/src/overview/RelatedResources.jsx, admin/src/tables/MediaFilesTable.jsx, includes/api/class-urlslab-api-files.php, includes/cron/class-urlslab-related-resources-cron.php, includes/cron/class-urlslab-youtube-cron.php, includes/data/class-urlslab-url-row.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-screenshot-widget.php, includes/widgets/class-urlslab-widget.php
- offloading of urlslab images
- lazy loading of related resources images
Close https://github.com/QualityUnit/web-issues/issues/1298
=> fix: lazy loading and offloading of related resources images

admin/src/overview/Generator.jsx, includes/cron/class-urlslab-generators-cron.php, includes/cron/class-urlslab-related-resources-cron.php, includes/widgets/class-urlslab-content-generator-widget.php
Close https://github.com/QualityUnit/web-issues/issues/1403
=> rename shortcode attributes, fix fatal error in related resources cron, modify alg how we filter semantic content

includes/api/class-urlslab-api-files.php
partial implementation of the task, UI part is not ready, this is just file transfer part
https://github.com/QualityUnit/web-issues/issues/1367
=> feat: API to transfer files between storages

includes/api/class-urlslab-api-content-generators.php
prompt engineering test to fix some issues in translations
Close https://github.com/QualityUnit/web-issues/issues/1398
=> fix: prompt engineering for translations and input text validation

includes/widgets/class-urlslab-content-generator-widget.php
https://github.com/QualityUnit/web-issues/issues/1415
=> chore: don't use template if template name not set

admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/elements/BrowserIcon.jsx
=> I#986 59 react admin

includes/data/class-urlslab-url-row.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-screenshot-widget.php
Close https://github.com/QualityUnit/web-issues/issues/1418
=> fix: scheduling of images

admin/src/tables/LinkManagerTable.jsx, includes/api/class-urlslab-api-meta-tags.php, includes/api/class-urlslab-api-urls.php, includes/class-urlslab-activator.php, includes/cron/class-urlslab-update-url-http-status-cron.php, includes/data/class-urlslab-url-row.php, includes/widgets/class-urlslab-link-enhancer.php, urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1421
=> redirect link replaced with real destination url

admin/src/hooks/useChangeRow.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/RedirectsTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
Implemented Youtube Usage details panel, Media manager transfer, visibility of Redirects columns
Close QualityUnit/web-issues#1367
Close QualityUnit/web-issues#1369
Close QualityUnit/web-issues#1385
=> [1367] feat fixes: 1367, 1369, 1385

includes/api/class-urlslab-api-content-generators.php
changed capability for translator
Close https://github.com/QualityUnit/web-issues/issues/1431
=> fix: translation permissions

includes/api/class-urlslab-api-schedules.php
Close https://github.com/QualityUnit/web-issues/issues/1439
=> fix: schedules api should use POST to get items

includes/api/class-urlslab-api-billing.php, includes/api/class-urlslab-api-content-generators.php, includes/api/class-urlslab-api-files.php, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-urls.php, includes/api/class-urlslab-api-youtube-cache.php
Close https://github.com/QualityUnit/web-issues/issues/1441
=> fix: change get to post for list api calls

includes/api/class-urlslab-api-urls.php
just api implementation
https://github.com/QualityUnit/web-issues/issues/1442
=> feat: offer multiple image format URLs in API of urls

includes/api/class-urlslab-api-base.php, includes/api/class-urlslab-api-content-generators.php, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-modules.php, includes/api/class-urlslab-api-optimize.php, includes/api/class-urlslab-api-permissions.php, includes/api/class-urlslab-api-schedules.php, includes/class-urlslab-activator.php
Close https://github.com/QualityUnit/web-issues/issues/1446
=> plugin capabilities, user capability and roles management

includes/api/class-urlslab-api-billing.php, includes/api/class-urlslab-api-content-cache.php, includes/api/class-urlslab-api-content-generators.php, includes/api/class-urlslab-api-cron.php, includes/api/class-urlslab-api-css-cache.php, includes/api/class-urlslab-api-files.php, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-labels.php, includes/api/class-urlslab-api-languages.php, includes/api/class-urlslab-api-meta-tags.php, includes/api/class-urlslab-api-modules.php, includes/api/class-urlslab-api-not-found-log.php, includes/api/class-urlslab-api-optimize.php, includes/api/class-urlslab-api-permissions.php, includes/api/class-urlslab-api-redirects.php, includes/api/class-urlslab-api-schedules.php, includes/api/class-urlslab-api-screenshots.php, includes/api/class-urlslab-api-search-replace.php, includes/api/class-urlslab-api-settings.php, includes/api/class-urlslab-api-url-relations.php, includes/api/class-urlslab-api-urls.php, includes/api/class-urlslab-api-youtube-cache.php
Close https://github.com/QualityUnit/web-issues/issues/1447
=> feat: label modules api, fixed labels for keyword table

admin/src/tables/GeneratorShortcodeTable.jsx, admin/src/tables/SchedulesTable.jsx, includes/api/class-urlslab-api-schedules.php, includes/api/class-urlslab-api-shortcodes.php, includes/data/class-urlslab-generator-shortcode-row.php, includes/widgets/class-urlslab-content-generator-widget.php
- dialog to add schedules
- dialog to add shortcode in generators
checkboxes are not working correctly
Close QualityUnit/web-issues#1451
=> fea: addingin schedules and shortcodes

includes/cron/class-urlslab-update-url-http-status-cron.php
Close https://github.com/QualityUnit/web-issues/issues/1455
=> fix: memory optimization - skip loading full html content

admin/dist/assets/main.css, admin/src/assets/styles/elements/_Tag.scss, admin/src/assets/styles/elements/_TagsMenu.scss, admin/src/elements/TagsMenu.jsx
Tags menu in table with predefined values, writing new tag created in menu to database (no optimistic update now)
=> feat: writing freshly created tags in tag menu to database

admin/src/overview/Generator.jsx, includes/cron/class-urlslab-youtube-cron.php, includes/data/class-urlslab-youtube-row.php, includes/widgets/class-urlslab-content-generator-widget.php
small improvements for video vidget
=> fix: loading of video_description and other microdata

admin/src/overview/Generator.jsx, includes/data/class-urlslab-youtube-row.php, includes/widgets/class-urlslab-content-generator-widget.php, includes/widgets/class-urlslab-lazy-loading.php
some more YT variables added to generator
video_channel_title
video_tags
=> feat: additional youtube variables

admin/src/tables/GeneratorShortcodeTable.jsx, includes/widgets/class-urlslab-content-generator-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1465
=> fix: added description to field, process youtube url as videoid

includes/class-urlslab-file-cache.php
Close https://github.com/QualityUnit/web-issues/issues/1466
=> fix: warning if file not accessible

admin/dist/assets/main.css, admin/src/assets/styles/components/_Panel.scss, admin/src/assets/styles/elements/_TagsMenu.scss, admin/src/components/ColorPicker.jsx, admin/src/components/EditRowPanel.jsx, admin/src/elements/LangMenu.jsx, admin/src/elements/TagsMenu.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/modules/TagsLabels.jsx, admin/src/tables/GeneratorShortcodeTable.jsx, admin/src/tables/KeywordsTable.jsx
editor for generator, other editor changes
=> I1373 editing row v2

includes/class-urlslab-activator.php, includes/cron/class-urlslab-update-url-http-status-cron.php, includes/cron/class-urlslab-youtube-cron.php, includes/widgets/class-urlslab-related-resources-widget.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/1470
Close https://github.com/QualityUnit/web-issues/issues/1467
=> fix: fatal error fix in related resources, fixed scheduling of youtube videos

admin/src/components/DetailsPanel.jsx, admin/src/components/EditRowPanel.jsx, admin/src/elements/TagsMenu.jsx, admin/src/elements/Textarea.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/modules/TagsLabels.jsx
=> fix: usage table, tags menu in keywords edit panel

includes/cron/class-urlslab-generators-cron.php, includes/cron/class-urlslab-youtube-cron.php, includes/widgets/class-urlslab-content-generator-widget.php
Close https://github.com/QualityUnit/web-issues/issues/1473
=> fix: processing of youtube videos and missing captions 

includes/api/class-urlslab-api-files.php, includes/api/class-urlslab-api-generators.php, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-shortcodes.php, includes/api/class-urlslab-api-table.php, includes/api/class-urlslab-api-urls.php, includes/api/class-urlslab-api-youtube-cache.php
=> fixed usage popup api calls

admin/src/tables/GeneratorShortcodeTable.jsx, includes/api/class-urlslab-api-shortcodes.php, includes/widgets/class-urlslab-content-generator-widget.php
Close https://github.com/QualityUnit/web-issues/issues/1480
=> feat: show shortcode in the table

admin/js/urlslab-wpml.js, admin/src/components/ImportPanel.jsx, admin/src/tables/GeneratorShortcodeTable.jsx, admin/src/tables/YouTubeCacheTable.jsx, includes/api/class-urlslab-api-youtube-cache.php, includes/data/class-urlslab-youtube-row.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1459
=> feat: export and delete all for yt videos

admin/src/overview/Generator.jsx, admin/src/tables/GeneratorShortcodeTable.jsx, includes/cron/class-urlslab-generators-cron.php, includes/data/class-urlslab-youtube-row.php, includes/widgets/class-urlslab-content-generator-widget.php, includes/widgets/class-urlslab-related-resources-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1485
Close https://github.com/QualityUnit/web-issues/issues/1484
=> bug fix related articles and formatting generator variables

assets/scss/urlslab_related_resources.scss, includes/class-urlslab-url.php, includes/widgets/class-urlslab-related-resources-widget.php
change related articles structure
**Checklist**
Close QualityUnit/web-issues#1429
=> [1429] feat: change related articles structure

includes/cron/class-urlslab-generators-cron.php, includes/cron/class-urlslab-youtube-cron.php
- fixed handling api errors
- fixed the way how we send context to augmenting api
=> Yt data fix

admin/js/urlslab-wpml.js, admin/src/assets/styles/elements/_TagsMenu.scss, admin/src/components/DetailsPanel.jsx, admin/src/elements/Editor.jsx, admin/src/tables/GeneratorResultTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx, admin/src/tables/NotFoundTable.jsx, includes/widgets/class-urlslab-content-generator-widget.php
Close QualityUnit/web-issues#1417
Close QualityUnit/web-issues#1462
=> [1417] usage links for generator

includes/api/class-urlslab-api-generators.php
urlslab api was changed and code now reflexts the new API
Close https://github.com/QualityUnit/web-issues/issues/1494
=> fix: translation api

includes/cron/class-urlslab-related-resources-cron.php, includes/widgets/class-urlslab-related-resources-widget.php
Close https://github.com/QualityUnit/web-issues/issues/1495
=> feat: limit urls included in related resources results by time of last seen

admin/js/urlslab-wpml.js
**Checklist**
Close QualityUnit/web-issues#1500
=> [1500] fix: translation buttons functionality

includes/api/class-urlslab-api-generators.php, includes/api/class-urlslab-api-shortcodes.php
Close https://github.com/QualityUnit/web-issues/issues/1496
=> fix: deleting of shortcodes or results should delete also related data

admin/src/tables/GeneratorResultTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1498
=> fix: added missing button to change the statu of row

admin/src/api/exportCsv.js, admin/src/api/importCsv.js, admin/src/components/ExportPanel.jsx, admin/src/components/ImportPanel.jsx
Cancel button in Import/Export panels cancels fetching of data
Close QualityUnit/web-issues#1499
=> [1499] feat: abort export/import on cancel button

admin/js/urlslab-wpml.js
Close https://github.com/QualityUnit/web-issues/issues/1513
=> fix: translation of all messages should continue if empty result

includes/api/class-urlslab-api-schedules.php
Close https://github.com/QualityUnit/web-issues/issues/1503
=> fix: scheduling new values in schedules

admin/src/App.jsx, admin/src/assets/styles/components/_DashboardModule.scss, admin/src/assets/styles/elements/_SearchField.scss, admin/src/assets/styles/layouts/_Header.scss, admin/src/components/DashboardModule.jsx, admin/src/components/DynamicModule.jsx, admin/src/components/MainMenu.jsx, admin/src/elements/LangMenu.jsx, admin/src/elements/MultiSelectMenu.jsx, admin/src/elements/SearchField.jsx, admin/src/elements/Tag.jsx, admin/src/lib/hexToHSL.js, admin/src/modules/Modules.jsx, admin/src/tables/YouTubeCacheTable.jsx
Adding search and filtering of modules. Not used categories/labels commented in code
Close QualityUnit/web-issues#1432
=> [1432] modules filtering

admin/src/tables/GeneratorResultTable.jsx
Close https://github.com/QualityUnit/web-issues/issues/1518
=> fix: lang column not used - removed

admin/src/components/EditRowPanel.jsx, admin/src/tables/NotFoundTable.jsx
=> [1523] fix: redirect

includes/widgets/class-urlslab-content-generator-widget.php, includes/widgets/class-urlslab-lazy-loading.php
**Checklist**
Close QualityUnit/web-issues#1525
=> feat: option to format video attribute as html from shortcode

admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/tables/CreditsTable.jsx, admin/src/tables/NotFoundTable.jsx
Refresh Redirects table on adding 404 new redirect, Credits table sorting and date formatting added
Close QualityUnit/web-issues#1523
=> [1523] redirect refresh

includes/api/class-urlslab-api-cache-rules.php, includes/widgets/class-urlslab-cache.php
Close https://github.com/QualityUnit/web-issues/issues/1531
=> feat: drop cloudfront cache, invalidate cache on each post save

admin/src/assets/styles/elements/_SuggestedInputField.scss, admin/src/components/SettingsOption.jsx, admin/src/elements/SuggestInputField.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/NotFoundTable.jsx, admin/src/tables/RedirectsTable.jsx
integrating suggestions to keywords manager and redirects
=> [1461] feat: integrating suggestions to keywords manager and redirects

includes/widgets/class-urlslab-screenshot-widget.php
Close https://github.com/QualityUnit/web-issues/issues/1540
=> fix: screenshot settings validator

admin/src/assets/styles/common/_mixins.scss, admin/src/assets/styles/elements/_Inputs.scss, admin/src/assets/styles/layouts/_Header.scss, admin/src/components/Header.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/components/OverviewTemplate.jsx, admin/src/elements/Checkbox.jsx, admin/src/elements/SuggestInputField.jsx, admin/src/modules/TagsLabels.jsx, admin/src/tables/CacheRulesTable.jsx, admin/src/tables/CustomHtmlTable.jsx, admin/src/tables/GeneratorResultTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/NotFoundTable.jsx, admin/src/tables/RedirectsTable.jsx, admin/src/tables/SchedulesTable.jsx, admin/src/tables/ScreenshotTable.jsx, admin/src/tables/SearchReplaceTable.jsx, admin/src/tables/URLRelationTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
Popup showing on table scroll/rerender, fix for multiple selected items in single select
Close QualityUnit/web-issues#1532
Close QualityUnit/web-issues#1541
Close QualityUnit/web-issues#1542
=> [1532] Popup showing

includes/api/class-urlslab-api-youtube-cache.php, includes/data/class-urlslab-data.php, includes/data/class-urlslab-youtube-row.php, includes/widgets/class-urlslab-content-generator-widget.php, includes/widgets/class-urlslab-lazy-loading.php
- validate videoid
- decline invalid videoids
- don't import invalid videoids
Close https://github.com/QualityUnit/web-issues/issues/1545
=> fix: videoid validation

includes/class-urlslab.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1548
=> fix: adding custom header html

includes/api/class-urlslab-api-keywords.php, includes/class-urlslab.php
improve search in suggestions
Close QualityUnit/web-issues#1549
=> search in kw suggestions improved

admin/src/tables/NotFoundTable.jsx
Close https://github.com/QualityUnit/web-issues/issues/1550
=> feat: improve suggestions of not found redirect

includes/cron/class-urlslab-screenshots-cron.php
Close https://github.com/QualityUnit/web-issues/issues/1552
=> fix: updated urlslab api

admin/src/tables/KeywordsTable.jsx
removed required attribute on fields - it was not working and form was not possible to submit
Close https://github.com/QualityUnit/web-issues/issues/1553
=> fix: adding kw priority

includes/widgets/class-urlslab-cache.php, includes/widgets/class-urlslab-widget.php
+ fix to compute default url from canonical url
Close https://github.com/QualityUnit/web-issues/issues/1557
=> feat: short time to live and default cache ttl

includes/widgets/class-urlslab-link-enhancer.php
Close https://github.com/QualityUnit/web-issues/issues/1572
=> feat: urlslab_url_attribute and urlslab_url_attributes

includes/widgets/class-urlslab-related-resources-widget.php
=> chore: debug html comment

admin/src/assets/styles/components/_FloatingPanel.scss, admin/src/assets/styles/components/_ModuleViewHeader.scss, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/elements/Tooltip_SortingFiltering.jsx, admin/src/hooks/filteringSorting.jsx, admin/src/hooks/useInfiniteFetch.jsx
filtering menu visible on hidden columns of that type
row count updated on filtering
Close QualityUnit/web-issues#1567
Close QualityUnit/web-issues#1568
=> [1568] fix: filtering menu visible on hidden columns of that type

admin/src/components/DetailsPanel.jsx
export button for url details panel (outgoing links)
Close QualityUnit/web-issues#1575
=> [1575] feat: export button for url details panel (outgoing links)

admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/hooks/useChangeRow.jsx
fixing delete selected function
Close QualityUnit/web-issues#1570
=> [1570] fix: fixing delete selected function

admin/src/components/EditRowPanel.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/elements/SingleSelectMenu.jsx, admin/src/tables/SchedulesTable.jsx
Fixed bug in single select menu when defaultAccept prop has been used it rewrote all previously entered values in Edit/Add row panel
Close QualityUnit/web-issues#1586
=> [1586] fix: bug when defaultvalue prop on single select menu

admin/src/components/DetailsPanel.jsx, admin/src/components/EditRowPanel.jsx, admin/src/components/ImportPanel.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/hooks/useCloseModal.jsx, admin/src/tables/KeywordsTable.jsx
multiple bug fixes for adding new items to table
Close QualityUnit/web-issues#1590
Close QualityUnit/web-issues#1591
Close QualityUnit/web-issues#1592
=> [1591] fix: multiple bug fixes for adding new items to table

includes/api/class-urlslab-api-keywords.php
Close https://github.com/QualityUnit/web-issues/issues/1593
=> fix: sql should accept url_id parameter

includes/api/class-urlslab-api-keywords.php, includes/class-urlslab-url.php, includes/cron/class-urlslab-generators-cron.php, includes/widgets/class-urlslab-cache.php, includes/widgets/class-urlslab-content-generator-widget.php, includes/widgets/class-urlslab-custom-html.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-link-enhancer.php, includes/widgets/class-urlslab-media-offloader-widget.php, includes/widgets/class-urlslab-meta-tag.php, includes/widgets/class-urlslab-related-resources-widget.php, includes/widgets/class-urlslab-screenshot-widget.php, includes/widgets/class-urlslab-search-replace.php, includes/widgets/class-urlslab-widget.php
Close https://github.com/QualityUnit/web-issues/issues/1596
=> fix: urls with query parameters should be handled correctly

admin/src/tables/ScreenshotTable.jsx
removed screenshot_thumbnail_url from filters
Close QualityUnit/web-issues#1585
=> [1585] fix: removed screenshot_thumbnail_url from filters

includes/widgets/class-urlslab-related-resources-widget.php
Close https://github.com/QualityUnit/web-issues/issues/1603
=> fix: show related articles just on singular pages of specific post type

includes/data/class-urlslab-url-row.php, includes/widgets/class-urlslab-cache.php, includes/widgets/class-urlslab-image-alt-text.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-link-enhancer.php, includes/widgets/class-urlslab-media-offloader-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1599
=> fix: exclude from processing admin toolbar

composer.lock, includes/class-urlslab.php
disabled urlslab processing with sitemap pages based on yoast sitemap parsing
**Checklist**
Close QualityUnit/web-issues#1606
=> fixed the bug with sitemap

docker/dev/docker-compose.yaml, docker/dev/wordpress.dockerfile, includes/cron/class-urlslab-download-css-cron.php, includes/widgets/class-urlslab-css-optimizer.php, vendor/composer/ClassLoader.php, vendor/composer/autoload_real.php
Fixed bug with css optimizer
**Checklist**
Close QualityUnit/web-issues#1587
=> Fixed bug with css optimizer

includes/class-urlslab-url.php, includes/cron/class-urlslab-download-css-cron.php
**Checklist**
Close QualityUnit/web-issues#1587
=> header theme bugfix

includes/api/class-urlslab-api-generators.php, includes/class-urlslab-yt-helper.php, includes/class-urlslab.php, includes/cron/class-urlslab-youtube-cron.php
youtube transcription endpoint
**Checklist**
Close QualityUnit/web-issues#1618
=> Youtube Transcription endpoint

includes/cron/class-urlslab-update-url-http-status-cron.php
Bug Fix for URSLAB HTTP Status cron
**Checklist**
Close QualityUnit/web-issues#1571
=> Bug Fix for urlslab HTTP Status

admin/src/components/SettingsOption.jsx, includes/api/class-urlslab-api-settings.php, includes/cron/class-urlslab-optimize-cron.php, includes/widgets/class-urlslab-optimize.php
Fixed the bug with time sync
**Checklist**
Close QualityUnit/web-issues#1371
=> Time Sync Bug fix

includes/api/class-urlslab-api-settings.php, includes/widgets/class-urlslab-widget.php
=> Bug fix with Switches

.github/scripts/build-files.sh
=> urlslab-sdk_fix

admin/src/assets/styles/components/_Panel.scss, admin/src/assets/styles/components/_UnifiedPanelMenu.scss, admin/src/components/ColorPicker.jsx, admin/src/components/DangerPanel.jsx, admin/src/components/DetailsPanel.jsx, admin/src/components/EditRowPanel.jsx, admin/src/components/ExportPanel.jsx, admin/src/components/ImportPanel.jsx, admin/src/components/ModuleViewHeaderBottom.jsx, admin/src/components/TablePanels.jsx, admin/src/components/UnifiedPanelMenu.jsx, admin/src/elements/Button.jsx, admin/src/elements/InputField.jsx, admin/src/elements/SearchField.jsx, admin/src/elements/TableActionsMenu.jsx, admin/src/hooks/useCloseModal.jsx, admin/src/hooks/useTablePanels.jsx, admin/src/tables/CacheRulesTable.jsx, admin/src/tables/GeneratorResultTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/ScreenshotTable.jsx, admin/src/tables/YouTubeCacheTable.jsx
Unified popup panel for Edit and link usage
Close QualityUnit/web-issues#1433
=> [1433] Unified popup

admin/src/tables/GeneratorResultTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx
Editor for generator results table
Close QualityUnit/web-issues#1477
=> [1477] Editor generator results

admin/src/app-ai-content-assistant/src/elements/JSXElements.tsx, admin/src/assets/styles/elements/_Inputs.scss, admin/src/components/DetailsPanel.jsx, admin/src/elements/Editor.jsx, admin/src/elements/InputField.jsx, admin/src/elements/MultiSelectMenu.jsx, admin/src/elements/SingleSelectMenu.jsx, admin/src/elements/SuggestInputField.jsx, admin/src/elements/TagsMenu.jsx, admin/src/elements/Textarea.jsx, admin/src/tables/GeneratorResultTable.jsx
mandatory/required field marked with red start and tooltip, overflowing in Generator Results, URL details popup table adding rows from other request fix
Close QualityUnit/web-issues#1638
=> [1638] feat: required field info added, fixing few bugs

composer.lock, includes/api/class-urlslab-api-urls.php, includes/class-urlslab.php, includes/data/class-urlslab-url-row.php, includes/urlslab-helper.php
=> Added screenshot to history api

includes/widgets/class-urlslab-lazy-loading.php
=> fix: lazy content loading

admin/src/components/SettingsOption.jsx
Options in settings may call callback fn after successful save.
For api key option added callback to refresh credits.
Credits should be refetched after successful save of api key option.
**Checklist**
Close QualityUnit/web-issues#1637
=> [Bug]: Reload the number of credits when I add/update API key

includes/class-urlslab.php, includes/widgets/class-urlslab-lazy-loading.php, includes/widgets/class-urlslab-search-replace.php
Close https://github.com/QualityUnit/web-issues/issues/1653
=> feat: HTML minification

.github/scripts/build-files-dev.sh, README.md
=> Updating Readme

composer.lock, includes/api/class-urlslab-api-css-cache.php, includes/widgets/class-urlslab-cache.php, includes/widgets/class-urlslab-html-optimizer.php
cache merged css files from DB to file
https://github.com/QualityUnit/web-issues/issues/1654
=> feat: minified css cache to file

admin/src/components/DetailsPanel.jsx, admin/src/components/UnifiedPanelMenu.jsx
url details panel bug
Close QualityUnit/web-issues#1670
=> [1670] fix: url details panel

includes/cron/class-urlslab-download-css-cron.php, includes/cron/class-urlslab-download-js-cron.php
Close QualityUnit/web-issues#1685
=> fix: undefined variable warning

includes/api/class-urlslab-api-schedules.php, includes/cron/class-urlslab-download-css-cron.php, includes/cron/class-urlslab-download-js-cron.php
Close https://github.com/QualityUnit/web-issues/issues/1686
=> trim received array and not string

includes/widgets/class-urlslab-html-optimizer.php
Close https://github.com/QualityUnit/web-issues/issues/1688
=> fix: chatch exception

.github/scripts/build-files.sh
not sure if it helps - I don't know how to test this change
Close https://github.com/QualityUnit/web-issues/issues/1689
=> fix: missing file in vendor

includes/class-urlslab.php, includes/widgets/class-urlslab-html-optimizer.php
Close https://github.com/QualityUnit/web-issues/issues/1691
=> fix: minifyu just html files

includes/widgets/class-urlslab-html-optimizer.php
Close QualityUnit/web-issues#1690
=> fix: skip processing wordfence javascript tag

includes/widgets/class-urlslab-search-replace.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1692
=> fix: undefined array key

includes/cron/class-urlslab-download-css-cron.php
Close https://github.com/QualityUnit/web-issues/issues/1693
=> fix: absolute path normalization

includes/class-urlslab-url.php, includes/widgets/class-urlslab-link-enhancer.php
Close https://github.com/QualityUnit/web-issues/issues/1694
=> feat: fix link protocol

includes/widgets/class-urlslab-html-optimizer.php
new options for minification of HTML
Close https://github.com/QualityUnit/web-issues/issues/1696
=> feat: configurable minification of HTML

includes/widgets/class-urlslab-html-optimizer.php
Close https://github.com/QualityUnit/web-issues/issues/1701
=> fix: keep order of merged files

includes/widgets/class-urlslab-html-optimizer.php
=> remove js merge feature - it was not working as expected

admin/src/assets/styles/elements/_Tooltip.scss, admin/src/components/ChangesPanel/ChangesPanel.jsx
added tooltip preview on changes panel
=> [1684] fix: added tooltip preview on changes panel

admin/src/elements/SuggestInputField.jsx
Fixed bug mentioned in related issue
**Checklist**
Close QualityUnit/web-issues#1719
=> fix: missing localization function

admin/src/assets/styles/components/_Panel.scss
Fixed table height in modal popup.
Close QualityUnit/web-issues#1720
=> [Bug]: Usage Popup doesn't show data

admin/src/assets/styles/components/_ImageCompare.scss, admin/src/components/ImageCompare.jsx
=> changed text and close button position

includes/api/class-urlslab-api-cache-rules.php
Close https://github.com/QualityUnit/web-issues/issues/1728
=> fix: with drop of cloudfront cache will be droped also all cache files

includes/class-urlslab.php, includes/cron/class-urlslab-update-url-http-status-cron.php, includes/widgets/class-urlslab-faq.php, includes/widgets/class-urlslab-html-optimizer.php, includes/widgets/class-urlslab-lazy-loading.php
Close https://github.com/QualityUnit/web-issues/issues/1726
=> fix: don't remove http(s) from urls in head - e.g. canonical should keep protocol

includes/widgets/class-urlslab-link-enhancer.php, includes/widgets/class-urlslab-related-resources-widget.php
- if post updated, update status
- don't include in related resources urls without correct status
Close https://github.com/QualityUnit/web-issues/issues/1734
Close https://github.com/QualityUnit/web-issues/issues/1743
=> fix: deleted page should not be in related resources

includes/class-urlslab-activator.php
=> fix: sql error in create script

includes/class-urlslab-activator.php, includes/cron/class-urlslab-update-url-http-status-cron.php, includes/data/class-urlslab-url-row.php, includes/widgets/class-urlslab-link-enhancer.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/1727
=> feat: add hreflang attribute if avalable in url

includes/cron/class-urlslab-update-url-http-status-cron.php
- blacklisted domains set as valid without check
- invalid urls set as error without check
=> feat: skip validation of blacklisted domains or invalid urls

includes/cron/class-urlslab-update-url-http-status-cron.php
Close https://github.com/QualityUnit/web-issues/issues/1745
=> feat: detect content language of url

admin/src/tables/LinkManagerTable.jsx, admin/src/tables/URLRelationTable.jsx, includes/api/class-urlslab-api-cache-rules.php, includes/api/class-urlslab-api-content-cache.php, includes/api/class-urlslab-api-css-cache.php, includes/api/class-urlslab-api-custom-html.php, includes/api/class-urlslab-api-faq-urls.php, includes/api/class-urlslab-api-faq.php, includes/api/class-urlslab-api-files.php, includes/api/class-urlslab-api-generators.php, includes/api/class-urlslab-api-js-cache.php, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-labels.php, includes/api/class-urlslab-api-not-found-log.php, includes/api/class-urlslab-api-redirects.php, includes/api/class-urlslab-api-search-replace.php, includes/api/class-urlslab-api-shortcodes.php, includes/api/class-urlslab-api-table.php, includes/api/class-urlslab-api-url-relations.php, includes/api/class-urlslab-api-urls.php, includes/api/class-urlslab-api-youtube-cache.php, includes/class-urlslab-activator.php, includes/cron/class-urlslab-related-resources-cron.php, includes/data/class-urlslab-url-relation-row.php, includes/data/class-urlslab-url-row.php, includes/widgets/class-urlslab-related-resources-widget.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/1749
=> related resources locking and url seo priority

admin/src/hooks/useChangeRow.jsx
update function now accepts true/false values as well, only ignoring undefined
Close QualityUnit/web-issues#1755
=> [1755] fix: update function on checkbox true/false 

admin/src/tables/GeneratorShortcodeTable.jsx, includes/class-urlslab-activator.php, includes/widgets/class-urlslab-html-optimizer.php
Close https://github.com/QualityUnit/web-issues/issues/1757
=> fix: don't remove spaces between tags in body content, just in headers

admin/src/assets/styles/components/datepicker/_variables.scss, admin/src/assets/styles/components/datepicker/datepicker.scss, admin/src/assets/styles/elements/_MultiSelectMenu.scss
Font family changed to Poppins for selects and datepicker.
Not sure if it's worth to go through all tooltips on selects and check their width as poppins text is wider than open sans....
Close QualityUnit/web-issues#1748
=> Change the Font Family

admin/src/assets/styles/components/_Panel.scss, admin/src/assets/styles/elements/_MultiSelectMenu.scss, admin/src/components/ChangesPanel/ChangesPanel.jsx, admin/src/tables/GeneratorShortcodeTable.jsx
Fixed popup overflow on small displays
Close QualityUnit/web-issues#1741
=> [1741] fix: popup on small displays

includes/widgets/class-urlslab-faq.php
trim input value of question and answer
don't import FAQ with empty answer or question
Close https://github.com/QualityUnit/web-issues/issues/1762
=> fix: trim values imported from page

includes/widgets/class-urlslab-html-optimizer.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-link-enhancer.php
https://github.com/QualityUnit/web-issues/issues/1758
=> fix: minification of spaces between tags, handling of duplicate links

includes/widgets/class-urlslab-html-optimizer.php, includes/widgets/class-urlslab-keywords-links.php, includes/widgets/class-urlslab-link-enhancer.php
Close https://github.com/QualityUnit/web-issues/issues/1758
=> spacing between links fixed

admin/src/tables/FaqUrlsTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/URLRelationTable.jsx, includes/api/class-urlslab-api-faq-urls.php, includes/api/class-urlslab-api-keywords.php, includes/api/class-urlslab-api-url-relations.php, includes/api/class-urlslab-api-urls.php, includes/class-urlslab-activator.php, includes/data/class-urlslab-url-row.php, includes/widgets/class-urlslab-related-resources-widget.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/1760
=> feat: unify priorities of entities as seo rank field with values 0 - 100

admin/src/modules/Serp.jsx, admin/src/tables/SerpTopDomainsTable.jsx, includes/api/class-urlslab-api-serp-domains.php, includes/class-urlslab-api-router.php, includes/data/class-urlslab-serp-domain-row.php, includes/widgets/class-urlslab-serp.php
- simple report - list of competitor domains
=> feat: top competitors

admin/class-urlslab-admin.php
fixed react minified error in console
Close QualityUnit/web-issues#1669
=> [Bug] React minified error

admin/src/tables/MediaFilesTable.jsx, includes/api/class-urlslab-api-files.php, includes/cron/class-urlslab-offload-transfer-files-cron.php, includes/driver/class-urlslab-driver.php, includes/widgets/class-urlslab-media-offloader-widget.php
**Checklist**
Close https://github.com/QualityUnit/web-issues/issues/1501
=> chore: hide S3 related features

admin/src/tables/SerpQueriesTable.jsx, admin/src/tables/SerpTopDomainsTable.jsx, includes/api/class-urlslab-api-serp-domains.php, includes/api/class-urlslab-api-serp-queries.php, includes/class-urlslab-activator.php, includes/cron/class-urlslab-serp-cron.php, includes/data/class-urlslab-serp-domain-row.php, includes/data/class-urlslab-serp-query-row.php, includes/widgets/class-urlslab-serp.php, urlslab.php
https://github.com/QualityUnit/web-issues/issues/1763
=> feat: domain types, query types

admin/src/modules/Serp.jsx, admin/src/tables/SerpTopDomainsTable.jsx, includes/api/class-urlslab-api-serp-domains.php, includes/data/class-urlslab-serp-domain-row.php
https://github.com/QualityUnit/web-issues/issues/1763
=> feat: add serp domains manually

includes/class-urlslab-url.php
m.me should be blackliste url
Close https://github.com/QualityUnit/web-issues/issues/1643
=> fix: m.me should be blacklisted url

admin/src/lib/filterOperators.js, admin/src/modules/Serp.jsx, admin/src/tables/GscSitesTable.jsx, admin/src/tables/SerpGapTable.jsx, admin/src/tables/SerpUrlsTable.jsx, includes/api/class-urlslab-api-serp-domains.php, includes/api/class-urlslab-api-serp-gap.php, includes/api/class-urlslab-api-serp-urls.php, includes/class-urlslab-activator.php, includes/class-urlslab-api-router.php, includes/cron/class-urlslab-gsc-cron.php, includes/cron/class-urlslab-serp-cron.php, includes/data/class-urlslab-serp-query-row.php, includes/widgets/class-urlslab-serp.php
https://github.com/QualityUnit/web-issues/issues/1763
=> Content Gap Report

includes/api/class-urlslab-api-serp-queries.php
https://github.com/QualityUnit/web-issues/issues/1763#issuecomment-1654155358
=> api kw cluster

admin/src/tables/SerpGapTable.jsx, includes/api/class-urlslab-api-serp-domains.php, includes/cron/class-urlslab-serp-cron.php, includes/data/class-urlslab-serp-domain-row.php
https://github.com/QualityUnit/web-issues/issues/1789
=> fix sql if empty serp domains

admin/src/components/TableFilter.jsx, admin/src/components/TableFilterPanel.jsx
fixed bug when app failed on in between value
Close QualityUnit/web-issues#1786
=> [1786] fix: error on between range

admin/src/hooks/useChangeRow.jsx
getting proper row id to change value for
=> fix: getting proper row id to change value for

admin/src/components/TableFilter.jsx
Fixed error in range table filter "is between".
Add filter for number value in table (ie. Link Building module). Added filter should not cause error.
Close QualityUnit/web-issues#1786
=> [Bug]: Table filter "is between" error

admin/src/tables/SerpGapTable.jsx
Close https://github.com/QualityUnit/web-issues/issues/1794
=> fix: remove add button - not needed in this table

includes/widgets/class-urlslab-lazy-loading.php
Close https://github.com/QualityUnit/web-issues/issues/1793
=> fix: remove attribute loading=lazy

includes/widgets/class-urlslab-faq.php
Close https://github.com/QualityUnit/web-issues/issues/1795
=> fix: warning in faq import

includes/api/class-urlslab-api-faq-urls.php, includes/api/class-urlslab-api-faq.php
just soting validato was wong
Close https://github.com/QualityUnit/web-issues/issues/1807
=> fix: sorting validato fixed

includes/cron/class-urlslab-serp-cron.php
Close https://github.com/QualityUnit/web-issues/issues/1803
=> fix: fist character uppercase

includes/cron/class-urlslab-serp-cron.php
**Checklist**
Close QualityUnit/web-issues#1813
=> Bug Fix for duplicate serp reduction

composer.lock
=> Composer update of all deps

includes/widgets/class-urlslab-faq.php
=> Fixed bug with faq

includes/api/class-urlslab-api-faq-urls.php, includes/data/class-urlslab-faq-url-row.php
**Checklist**
Close QualityUnit/web-issues#1816
=> Fix for URL Assignment

admin/src/components/SettingsOption.jsx
multiple radio checkboxes in single select settings
Close QualityUnit/web-issues#1817
=> [1817] fix: multiple radio checkboxes in single select settings

admin/src/components/EditRowPanel.jsx, admin/src/hooks/useChangeRow.jsx, admin/src/modules/static/TagsLabels.jsx, admin/src/tables/CSSCacheTable.jsx, admin/src/tables/CacheRulesTable.jsx, admin/src/tables/CustomHtmlTable.jsx, admin/src/tables/FaqUrlsTable.jsx, admin/src/tables/FaqsTable.jsx, admin/src/tables/GeneratorResultTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx, admin/src/tables/JSCacheTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/LinkManagerTable.jsx, admin/src/tables/MediaFilesTable.jsx, admin/src/tables/NotFoundTable.jsx, admin/src/tables/RedirectsTable.jsx, admin/src/tables/SchedulesTable.jsx, admin/src/tables/ScreenshotTable.jsx, admin/src/tables/SearchReplaceTable.jsx, admin/src/tables/SerpQueriesTable.jsx, admin/src/tables/URLRelationTable.jsx, admin/src/tables/YouTubeCacheTable.jsx, includes/api/class-urlslab-api-faq-urls.php
easier to show row action buttons (edit, delete etc), faq assignment editing
=> [1808] fix: faq assignment editing

includes/api/class-urlslab-api-faq-urls.php, includes/api/class-urlslab-api-faq.php, includes/data/class-urlslab-faq-url-row.php
=> fixed bugs in faq

admin/src/components/generator/ContentGeneratorConfigPanel.jsx
=> Bug Fix Prompt

includes/widgets/class-urlslab-content-generator-widget.php
Close https://github.com/QualityUnit/web-issues/issues/1859
=> fix: hide wpml settings if wpml not available

admin/src/data/promptTemplates.json, admin/src/tables/SerpGapTable.jsx
=> Added Serp Integration

admin/src/assets/styles/components/_ChangesPanel.scss, admin/src/components/DeleteFilteredPanel.jsx, admin/src/components/ImportPanel.jsx, admin/src/components/RowCounter.jsx, admin/src/elements/ColumnsMenu.jsx, admin/src/elements/ExportCSVButton.jsx, admin/src/hooks/useTablePanels.jsx
fixes: 
#1818 – disable panel button on export/import/delete filtered
#1819 – row counter on table refresh
#1820 – columns menu
Close QualityUnit/web-issues#1818
Close QualityUnit/web-issues#1819
Close QualityUnit/web-issues#1820
=> [1818] fix: fixes for 1818, 1819, 1820

includes/api/class-urlslab-api-serp-domains.php, includes/api/class-urlslab-api-serp-queries.php
Close https://github.com/QualityUnit/web-issues/issues/1798
=> fix: edit permissions for serp features

admin/src/tables/SerpTopDomainsTable.jsx, includes/api/class-urlslab-api-serp-domains.php, includes/data/class-urlslab-serp-domain-row.php
Close https://github.com/QualityUnit/web-issues/issues/1796
=> feat: new domain type - ignored

includes/widgets/class-urlslab-faq.php
=> Added insert ignore

admin/src/api/generatorApi.js, admin/src/components/generator/ContentGeneratorConfigPanel.jsx, admin/src/elements/SuggestInputField.jsx, admin/src/hooks/useAIGenerator.jsx, admin/src/lib/aiGeneratorPanel.js, admin/src/lib/helpers.js, admin/src/modules/Generator.jsx, admin/src/queries/useAIModelsQuery.jsx, admin/src/tables/FaqsTable.jsx, admin/src/tables/GeneratorPromptTemplateTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/NotFoundTable.jsx, admin/src/tables/RedirectsTable.jsx, includes/api/class-urlslab-api-generators.php, includes/api/class-urlslab-api-prompt-template.php, includes/class-urlslab-activator.php, includes/class-urlslab-api-router.php, includes/class-urlslab.php, includes/data/class-urlslab-prompt-template-row.php, includes/defaults/class-urlslab-default-prompt-template.php, table-names.php, urlslab.php
=> Prompt Template Implementation

admin/src/lib/aiGeneratorPanel.js, admin/src/tables/URLRelationTable.jsx, includes/api/class-urlslab-api-base.php, includes/api/class-urlslab-api-serp-domains.php, includes/api/class-urlslab-api-serp-queries.php, includes/api/class-urlslab-api-url-relations.php, includes/class-urlslab-serp-connection.php, includes/cron/class-urlslab-serp-cron.php
=> Bug fix for deleting selection Rows

includes/class-urlslab-activator.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/1876
=> feat: add index on domain type in serp domains

admin/src/tables/SerpGapTable.jsx, admin/src/tables/SerpQueriesTable.jsx
Close https://github.com/QualityUnit/web-issues/issues/1870
=> chore: renamed types of queries

admin/src/tables/SerpGapTable.jsx, admin/src/tables/SerpQueriesTable.jsx, includes/api/class-urlslab-api-serp-queries.php, includes/class-urlslab-activator.php, includes/data/class-urlslab-serp-query-row.php, urlslab.php
Close https://github.com/QualityUnit/web-issues/issues/1804
=> feat: add tags to serp queries

admin/src/components/ImageCompare.jsx
=> active Screen back to Overlay

admin/src/modules/Serp.jsx, admin/src/tables/SerpCompetitorsTable.jsx, includes/api/class-urlslab-api-serp-competitors.php, includes/api/class-urlslab-api-table-sql.php, includes/class-urlslab-api-router.php
Close https://github.com/QualityUnit/web-issues/issues/1878
=> feat: Competitors table

admin/src/assets/images/icons/icon-addTag.svg, admin/src/assets/styles/elements/_TagsMenu.scss, admin/src/assets/styles/elements/_Tooltip.scss, admin/src/components/ChangesPanel/Chart.jsx, admin/src/components/DetailsPanel.jsx, admin/src/components/EditRowPanel.jsx, admin/src/components/ImageCompare.jsx, admin/src/components/TableFilterPanel.jsx, admin/src/elements/DateRangeButton.jsx, admin/src/elements/DateTimeFormat.jsx, admin/src/elements/TagsMenu.jsx, admin/src/hooks/useTablePanels.jsx, admin/src/lib/helpers.js, admin/src/tables/CacheRulesTable.jsx, admin/src/tables/CustomHtmlTable.jsx, admin/src/tables/FaqsTable.jsx, admin/src/tables/GeneratorShortcodeTable.jsx, admin/src/tables/KeywordsTable.jsx, admin/src/tables/MetaTagsTable.jsx, admin/src/tables/NotFoundTable.jsx, admin/src/tables/RedirectsTable.jsx, admin/src/tables/SearchReplaceTable.jsx, admin/src/tables/SerpQueriesTable.jsx
Fixes for #1839, #1848, #1852, #1857, #1871, #1872, #1873
Close QualityUnit/web-issues#1839
Close QualityUnit/web-issues#1848
Close QualityUnit/web-issues#1852
Close QualityUnit/web-issues#1857
Close QualityUnit/web-issues#1871
Close QualityUnit/web-issues#1872
Close QualityUnit/web-issues#1873
=> fix: Multiple bugfixes v4
